### ISSUE TITLE
Add ignore option to length-zero-no-unit when used with calc()

### ISSUE THREAD

**Issue by stevethemacguy** [stylelint/stylelint#3666] opened 2018-09-12 20:06 UTC
> What is the problem you're trying to solve?

Allow for a '0px' property value within calc(). The W3 spec states that a unit identifier is optional for zero lengths (see https://www.w3.org/TR/css3-values/#lengths), but not all browsers currently support this spec within calc(). For example, calc(0 + 24px) will fail in in IE 11. In Chrome, the value is correctly computed, but an 'invalid property value' warning is shown in the Chrome DevTools.

Some CSS minifiers correct this issue by removing calc() from the final CSS (e.g. cssnano), but others do not (e.g. clean-css). See https://cssnano.co/optimisations/calc/

> What solution would you like to see?

Add an option to ignore the length-zero-no-unit rule when used with calc().  A related issue (#2522) was already discussed and closed. Unlike #2522, however, this is not just a bug in IE.

**Comment by hudochenkov** [comment] 2018-09-12 20:59
Duplicate of https://github.com/stylelint/stylelint/issues/3037. Please, consider [contributing](https://stylelint.io/developer-guide/rules/#adding-an-option-to-an-existing-rule).

**Closed by hudochenkov** 2018-09-12 20:59 UTC
