### ISSUE TITLE
Fix autofix duplicated properties within comments

### ISSUE THREAD

**Issue by Zotova2008** [stylelint/stylelint#7429] opened 2023-12-28 19:02 UTC
### What minimal example or steps are needed to reproduce the bug?

Scss. Основной форматировщик выбран Stylelint. 
В настройках прописаны свойства.
Включение и отключение стандартного валидатора не влияет на ситуацию

(Scss. The main formatter selected is Stylelint.
The properties are specified in the settings.
Enabling and disabling the standard validator does not affect the situation)

```
"stylelint.enable": true,
"stylelint.validate": [
	"css",
	"less",
	"postcss",
	"scss",
	"sass"
],
```

 при сохранении Stylelint начинает дублировать закомментированные свойства, при чем сколько раз сохранишь, столько же и добавит

(when saving, Stylelint begins to duplicate the commented out properties, and no matter how many times you save, the same number will be added)

![1](https://github.com/stylelint/stylelint/assets/30495506/ecb78ba1-c344-4104-8e12-db6bed0e302f)
![2](https://github.com/stylelint/stylelint/assets/30495506/07b97b1d-6a88-419b-93eb-c6f83cab7d9e)

### What minimal configuration is needed to reproduce the bug?

```
{
"[scss]": {
	"editor.defaultFormatter": "stylelint.vscode-stylelint"
},
"stylelint.enable": true,
"stylelint.validate": [
	"css",
	"less",
	"postcss",
	"scss",
	"sass"
],
}
```

### How did you run Stylelint?

VS Code плагин Stylelint

(VS Code plugin Stylelint)

### Which Stylelint-related dependencies are you using?

```
{
"stylelint": "16.1.0",
"stylelint-config-htmlacademy": "^4.0.1",
}
```

### What did you expect to happen?

Ожидалось, что при сохранении файл отформатируется без дублирования свойств 

(It was expected that when saving the file would be formatted without duplicating properties)

### What actually happened?

Дублируются закомментрированные свойства

(Commented out properties are duplicated)

### Do you have a proposal to fix the bug?

Как исправить не знаю

(I don’t know how to fix it)

**Comment by jeddy3** [comment] 2023-12-29 20:20
@Zotova2008 Thanks for the report and for using the template. I've added a translation to your issue.

Please create a minimum reproducible example so that we can best help you.

Firstly, can you confirm this is an issue using the Stylelint CLI?

If it is, then can you identify which part of the stylelint-config-htmlacademy config is triggering the problem as [it uses](https://github.com/htmlacademy/stylelint-config-htmlacademy/blob/master/.stylelintrc) the :

- postcss-less custom syntax
- postcss-scss custom syntax
- stylistic custom rules plugin pack

I suggest starting with just the built-in rules, if that fixes the issue, then add on the plugin pack, and then custom syntaxes. The issue maybe triggered the combination of a rule with one of the custom syntaxes.

We'll only be able to fix the issue here if it's with Stylelint or one of the built-in rules.

**Comment by Zotova2008** [comment] 2024-01-02 10:08
@jeddy3 Благодарю за перевод.

Stylelint настроен на автоматическое форматирование при сохранении файлов. 
Форматировщик по умолчанию - Stylelint

Убрала плагин с конфигурацией, 
![2](https://github.com/stylelint/stylelint/assets/30495506/3b4ffcdc-227f-4158-b8e0-af4ea9020343)

проблема повторилась и теперь двоятся свойства и при форматировании stylelint и при встроенном в vscode форматировании.
![1](https://github.com/stylelint/stylelint/assets/30495506/42879bd0-99fa-4781-9ecf-7f589e14eca6)

Когда вернула обратно файл конфигурации, 
```
"extends": [
  "stylelint-config-htmlacademy"
],
```
проблема осталась только при форматировщике по умолчанию - Stylelint

**Comment by r2musings** [comment] 2024-01-02 13:02
This happens for us as well. Will try to get together a small sample that reproduces outside of our larger codebase.

<img width="1737" alt="image" src="https://github.com/stylelint/stylelint/assets/2158785/2d6ebb72-75d8-4170-8564-f37882ca899c">

**Comment by jeddy3** [comment] 2024-01-02 13:07
> Will try to get together a small sample that reproduces outside of our larger codebase

Thank you. That'll help a lot.

**Comment by r2musings** [comment] 2024-01-02 16:37
Check readme for repro.  Basically, it happens when using "--fix".

https://github.com/r2musings/stylelint-comment-bug

**Comment by jeddy3** [comment] 2024-01-02 18:25
@r2musings Thank you. I was able to [reproduce a minimal demo](https://stylelint.io/demo/#N4Igxg9gJgpiBcID0SAEBhCBbLMB2ALqgO4CWBAFqpADYR7wA6eAAgG4CGATvKpzQFcYAbhAAaEADNSNGADkOuBCBgAPRQAdZAOlkBnPePD1pAc2XBmqVIxWqC+KHtu8A2les2QeggE9ZNKSEALSQeGbBPhx4UNxQth4AuswAvkZhZgBiEFxYHATKAFZ69EawGoaIlnjWtj7+MIGELl40+TA+tmIedX4BQQShJqSmkQTRsVzxCK3tneI93n2NA0PhI2MTccH6zjO2bQ7zqSApQA) using your repo.

A comment with a colon triggers it. However, this only occurs for the default syntax and [not for](https://stylelint.io/demo/#N4Igxg9gJgpiBcID0SAEBhCBbLMB2ALqgO4CWBAFqpADYR7wA6eAAgG4CGATvKpzQFcYAbhAAaEADNSNGADkOuBCBgAPRQAdZAOlkBnPePD1pAc2XBmqVIxWqC+KHtu8A2les2QeggE9ZNKSEALSQeGbBPhx4UNxQwfrOIB4AuswAvkZhZgBiEFxYHATKAFZ69EawGoaIlnjWtj7+MIGELl40RTA+tmIejX4BQQShJqSmkQTRsVxQ7badDj3i-d6DLcOj4eOT03EJ3Um8C13LGSDpQA) for postcss-less custom one. 

In your repo, [the Stylelint config is set up for vanilla CSS](https://github.com/r2musings/stylelint-comment-bug/blob/main/.stylelintrc.json). Can you configure it for Less to see it that helps, please:

```json
{ "extends": ["stylelint-config-standard-less"] }
```

@r2musings and @Zotova2008 If able, can you also share your complete Stylelint configuration files, please?

**Comment by r2musings** [comment] 2024-01-02 19:29
@jeddy3 That did fix it!  Thanks for looking at my demo and providing that solution.  I appreciate it!

**Comment by Zotova2008** [comment] 2024-01-03 09:42
```
{
  "extends": [
    "stylelint-config-htmlacademy"
  ],
  "overrides": [
    {
      "files": [
        "*.scss",
        "**/*.scss"
      ],
      "customSyntax": "postcss-scss"
    }
  ],
  "rules": {},
  "ignoreFiles": [
    "vendor/**/*.*"
  ]
}
```

**Comment by jeddy3** [comment] 2024-01-03 09:56
@Zotova2008 Thank you. The config looks okay.

Can you produce the problem using the CLI?

```console
npx stylelint "reboots.scss" --fix
```

**Comment by Zotova2008** [comment] 2024-01-03 18:33
> @Zotova2008Спасибо. Конфигурация выглядит нормально.
> 
> Можете ли вы создать проблему с помощью CLI?
> 
> ```
> npx stylelint "reboots.scss" --fix
> ```

нет, баг не воспроизводится, свойства не дублируются

**Comment by jeddy3** [comment] 2024-01-07 10:03
@Zotova2008 Thank you for confirming. It's either a bug with the VSCode extension or your local configuration. 

Check that you haven't got a `stylelint.config: {}` in your VSCode configuration file as that would override the `stylelint-config-htmlacademy` config where the custom syntax is set. 

I'll close the issue here as it's unlikely to be an issue with the stylelint package because the CLI works.

**Closed by jeddy3** 2024-01-07 10:03 UTC
Labels: status: needs clarification

**Comment by Zotova2008** [comment] 2024-01-10 06:55
Такой `stylelint.config: {}` настройки в vs code нет.
