### ISSUE TITLE
Unexcepted semicolon when use stylelint-config-recess-order and stylelint-stylus

### ISSUE THREAD

**Issue by gapkukb** [stylelint/stylelint#7858] opened 2024-07-18 10:47 UTC
### What minimal example or steps are needed to reproduce the bug?
```
// css.styl
body
  color red
  font-weight 100
  ```
// vscode will format by auto save fix,will get unexcepted semiconlon on the which one property be reordered
```
body
  font-weight 100;
  color red
```
### What minimal configuration is needed to reproduce the bug?
```
module.exports={
extends:[
 'stylelint-stylus/standard',
 'stylelint-config-recess-order'
]
}
```
### How did you run Stylelint?

vscode stylelint extension auto save fix

### Which Stylelint-related dependencies are you using?
```
stylelint:16.7.0
stylelint-config-recess-order:5.0.1
stylelint-stylus:1.0.0
```
### What did you expect to happen?

without semicolon at the standard rule

### What actually happened?

will get a semicolon at the rule which one reorder by 'stylelint-config-recess-order plugin' on first save action on vscode,
but if save agian ,  vscode will fix again and works good;

**Comment by ybiquitous** [comment] 2024-07-21 02:42
@gapkukb Thanks for the report. I confirm the behavior in [this demo](https://stylelint.io/demo/#N4Igxg9gJgpiBcIBG0CeAdAdgAm5ANhAE7ZExRa4BmEmALgLQDuMAlgOYAWd2AjAAz8QAGhBVW+GADkAhgFs4iGAA95AB0kA6AM51U+EeFrj2CEMErZ0IFXRiYo26-GwBtS7mu79MfK3oM3vgArtoA9LoyDjJEFCIeViBBvv6MkJgmDGRgMNraDMSwRNaWALpYAL6G6SYAYsRyMnRmAFbatIawatpmFjiJyX70zom8AGyaAOya-NbCll56kkNpxhxZMDl5BbEwxQiJAKwzmrxzC0lLKQFBoSPWvCezIJUgFUA).

```
Expected "font-weight" to come before "color" (order/properties-order)
```

But I'm not sure if this insertion of an extra semicolon is caused by Stylelint, the [stylelint-order](https://github.com/hudochenkov/stylelint-order) plugin, or [stylelint-stylus](https://github.com/stylus/stylelint-stylus). 🤔

**Comment by jeddy3** [comment] 2024-12-13 17:37
Closing as unlikely an issue with Stylelint itself, but rather with the stylus custom syntax or the order plugin. @gapkukb If you have time, I suggest starting your investigation in either of those places.

**Closed by jeddy3** 2024-12-13 17:37 UTC
Labels: status: needs investigation
