### ISSUE TITLE
SCSS files inside `node_modules` are not being ignored

### ISSUE THREAD

**Issue by asumaran** [stylelint/stylelint#3005] opened 2017-11-05 06:17 UTC
First of all, I've created a repo where we can reproduce the bug  https://github.com/asumaran/stylelintbug

> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

This is a bug since the documentation says `stylelint` will [ignore `node_modules` by default](https://stylelint.io/user-guide/node-api/#files) but it doesn't seem to be working well.

> What CSS is needed to reproduce this issue?

I tested with SCSS and no particular SCSS is required.

> What stylelint configuration is needed to reproduce this issue?

I used this

```
{
  "extends": [
    "stylelint-config-prettier"
  ]
}
```

> Which version of stylelint are you using?

`"stylelint": "^8.2.0"`

> How are you running stylelint: CLI, PostCSS plugin, Node API?

via CLI, using the following command.

```
stylelintbug - master ❯ ./node_modules/.bin/stylelint "./**/*.scss"  --config .stylelintrc
```

> Does your issue relate to non-standard syntax (e.g. SCSS, nesting, etc.)?

Related to SCSS

> What did you expect to happen?

Should ignore from linting files inside `node_modules`

> What actually happened (e.g. what warnings or errors you are getting)?

```
stylelintbug - master ❯ ./node_modules/.bin/stylelint "./**/*.scss"  --config .stylelintrc                                                                                                         [system]

node_modules/bootstrap-sass/assets/stylesheets/bootstrap/_modals.scss
 36:49  ✖  Unexpected whitespace before ";"   at-rule-semicolon-space-before

node_modules/bootstrap-sass/assets/stylesheets/bootstrap/_theme.scss
 217:3  ✖  Unexpected whitespace before ";"   at-rule-semicolon-space-before

node_modules/bootstrap-sass/assets/stylesheets/bootstrap/mixins/_image.scss
 23:8   ✖  Expected single space after at-rule name "@media"   at-rule-name-space-after
 24:54  ✖  Expected single space after ","                     media-query-list-comma-space-after
 25:20  ✖  Unexpected whitespace after "("                     media-feature-parentheses-space-inside
 25:54  ✖  Expected single space after ","                     media-query-list-comma-space-after
 26:20  ✖  Unexpected whitespace after "("                     media-feature-parentheses-space-inside
 26:56  ✖  Expected single space after ","                     media-query-list-comma-space-after
 27:20  ✖  Unexpected whitespace after "("                     media-feature-parentheses-space-inside
 27:54  ✖  Expected single space after ","                     media-query-list-comma-space-after
 28:20  ✖  Unexpected whitespace after "("                     media-feature-parentheses-space-inside
 28:59  ✖  Expected single space after ","                     media-query-list-comma-space-after
 29:20  ✖  Unexpected whitespace after "("                     media-feature-parentheses-space-inside
```

**Comment by hudochenkov** [comment] 2017-11-05 09:52
Thank you for creating an example repository. Indeed, I can also reproduce this problem using the command above. Although, if I change a path to `"**/*.scss"` it works as expected.

```
./node_modules/.bin/stylelint "**/*.scss"
```

I'm not sure why the behavior is different if there `./` in the beginning.

@asumaran you don't need to specify `--config` because it will be picked up automatically based on file name.

**Comment by jeddy3** [comment] 2017-11-06 13:53
> I'm not sure why the behavior is different if there ./ in the beginning.

Good sleuthing. Do we want to dig deeper, or should we just document this caveat?

**Comment by jeddy3** [comment] 2017-12-07 19:50
Closing for now. We can always document this is it comes up again.

**Closed by jeddy3** 2017-12-07 19:50 UTC
Labels: status: needs investigation
