### ISSUE TITLE
Add unicode-bom rule

### ISSUE THREAD

**Issue by vkrol** [stylelint/stylelint#3792] opened 2018-11-09 07:57 UTC
> What is the problem you're trying to solve?

The developers on my team use BOM inconsistently. This clutters the diffs.

> What solution would you like to see?

A rule that requires that files always begin with the Unicode BOM character U+FEFF or that files must never begin with U+FEFF.

Inspired by https://eslint.org/docs/rules/unicode-bom

I tried to write such a rule myself, but I could not find any traces of BOM in the results of the parsing.

**Comment by ybiquitous** [comment] 2018-11-09 08:00
How about using [EditorConfig](https://editorconfig.org/)?

**Comment by vkrol** [comment] 2018-11-09 08:08
@ybiquitous EditorConfig does not provide any embedded linting functionality. We want to check the absence of BOM in pre-commit hooks for example. We already do this for JS files (thanks to the ESLint rule).

**Comment by ybiquitous** [comment] 2018-11-09 08:12
Then, how about [eclint](https://github.com/jedmao/eclint)?

I think checking BOM is out of the scope of stylelint... 🤔

**Comment by vkrol** [comment] 2018-11-09 08:17
Introducing the additional linting tool for this is the last resort for us :(
> I think checking BOM is out of the scope of stylelint... 🤔

Please, can you elaborate? I think the proposed rule is similar to [linebreaks](https://stylelint.io/user-guide/rules/linebreaks/) rule.

**Comment by vkrol** [comment] 2018-11-09 08:40
> I'm a bit worried about that BOM rule will conflict with EditorConfig, Prettier, or similar tools... 🤔

The ESLint rule does not conflict with EditorConfig, Prettier, etc., as far as I know. It is enabled by default in the Airbnb configuration even https://github.com/airbnb/javascript/blob/17e0454672f784772c5f5ab052523a93229d9adf/packages/eslint-config-airbnb-base/rules/style.js#L513.

**Comment by ybiquitous** [comment] 2018-11-09 08:43
It sounds like good! 😄

**Comment by vkrol** [comment] 2018-11-09 08:56
@ybiquitous do you have any idea how this rule can be implemented? Apparently, PostCSS cuts out BOM :(

**Comment by ybiquitous** [comment] 2018-11-09 09:01
Oh, I don't know how...

> Apparently, PostCSS cuts out BOM :(

Isn't this behavior a bug of PostCSS?

**Comment by vkrol** [comment] 2018-11-09 09:06
I think this is the intended behavior. But I will ask about this in Gitter.

**Comment by jeddy3** [comment] 2018-11-09 10:12
> do you have any idea how this rule can be implemented

[This](https://github.com/dichuvichkin/postcss-bom/blob/master/index.js#L9) makes me think you'll find the BOM in the `before` of the first node.

> But I will ask about this in Gitter.

Good idea, though.

**Comment by evilebottnawi** [comment] 2018-11-09 10:13
:+1: On this rule, analog eslint rule https://eslint.org/docs/rules/unicode-bom

**Comment by evilebottnawi** [comment] 2018-11-09 10:44
Postcss remove `BOM`by default before process and add again after if I'm not making a mistake
/cc @ai

**Comment by vkrol** [comment] 2018-11-09 11:30
@jeddy3 @evilebottnawi PostCSS intentionally strips BOM https://github.com/postcss/postcss/blob/37ddfa78c59efb6f66273f56684673da5bea906e/lib/input.es6#L36. /cc @ai

**Comment by vkrol** [comment] 2018-11-14 16:03
Waiting for https://github.com/postcss/postcss/pull/1203.

**Comment by vkrol** [comment] 2018-11-15 08:23
> @vkrol Feel free to contribute this rule. Once the BOM is tracked down, it'll hopefully be a pretty trivial (autofixable) rule to implement.

I will do it after https://github.com/postcss/postcss/pull/1203.

**Comment by DekiGk** [comment] 2019-03-04 16:06
> I will do it after [postcss/postcss#1203](https://github.com/postcss/postcss/pull/1203).

I think this one is fixed with [this version](https://github.com/postcss/postcss/releases/tag/7.0.6). Can we have it now in Stylelint? :)

**Comment by jeddy3** [comment] 2019-03-05 16:22
> Can we have it now in Stylelint? :)

Yes. I've removed the "blocked" label. The issue is label as "help wanted", i.e. PR welcome, and is waiting on someone to contribute it.

**Closed** 2019-09-04 13:43 UTC
Labels: good first issue, help wanted, type: new rule
