### ISSUE TITLE
`length-zero-no-unit`  autofix not working

### ISSUE THREAD

**Issue by webfrontzhifei** [stylelint/stylelint#6074] opened 2022-05-08 06:47 UTC
### What steps are needed to reproduce the bug?

.demo{
  position: absolute;
  right: .0rem;
  top: -.52rem;
}

### What Stylelint configuration is needed to reproduce the bug?

const config = {
  extends: ['stylelint-config-standard'],
  plugins: ['stylelint-scss'],
  rules: {}
};

module.exports = config;

### How did you run Stylelint?

stylelint --fix

### Which version of Stylelint are you using?

14.8.2

### What did you expect to happen?

.demo{
  position: absolute;
  right: 0;
  top: -.52rem;
}

### What actually happened?

.demo{
  position: absolute;
  right: ;
  top: -.52rem;
}

**Comment by ybiquitous** [comment] 2022-05-09 00:27
@webfrontzhifei Thanks for using the template. Your report seems related to the [length-zero-no-unit](https://stylelint.io/user-guide/rules/list/length-zero-no-unit) rule.

Unfortunately, I cannot reproduce the behavior reported. Could you provide a reproduction repository, please?

**Comment by webfrontzhifei** [comment] 2022-05-15 02:23
I'm so sorry, I do not descripe clear to reproduce the behavior。
the eslintrc.js config rule like this.

module.exports = {
  "extends": ["stylelint-config-standard"],
   rules: {
    'number-leading-zero': null
  }
};
 then if you run  npx stylelint "**/*.css" --fix ，you will reproduce the behavior descriped above

**Comment by ybiquitous** [comment] 2022-05-15 02:44
@webfrontzhifei Thanks. I've created the reproduction repo on Gist:

https://gist.github.com/ybiquitous/fd003e2a8f6d7533da4913d5a8479534

Autofix seems to work... 🤔

**Comment by webfrontzhifei** [comment] 2022-05-15 02:52
I have commented，".0rem" or ".0" will reproduce the behavior

**Comment by ybiquitous** [comment] 2022-05-15 06:28
@webfrontzhifei Thanks! I can reproduce the bug. 👍🏼

**Comment by ybiquitous** [comment] 2022-05-15 06:31
I've labeled the issue as ready to implement. Please consider [contributing](https://stylelint.io/contributing) if you have time.

There are [steps on how to fix a bug in a rule](https://stylelint.io/developer-guide/rules#fix-a-bug-in-a-rule) in the Developer guide.

The following code should be fixed:

https://github.com/stylelint/stylelint/blob/479c99d394d9cae270d66a73d0c77ea74a3076cc/lib/rules/length-zero-no-unit/index.js#L83-L88

**Closed** 2022-05-19 00:25 UTC
Labels: status: ready to implement, type: bug, good first issue
