### ISSUE TITLE
To print absolute paths with the string formatter

### ISSUE THREAD

**Issue by tingtien** [stylelint/stylelint#4297] opened 2019-09-24 06:56 UTC
> Clearly describe the bug

It don't print absolute path with string formatter in the terminal.

> Which rule, if any, is the bug related to?

stringFormatter.js
```
function logFrom(fromValue) {
  if (fromValue.charAt(0) === "<") return fromValue;

  return path
    .relative(process.cwd(), fromValue)
    .split(path.sep)
    .join("/");
}
```
to

```
function logFrom(fromValue) {
  if (fromValue.charAt(0) === "<") return fromValue;

  return fromValue.split(path.sep).join("/");
}
```

**Comment by hudochenkov** [comment] 2019-09-24 08:33
Duplicate of https://github.com/stylelint/stylelint/issues/4296

**Closed by hudochenkov** 2019-09-24 08:33 UTC
