### ISSUE TITLE
Consider @eslint/css

### ISSUE THREAD

**Issue by tudobeleza** [stylelint/stylelint#8205] opened 2024-12-16 17:48 UTC
I hope that your Stylelint team gets in touch with the ESLint team so that you two can combine your efforts.

The best of all worlds would be if you joined forces profoundly. If a plugin for ESLint were to be created by Stylelint, through which we at ESLint could use the Stylelint rules to analyze .css files and CSS-in-JS, that would be amazing. We would have a single config file, a single API. Related: https://github.com/eslint/css/issues/34 and https://eslint.org/blog/2024/10/eslint-json-markdown-support/

Or if these rules were to be migrated from Stylelint rules to @eslint/css.

I understand that this may be difficult, but it would be very good, to keep the community united around a single linter for CSS.

**Comment by Mouvedia** [comment] 2024-12-16 17:52
@jeddy3 should we merge #6593 with this issue?

**Comment by jeddy3** [comment] 2024-12-17 11:45
@tudobeleza Thanks for opening the issue. As @Mouvedia suggested, let's close this as a dupe of https://github.com/stylelint/stylelint/issues/6593. You're welcome to continue the discussion over there.

**Closed by jeddy3** 2024-12-17 11:45 UTC

**Comment by Mouvedia** [comment] 2025-01-20 20:10
related: mizdra/honey-css-modules#50 vs mizdra/honey-css-modules#52
