### ISSUE TITLE
Property pasted behind SCSS comment

### ISSUE THREAD

**Issue by Netail** [stylelint/stylelint#8015] opened 2024-10-03 10:11 UTC
### What minimal example or steps are needed to reproduce the bug?

When using a SCSS comment (`//`), it pastes the property behind the value

```
.test {
	// padding: 1rem;
}
```

becomes

```
.test {
	// padding: 1rem;padding
}
```

Sandbox example (but not sure if this includes SCSS support);

https://stylelint.io/demo/#N4Igxg9gJgpiBcIB0AXGBnFACYAdAdrigPTFYAOAhlFAJb4Dm8WAjAE4wC2A3AUQGYAbGAA8AtAzYQA7sxa98WLBABuMNkJnMAFrRox8CgL4gANCH61hAOUqc4iUXfLCk6MOnRnwEfJYYIIHiKWLggomj4UOhhzADaBEpKYZgAnsKC9ChikH60DGKYlFGUbFBhiVgAugQm5rn+AGIQbJyUKIEAVui+3rDkXojBySBpGVmxoSCC7RgoYaaVKSjpMJn42Q35hSjFUKXlCFMzaJgV+CZGQA

### What minimal configuration is needed to reproduce the bug?

```json
{
  "extends": [
    "stylelint-config-standard-scss",
    "stylelint-config-prettier-scss"
  ],
  "plugins": [
    "stylelint-order"
  ],
}
```

### How did you run Stylelint?

VSCode

### Which Stylelint-related dependencies are you using?

```json
{
  "stylelint": "latest",
  "stylelint-config-prettier-scss": "^1.0.0",
  "stylelint-config-standard-scss": "^13.1.0",
  "stylelint-order": "^6.0.4"
}
```

### What did you expect to happen?

Format correctly without property pasted behind the value

### What actually happened?

Formatting pasted the property behind the value

**Comment by Mouvedia** [comment] 2024-10-03 14:16
see https://github.com/stylelint/stylelint/issues/7494#issuecomment-1907759441

**Comment by ybiquitous** [comment] 2024-10-04 14:30
@Netail Thanks for the report. Unfortunately, this is a known issue, which is caused by the combination of the `--fix` option (to be accurate, `postcss-safe-parser`) and the `no-invalid-double-slash-comments` rule.

See also the demo mentioned on <https://github.com/stylelint/stylelint/issues/7494#issuecomment-1908002481>.

This issue will be resolved by #7497. So, I'm closing this.

**Closed by ybiquitous** 2024-10-04 14:30 UTC
