### ISSUE TITLE
vue3-stylelint15-vscode=Unknown word (CssSyntaxError)

### ISSUE THREAD

**Issue by songxianling** [stylelint/stylelint#6832] opened 2023-05-06 02:55 UTC
### What steps are needed to reproduce the bug?

clone `https://github.com/songxianling/vue3-stylelint15`
// node 16.19.1
1. npm i  or cnpm i
2. find `src/pages/indexPage`
3. Add a new style to the style style; Then save

### What Stylelint configuration is needed to reproduce the bug?

```js
module.exports = {
  root: true,
  plugins: ['stylelint-prettier'],
  extends: ['stylelint-config-standard-scss', 'stylelint-config-rational-order', 'stylelint-config-recommended-vue'],
  // https://stylelint.docschina.org/user-guide/rules/
  customSyntax: 'postcss-html',
  overrides: [
    {
      files: ['**/*.vue'],
      customSyntax: 'postcss-html'
    }
  ],
  rules: {
    indentation: 2,
    'selector-pseudo-element-no-unknown': [
      true,
      {
        ignorePseudoElements: ['v-deep']
      }
    ],
    'number-leading-zero': 'never',
    'no-descending-specificity': null,
    'font-family-no-missing-generic-family-keyword': null,
    'selector-type-no-unknown': null,
    'at-rule-no-unknown': null,
    'no-duplicate-selectors': null,
    'no-empty-source': null,
    'selector-pseudo-class-no-unknown': [true, { ignorePseudoClasses: ['global'] }]
  }
}

```

### How did you run Stylelint?

Write CSS styles directly in `<style lang="scss" >` in a`. vue` file in the src directory of the `vscode` editor; An error message occurred while saving automatic formatting

### Which version of Stylelint or dependencies are you using?

```
// package.json
"stylelint": "^15.6.1",
  "stylelint-config-rational-order": "^0.1.2",
  "stylelint-config-recommended-vue": "^1.4.0",
  "stylelint-config-standard-scss": "^9.0.0",
  "stylelint-prettier": "^3.0.0",
```

### What did you expect to happen?

normal operation

### What actually happened?

<img width="622" alt="image" src="https://user-images.githubusercontent.com/16551088/236594669-681fcf32-f965-41b8-9264-b5c702c56729.png">
<img width="702" alt="image" src="https://user-images.githubusercontent.com/16551088/236594703-cfc844bf-bf3f-4114-86aa-78de9ee56955.png">

**Comment by yoyo837** [comment] 2023-05-06 13:48
I can't reproduce it.

**Comment by songxianling** [comment] 2023-05-08 01:59
Found the problem; Disable this plugin so that no errors will occur
<img width="654" alt="image" src="https://user-images.githubusercontent.com/16551088/236717417-4070f40b-f0e6-41fe-8a8e-dbca4ffd2e5e.png">

**Comment by yoyo837** [comment] 2023-05-08 02:02
Ok, it is recommended to keep only the official stylelint vscode plugin to lint style, let's close this.

**Closed by yoyo837** 2023-05-08 02:02 UTC
Labels: status: needs reproducible example

**Comment by zerobin** [comment] 2023-12-15 04:06
Same problem occurs, regardless of whether I am customizing it:
overrides: [
    {
      files: ['**/*.vue'],
      customSyntax: postcss-html
    }
  ],.
Or use: stylelint-config-recommended-vue, or: stylelint-config-html
Always report: Unknown word (CssSyntaxError)Stylelint(CssSyntaxError) in .vue files,

vue version: 3.3.4
vite: ^4.0.3
vscode version: 1.85.0
stylelint (official) plugin version: 1.3.0

vscode settings.json I set up: 
{
"editor.formatOnSave": true,
  "editor.codeActionsOnSave": {
    "source.fixAll.eslint": true,
    "source.fixAll.stylelint": true
  },
"css.validate": false,
  "less.validate": false
  "scss.validate": false }
"stylelint.validate": ["css", "less", "postcss", "sass", "scss", "vue"],
}

**Comment by zerobin** [comment] 2023-12-15 04:48
I ended up removing all the custom configurations and found that it was the official version of the stylelint plugin for vscode that was turned on:
"stylelint.validate": ["css", "less", "postcss", "sass", "scss", "vue"], the vue version would have this problem
The stylelint version is the same no matter which
