### ISSUE TITLE
Add ability for --fix to output results to STDOUT

### ISSUE THREAD

**Issue by chaucerbao** [stylelint/stylelint#2840] opened 2017-08-31 08:11 UTC
Just wanted to see what you thought about adding an option for `--fix` to output the results to STDOUT.  It would allow integration into an IDE.

**Comment by ntwb** [comment] 2017-09-01 02:06
Sounds like a great idea, looping @Arcanemagus in as the maintainer of [AtomLinter/linter-stylelint/](https://github.com/AtomLinter/linter-stylelint/) I'm sure he's thought about supporting fixable rules in Atom 😄

**Comment by jeddy3** [comment] 2017-09-02 16:28
Is this a dupe of https://github.com/stylelint/stylelint/issues/2710?

**Closed** 2017-09-09 23:04 UTC
Labels: status: discussion

**Comment by jeddy3** [comment] 2017-09-09 23:07
Closing for now as I think its a dupe. @chaucerbao autofix is a new feature that needs contribution to improve. Please consider helping out with https://github.com/stylelint/stylelint/issues/2710 and bringing autofix to non-files.
