### ISSUE TITLE
Atom linter-stylelint editor plugin

### ISSUE THREAD

**Issue by ismay** [stylelint/stylelint#290] opened 2015-07-16 13:08 UTC
It might be early days, but are there plans for an atom-linter? I'd be happy to field test it, and it'd probably be a relatively straight forward process because of atoms compatibility with node.

**Comment by davidtheclark** [comment] 2015-07-16 13:10
I think this probably needs to wait on #133.

**Comment by MoOx** [comment] 2015-07-16 13:10
I will be happy to work on that.

**Comment by ismay** [comment] 2015-07-16 13:13
Ah, right. Also, [linter-stylint](https://atom.io/packages/linter-stylint) (for stylus) is a little close to `linter-stylelint`. But that might not be that bad.

**Comment by ismay** [comment] 2015-07-16 13:23
It might be difficult to incorporate linting for css that hasn't been preprocessed though. I'm using several postcss plugins, which might be easily incorporated, but what about other preprocessors like rework, etc?

**Comment by MoOx** [comment] 2015-07-16 13:26
Since stylelint use postcss it can parse a lot of "invalid" css. So should not be a big deal. See #266

**Comment by 1000ch** [comment] 2015-07-25 05:58
@MoOx @ismay 
I [crafted](https://github.com/1000ch/linter-stylelint).

**Comment by ismay** [comment] 2015-07-25 07:28
Awesome! I'll have time to test it on monday.

**Comment by jeddy3** [comment] 2015-07-25 11:01
@1000ch Looks great! :)

> Don't know whether there is a consensus on a stylelintrc yet.

I think @MoOx is looking into this in #288

**Comment by MoOx** [comment] 2015-07-25 11:53
Exactly. I will work on that this week.

**Comment by davidtheclark** [comment] 2015-09-13 16:36
@ismay : Any input you might have over at https://github.com/stylelint/stylelint/pull/380 would be much appreciated.

**Comment by ntwb** [comment] 2015-09-14 04:58
@davidtheclark, it was @1000ch who wrote the Atom plugin :wink: 

@1000ch : Any input you might have over at #380 would be much appreciated.

**Comment by 1000ch** [comment] 2015-09-14 05:12
@davidtheclark @ntwb 
I confirmed conversations in #380 and totally understand. Sounds good :+1:

**Comment by davidtheclark** [comment] 2015-09-27 00:07
@1000ch Can you verify that the `js-api` branch will work for your plugin? It introduces the `.stylelintc` file (in JSON format), the CLI, the JS API, and extends. I think that ensuring that it works with editor plugins is vital.

**Comment by 1000ch** [comment] 2015-10-01 09:57
@davidtheclark Sorry for delay, I'll try it in a few days.

**Comment by 1000ch** [comment] 2015-10-01 10:53
@davidtheclark `js-api` branch worked without code changing :+1:

**Comment by davidtheclark** [comment] 2015-10-01 14:00
Awesome; thanks @1000ch !

**Comment by MadLittleMods** [comment] 2015-10-15 15:42
For those wanting to use `.stylelintrc` with `stylelint` before the `1.3.0` release, you can install with: `npm i stylelint/stylelint --ignore-scripts --save-dev && cd ./node_modules/stylelint && npm run prepublish && cd ../../`

**Comment by davidtheclark** [comment] 2015-10-17 01:21
@1000ch : Now that we have the CLI/API out (in 2.0.0) with `.stylelintrc` support, should we close this issue?

**Comment by 1000ch** [comment] 2015-10-17 14:47
@davidtheclark Yes! Atom plugin uses stylelint `v2.0.0` now.

**Comment by davidtheclark** [comment] 2015-10-17 15:07
Great!

**Closed by davidtheclark** 2015-10-17 15:07 UTC
Labels: status: blocked, type: ecosystem
