### ISSUE TITLE
Cannot add "fr" to unit whitelist

### ISSUE THREAD

**Issue by smlombardi** [stylelint/stylelint#2441] opened 2017-03-24 19:02 UTC
This is a new, valid unit for css grids.  It's flagged as an error and cannot be added to "unit-whitelist" without THAT generating a validation error on the JSON

![screen shot 2017-03-24 at 2 59 17 pm](https://cloud.githubusercontent.com/assets/835148/24309562/b1f54ce8-10a2-11e7-9c2c-3d6214155763.png)

![screen shot 2017-03-24 at 3 01 24 pm](https://cloud.githubusercontent.com/assets/835148/24309587/cabfda36-10a2-11e7-9e65-fa1bd33a35ee.png)

This is using VSCode insiders 1.11.0

**Comment by evilebottnawi** [comment] 2017-03-24 19:09
@smlombardi can you use issue tempalte?

**Comment by jeddy3** [comment] 2017-03-25 00:12
@smlombardi Thanks for the report.

I'm not able to reproduce this. `fr` support was added to `unit-no-unknown` in `7.8.0`, and I'm able to added, without issue, `fr` to the `unit-whitelist` array in my own `.stylelintrc` using VSCode.

> without THAT generating a validation error on the JSON

Do you know what's validating _the CSS units_ in the JSON in your second screenshot? I don't believe there's anything _within stylelint_ that would be doing that. Is it a feature of VSCode I'm not aware of?

**Comment by jeddy3** [comment] 2017-03-26 09:42
Oh, wow, this is fascinating... after a bit more digging it looks like `vscode-stylelint` [has support for](https://github.com/shinnn/vscode-stylelint/pull/33) validating stylelint configuration objects using something called [Schema Store](http://schemastore.org/json/). The stylelint schema is [here](http://json.schemastore.org/stylelintrc).

The problem appears to be that there is an [overly specific](https://github.com/SchemaStore/schemastore/blob/master/src/schemas/json/stylelintrc.json#L654-L769) `unitRule` definition. The definition assumes that only a specific set of (spec-based) units can be added to this rule, but that isn't the case. All the `whitelist` and `blacklist` rules can accept arbitrary strings to account for custom language extensions e.g. `@my-custom-at-rule`, `my-custom-property:`, `10my-custom-unit`, etc...

@smlombardi I would recommend you make a PR to [the Schema Store repo](https://github.com/SchemaStore/schemastore/blob/master/src/schemas/json/stylelintrc.json) to fix the issue. I suspect doing away with the [`unitRule` definition](https://github.com/SchemaStore/schemastore/blob/master/src/schemas/json/stylelintrc.json#L643-L794), and updating [`unit-blacklist`](https://github.com/SchemaStore/schemastore/blob/master/src/schemas/json/stylelintrc.json#L3597-L3600) and [`unit-whitelist`](https://github.com/SchemaStore/schemastore/blob/master/src/schemas/json/stylelintrc.json#L3659-L3661) to use `"$ref": "#/definitions/simpleArrayStringRule"` (rather than `"$ref": "#/definitions/unitRule"`) should do it. I don't have time to look more deeply into it though, or test this hypothesis.

As this isn't related to stylelint core, I'm going to close this issue.

**Closed by jeddy3** 2017-03-26 09:42 UTC
Labels: status: needs investigation
