### ISSUE TITLE
Ability to detect the use of "undefined custom properties (variables)" across all css files

### ISSUE THREAD

**Issue by vedmack** [stylelint/stylelint#6828] opened 2023-05-01 14:12 UTC
### What is the problem you're trying to solve?

Trying not to get error about using custom properties (variables) which are defined inside other CSS files, right now it look for the custom properties (variables) only inside the same CSS file

### What solution would you like to see?

Ability to rely on the `Unexpected vendor-prefix "-webkit-flex-direction" (property-no-vendor-prefix)` knowing that stylelint looks for the definition of the custom properties across all CSS file in the project

**Comment by ybiquitous** [comment] 2023-05-02 13:59
@vedmack Thanks for the report using the template. This issue seems to be a duplicate of #6746, right?

**Comment by vedmack** [comment] 2023-05-02 16:12
@ybiquitous you are right, a duplicate indeed :|, a solution that allows using all css files across the project or at least allows to define several source folders would be super useful.

**Comment by ybiquitous** [comment] 2023-05-03 01:23
I think so, too. Let's continue the discussion on #6746 or #4088.

Duplicate of #6746

**Closed** 2023-06-13 15:53 UTC
