### ISSUE TITLE
Add ignore: ["custom-elements"] to `selector-type-no-unknown` rule

### ISSUE THREAD

**Issue by evilebottnawi** [stylelint/stylelint#2437] opened 2017-03-21 12:55 UTC
> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

Ref: https://github.com/stylelint/stylelint/pull/2366#issuecomment-280635741

> Which rule, if any, is this issue related to?

e.g. `selector-type-no-unknown`

> What CSS is needed to reproduce this issue?

No matter

> What stylelint configuration is needed to reproduce this issue?

No matter

> Which version of stylelint are you using?

No matter

> How are you running stylelint: CLI, PostCSS plugin, Node API?

No matter

> Does your issue relate to non-standard syntax (e.g. SCSS, nesting, etc.)?

No matter

> What did you expect to happen?

No matter

> What actually happened (e.g. what warnings or errors you are getting)?

No matter

**Comment by jeddy3** [comment] 2017-04-01 13:54
Now dupe of https://github.com/stylelint/stylelint/issues/2348

**Closed by jeddy3** 2017-04-01 13:54 UTC
Labels: beginner-friendly, status: help wanted, type: option
