### ISSUE TITLE
Fix autofix for variable name matching property name

### ISSUE THREAD

**Issue by guoyunhe** [stylelint/stylelint#4662] opened 2020-03-26 12:22 UTC
> Clearly describe the bug

In React JSX/TSX files, the stylelint plugin try to auto fix variable casing in the `style` property. But this will cause the code not working.

> What code is needed to reproduce this issue?

e.g.

```jsx
// Container.jsx
import React from 'react';

export default function Container({maxWidth, children}) {
  return <div style={{ maxWidth: maxWidth + 10 }}>{children}</div>
}
```

> What vscode-stylelint configuration is needed to reproduce the bug?

```json
"editor.codeActionsOnSave": {
  "source.fixAll.stylelint": true
}
```

> Is this issue related to autofix? (`editor.codeActionsOnSave`)

Yes

> Which version of vscode-stylelint are you using?

`0.84.0`

> Which version of stylelint are you using?

`13.2.0`

> Does your issue relate to non-standard syntax (e.g. SCSS, nesting, etc.)?

It is related to JSX

> What did you expect to happen?

The code is valid and should not be touched.

> What actually happened (e.g. what warnings or errors you are getting)?

The code is changed, `maxWidth` --> `maxwidth`, and thus not working anymore.

**Comment by jeddy3** [comment] 2020-03-26 15:00
@guoyunhe Thanks for the report and for using the template.

I've transferred your issue because the problem is in stylelint itself, rather than the VS Code extension.

The underlying problem is likely with [the parser stylelint uses to support CSS-in-JS](https://github.com/stylelint/postcss-css-in-js). I've added this issue to https://github.com/stylelint/stylelint/issues/4574, which is a growing list of the problems with the syntax that we need help to fix.

Please consider [contributing to the parser](https://stylelint.io/developer-guide/syntaxes#working-on-syntaxes) if you have time.

**Comment by rbong** [comment] 2021-06-05 14:07
The parser is not the issue. The parser interprets the expression appropriately and does not turn it into lowercase when stringifying the parsed expression. The issue is with the `value-keyword-case` rule, which transforms parts of expressions even if they are not string literals.

**Comment by rbong** [comment] 2021-06-05 15:58
This appears to come down to the exact same issue described here: https://github.com/stylelint/stylelint/issues/5185#issuecomment-792913660

This is probably a duplicate of that issue, I don't believe it's related to the "variable name matching property name" as indicated in the title. Using another property name results in the same issue:

```javascript
return <div style={{ minWidth: maxWidth + 10 }}>{children}</div>
```

**Comment by jeddy3** [comment] 2022-01-18 15:20
Closing as the [`syntax` option was removed](https://github.com/stylelint/stylelint/issues/5289) for the [14.0.0 release](https://github.com/stylelint/stylelint/issues/5205). (See the [migration guide](https://github.com/stylelint/stylelint/blob/main/docs/migration-guide/to-14.md#syntax-option-and-automatic-inferral-of-syntax).)

We'll also [be deprecating](https://github.com/stylelint/postcss-css-in-js/issues/225) our [forked CSS-in-JS package](https://github.com/stylelint/postcss-css-in-js), in favour of leaner custom syntaxes.

Please consider [writing a custom syntax](https://github.com/stylelint/stylelint/blob/main/docs/developer-guide/syntaxes.md) specific to the CSS-in-JS library in this issue and fixing the bug there.

**Closed by jeddy3** 2022-01-18 15:20 UTC
Labels: status: ready to implement, type: bug, syntax: css-in-js
