### ISSUE TITLE
Fix "afterEnd" error while linting .vue files

### ISSUE THREAD

**Issue by Jovi** [stylelint/stylelint#3440] opened 2018-07-04 03:49 UTC
> Problem

There is a bug when I'm using stylelint with .vue files

> .vue file

```vue
<template>
    <div>aaa</div>
</template>

<script>
export default {
    
}
</script>

<style lang="scss" scoped>
.color {
    color:red;

    .aaa {
        font-size: 12px;
    }
}
</style>

```

> stylelint config

```json
{
    "extends": "stylelint-config-standard",
    "rules": {
        "indentation": 4
    }
}
```

> version

`9.3.0`

> CLI command

`stylelint --config PATH_TO/.stylelintrc PATH_TO/test.vue`

> Error

```
TypeError: Cannot set property 'afterEnd' of undefined
    at parseStyle (.../node_modules/postcss-syntax/parse-style.js:117:25)
    at processor (.../node_modules/postcss-syntax/processor.js:24:9)
    at Object.parse (.../node_modules/postcss-syntax/parse.js:19:9)
    at new LazyResult (.../node_modules/stylelint/node_modules/postcss/lib/lazy-result.js:70:24)
    at Processor.process (.../node_modules/stylelint/node_modules/postcss/lib/processor.js:117:12)
    at getCode.then.code (.../node_modules/stylelint/lib/getPostcssResult.js:106:31)
    at <anonymous>
```

**Comment by jeddy3** [comment] 2018-07-09 13:51
@Jovi Thanks for the report and for using the template.

@gucong3000 Is this an issue upstream in either `postcss-html` or `postcss-syntax`?

**Comment by gucong3000** [comment] 2018-07-16 02:29
@Jovi 
I can't reproduce the problem locally based on the information you provide.
```bash
E:\work\stylelint-test  (stylelint-test@1.0.0)
$ cat package.json
{
  "name": "stylelint-test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "stylelint test.vue --fix"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {},
  "devDependencies": {
    "stylelint": "^9.3.0",
    "stylelint-config-standard": "^18.2.0"
  }
}

E:\work\stylelint-test  (stylelint-test@1.0.0)
$ cat .stylelintrc
{
    "extends": "stylelint-config-standard",
    "rules": {
        "indentation": 4
    }
}
E:\work\stylelint-test  (stylelint-test@1.0.0)
$ cat test.vue
<template>
    <div>aaa</div>
</template>

<script>
export default {

}
</script>

<style lang="scss" scoped>
.color {
    color: red;

    .aaa {
        font-size: 12px;
    }
}
</style>

E:\work\stylelint-test  (stylelint-test@1.0.0)
$ stylelint test.vue
E:\work\stylelint-test  (stylelint-test@1.0.0)
$
```

Please try delete `node_modules`, `package-lock.json`, `yarn.lock`

**Comment by jeddy3** [comment] 2018-07-21 10:19
> I can't reproduce the problem locally

Closing for now.

@Jovi Feel free to reopen if you are able to create a reproducible test repo.

**Closed by jeddy3** 2018-07-21 10:19 UTC
Labels: status: needs clarification, syntax: html
