### ISSUE TITLE
stylelint-disable not working. Errors still showing in reports.

### ISSUE THREAD

**Issue by TidyLuke** [stylelint/stylelint#4430] opened 2019-11-22 14:58 UTC
> Clearly describe the bug

I've placed `/* stylelint-disable */` and `/* stylelint-enable */` around a block of styles, the errors however are still showing in my reports. This is the same if I try to ignore a single line or a block of styles.

> Which rule, if any, is the bug related to?

The rule I'm trying to disable is `declaration-no-important` but it's not working when making generic disable calls either.

> What CSS is needed to reproduce the bug?

```css
// The block that I'm trying to ignore
@media (prefers-reduced-motion: reduce) {
	*, *:before, *:after {
		animation-duration: .001s !important;
		transition-duration: .001s !important;
	}
}

// What I've tried
@media (prefers-reduced-motion: reduce) {
	*, *:before, *:after {
		/* stylelint-disable declaration-no-important */
		animation-duration: .001s !important;
		transition-duration: .001s !important;
		/* stylelint-enable */
	}
}

@media (prefers-reduced-motion: reduce) {
	*, *:before, *:after {
		/* stylelint-disable */
		animation-duration: .001s !important;
		transition-duration: .001s !important;
		/* stylelint-enable */
	}
}

@media (prefers-reduced-motion: reduce) {
	*, *:before, *:after {
		animation-duration: .001s !important; /* stylelint-disable-line */
		transition-duration: .001s !important; /* stylelint-disable-line */
	}
}
```

> What stylelint configuration is needed to reproduce the bug?

```json
{
  "rules": {
      "declaration-no-important": true
  }
}
```

> Which version of stylelint are you using?

`12.0.0`

> How are you running stylelint: CLI, PostCSS plugin, Node.js API?

gulp-stylelint

Options for gulp-stylelint:

```javasrcipt
styleLint({
	failAfterError: task.isDist,
	reporters: [{ formatter: 'verbose', console: true }],
	debug: true,
	fix: true,
})
```

> Does the bug relate to non-standard syntax (e.g. SCSS, Less etc.)?

SCSS

> What did you expect to happen?

No warnings to be flagged

> What actually happened (e.g. what warnings or errors did you get)?

The following warnings were flagged:

```shell
/assets/scss/base/general.scss
 72:31  ✖  Unexpected !important   declaration-no-important
 73:32  ✖  Unexpected !important   declaration-no-important

1 source checked
/assets/scss/base/general.scss

2 problems found
 severity level "error": 2
  declaration-no-important: 2
```

**Comment by fanich37** [comment] 2019-11-22 15:43
Thank you for opening the issue!
According to demo it works as expected so it might be `gulp-stylelint` issue.

https://stylelint.io/demo#N4Igxg9gJgpiBcIACBbGUCWBDABACgAcAnGAMxiIGcBaEqAVzHWpQgBcMIA7eHOxmAEocwADpdRbAFQAaHFPgAjMhBJyFWUmwojxkyVi4YUWDt2oMipzjxwA6AAwOAjJRwBCYwVVtDbANx6bJJsVlyUGGZcFvRWUbyOLm6eKN5EvlwBQQC+4rkSXKjo2PjEZBQ0-ExQLOw2vFVCuhLS6koqavLwmtpEzfpsAPRSOJRsAJ4ANjCTGJkWGJRYitM4sGCTWHE21FwQ1F4+fvKDQQZGJlEx29wJTq4eh+l+gS0hYRFXlta39vfJTwyWTeQxGYymMzmbGoMC4y1WUlOLXy+XERUwuEIJHIVFo6AENVY8T4+KYwjELVkXWUpFUMDaPR0FIGw1GE2ms3mmCWKxgJzOGWMP2i32JiQeKTSQNeA1Chk+O1F9T+SUeqSOmRlwVBbIhnOhsPhfMROTyekKaAxpWxFTxDGqtWJjXJQSpChpdIZWiZAsMQq+sWFd1Vko1ARwrPBHKhCx502onONSNlH0iisDYv+aqlLwjYPZkK5iyNCbmSdNXGyIBkIEo40yWAAHgha2BKJRq+BuKQMABzFsUnA4UQgIj0aaUEe8QdD4cgdabG7RPYHdXPTJTnChegwcRDlEgbJAA

**Comment by hudochenkov** [comment] 2019-11-24 08:08
Maybe it's related to `fix: true`.

Please, provide repository with reproducible problem.

**Comment by karfau** [comment] 2019-12-11 22:06
I have the same issue, no disable comment works. on my side it's SCSS and we are using postcss.
I tried to upgrade from version 10.1.0 to 12.0 and read about the new CLI flag `--report-needless-disables` so tried it immediately. 

Removing the option makes comment disables work again.

Hope it helps.

**Comment by jeddy3** [comment] 2020-01-11 20:35
Closing for now. Feel free to reopen with a reproducible example.

**Closed by jeddy3** 2020-01-11 20:35 UTC
Labels: status: needs reproducible example

**Comment by karfau** [comment] 2020-01-12 06:06
I already gave all the information required in my last comment:

```
$ ./node_modules/.bin/stylelint --config .stylelintrc test.scss 

test.scss
 3:32  ✖  Unexpected !important   declaration-no-important
 4:33  ✖  Unexpected !important   declaration-no-important

$ ./node_modules/.bin/stylelint --config .stylelintrc --rd test.scss 

test.scss
  3:32  ✖  Unexpected !important   declaration-no-important
  4:33  ✖  Unexpected !important   declaration-no-important
 11:32  ✖  Unexpected !important   declaration-no-important
 12:33  ✖  Unexpected !important   declaration-no-important
 20:32  ✖  Unexpected !important   declaration-no-important
 21:33  ✖  Unexpected !important   declaration-no-important
 28:32  ✖  Unexpected !important   declaration-no-important
 29:33  ✖  Unexpected !important   declaration-no-important
```

With the values you provided in the demo link, when using the new flag `--rd` all the disable comments stop having an impact.

I can also put that into a gist or github repo if you want, but I think it shouldn't be required.

**Comment by jeddy3** [comment] 2020-01-12 10:42
@karfau Sorry, I should've been clearer. I closed it as the bug described in the [original post](https://github.com/stylelint/stylelint/issues/4430#issue-527245269) wasn't reproducible.  Your specific bug is a duplicate of https://github.com/stylelint/stylelint/issues/4203 and is being tracked there. Thanks for your additional clear description of the problem, though.
