### ISSUE TITLE
Make official linters for major editors

### ISSUE THREAD

**Issue by corysimmons** [stylelint/stylelint#719] opened 2016-02-11 05:14 UTC
@davidtheclark @jeddy3 [This](https://github.com/kungfusheep/SublimeLinter-contrib-stylelint/issues/13), and my [barrage of issues with Atom's linter](https://github.com/AtomLinter/linter-stylelint/issues?utf8=%E2%9C%93&q=is%3Aissue+author%3Acorysimmons+), are prime examples of why stylelint org should maintain official linters for the major editors.

stylelint is a program designed to lint but it doesn't have a single functioning linter for any editor.

Linting via the command line is super cool as a pre-commit hook, but linting requires functional plugins to actually be usable (unless you expect people to run a lint task after every keystroke?).

If you're not interested in doing this, please put a disclaimer on your website and the top of your [README](https://github.com/stylelint/stylelint/pull/720) that stylelint doesn't have any functional linting plugins so people like me don't spend days fighting with it before they realize it's unusable.

I wrote about this prevalent problem in GitHub tooling in this [in-depth article](https://medium.com/@corysimmons/stop-marketing-your-unfinished-product-2851e15e7427).

This is the part where you scold me and tell me I can build these tools if I need them. stylelint isn't my project and I'm not good at JS dev yet.

I don't care if something is unfinished but you're in the wrong for not warning people.

For anyone saying they've actually used a custom stylelint config in production and all these problems are just specific to me: you're a liar. You cannot use a custom config.js with Sublime's linter. Atom's Linter throws bugs every other keystroke.

Anyway, moving onto [other tools](https://github.com/csscomb) that see the value maintain official/functional linters. They might be less strict, but at least I can somewhat use them.

**Comment by MoOx** [comment] 2016-02-11 05:55
[Like I said](https://github.com/stylelint/stylelint-config-standard/issues/6#issuecomment-182727079), your "request" is very clumsy. Your tone is really not friendly. That's not how OSS works.

**Comment by corysimmons** [comment] 2016-02-11 06:14
Sorry I'm a stinking jerkface :poop: head.

But so far as things we can measure: this project wasted a lot of my time.

I've opened [a PR](https://github.com/stylelint/stylelint/pull/720) that fixes the problem.

**Comment by MoOx** [comment] 2016-02-11 06:17
I hope you will learn for your mistake (yeah, you wasted your own time) 🙃.

Next time you are considering a tool, before implementing a ton of stuff, looks for what is important to you before using it.

**Comment by corysimmons** [comment] 2016-02-11 06:21
I typically do.

I think the problem this time was that I expected something called style**lint** to actually be able to *lint stuff* in a practical manner.

My bad! 😂

**Comment by corysimmons** [comment] 2016-02-11 06:59
lol csscomb sucks too. I'll revisit the whole Standard CSS thing in a few years when technology has progressed to the point of us landing human beings on Mars and basic CSS linting is possible.

**Comment by MoOx** [comment] 2016-02-11 07:01
I told you that there is no "ultimate" tool for this today. See you in some years then.

**Comment by corysimmons** [comment] 2016-02-11 07:03
To your guys credit, stylelint has the potential. :clap:

**Comment by simonsmith** [comment] 2016-02-11 07:15
Works fine in Vim.

**Comment by simonsmith** [comment] 2016-02-11 08:42
@corysimmons What part of this doesn't work in Atom?

![](https://s3.amazonaws.com/f.cl.ly/items/2v2s1z0C0l0l0D3x2P3q/Screen%20Recording%202016-02-11%20at%2008.41%20am.gif?v=6376840a)

**Comment by corysimmons** [comment] 2016-02-11 08:50
Add a large/custom [ruleset](https://raw.githubusercontent.com/standard-css/standard-css/1c88903384773bf569d66258af0eb020f0295db7/stylelint.config.js) and actually use it on a project. Enjoy the millions of [bugs](https://github.com/AtomLinter/linter-stylelint/issues?utf8=%E2%9C%93&q=is%3Aissue+author%3Acorysimmons).

This one was my favorite though. I opened foundation.scss and it bugged. :)
![image](https://cloud.githubusercontent.com/assets/224636/12972324/3c41f13e-d072-11e5-9633-7fdad29df0c9.png)

It's just thing after thing. Bug after bug after bug. It's clear to me that everyone using stylelint just uses lax settings and not in real world situations (small/medium sized sass files...).

**Comment by corysimmons** [comment] 2016-02-11 08:54
Not functional in VSCode as well: https://github.com/shinnn/vscode-stylelint/issues/2

![image](https://cloud.githubusercontent.com/assets/224636/12972425/244897a8-d073-11e5-9d24-60e73cf3dd5a.png)

**Comment by simonsmith** [comment] 2016-02-11 08:58
> It's clear to me that everyone using stylelint just uses lax settings and not in real world situations (small/medium sized sass files...)

Why would you make this assumption? I'm using the [suitcss config](https://github.com/suitcss/stylelint-config-suitcss/blob/master/index.js) which is quite comprehensive and is used in real world situations.

Just because your reams of incoherent Sass don't compile properly, doesn't mean you should write off Stylelint as some useless project.

Instead, collect your bug reports with reproducible steps and open issues [like an adult](https://github.com/stylelint/stylelint/issues/585) and I'm sure you'll find the stylelint team very helpful in getting things fixed.

**Comment by corysimmons** [comment] 2016-02-11 09:30
> reams of incoherent Sass

Like [foundation.scss](https://github.com/zurb/foundation-sites/blob/develop/scss/foundation.scss) (my version doesn't even have the mixin in it)? Totally incoherent.

> Instead, collect your bug reports with reproducible steps and open issues like an adult

Nah that's okay. Did that for a week or so. Kinda burnt out on trying to drag this project across the finish line. I'd rather just be a baby.

>  the stylelint team very helpful

Never said they weren't. I just said they should put a disclaimer on the project that says something to the effect of "This doesn't have any functional editor linters" -- would've saved me a lot of time and headaches.

---

In fact, I've wasted enough time even thinking about this project. I'll check in every few weeks/months to see if any linters work.

Ignoring til then. :D :baby: :baby_bottle:

**Comment by MoOx** [comment] 2016-02-11 09:52
It's not like if the website and readme clearly show "Example output" with a terminal picture.

Oh and also

> Decide whether to use the CLI, Node API, or PostCSS plugin.

See ya later babycory.

**Comment by benfrain** [comment] 2016-02-11 10:44
@corysimmons the Sublime plugin works fine :) We have been using it with loads of devs on Windows/Mac.

Whilst you are frustrated you should consider your context. You are struggling to get the thing working. I understand that incredibly annoying but that that is not the same as 'the thing doesn't work'.

**Comment by shinnn** [comment] 2016-02-11 11:37
The problem referred in https://github.com/stylelint/stylelint/issues/719#issuecomment-182771724 has was fixed in vscode-stylelint v0.3.0.

**Comment by simonsmith** [comment] 2016-02-11 11:39
@shinnn :+1:

**Comment by davidtheclark** [comment] 2016-02-11 12:52
@corysimmons: The problem you've been hitting with inaccurate positions for errors is specific to the SCSS parser and issues are being worked on in PostCSS to remedy this (https://github.com/postcss/postcss/issues/725). 

In case it's not apparent there's not a grand organization at work here. Pretending to have "official" linters wouldn't mean anything except probably that I personally would be obliged to write more code and maintain more things. I'm happy to have others step in and run those projects. Thanks to everyone who has been working on text editor linters!

**Closed by davidtheclark** 2016-02-11 12:52 UTC
