### ISSUE TITLE
Clean test output

### ISSUE THREAD

**Issue by jeddy3** [stylelint/stylelint#6631] opened 2023-02-09 16:49 UTC
While releasing, I noticed two outputs breaking up the list of passing tests:

```
PASS  lib/__tests__/writeOutputFile.test.js

(node:11863) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
(Use `node --trace-deprecation ...` to show where the warning was created)
```

And:

```
PASS  lib/__tests__/overrides.test.js
  ● Console

    console.warn
      /Users/jeddy3/Projects/stylelint/lib/__tests__/fixtures/config-overrides/style.scss: When linting something other than CSS, you should install an appropriate syntax, e.g. "postcss-scss", and use the "customSyntax" option

      146 |
      147 |     if (previouslyInferredExtensions[fileExtension]) {
    > 148 |             console.warn(
          |                     ^
      149 |                     `${filePath}: When linting something other than CSS, you should install an appropriate syntax, e.g. "${previouslyInferredExtensions[fileExtension]}", and use the "customSyntax" option`,
      150 |             );
      151 |     }

      at warn (lib/getPostcssResult.js:148:11)
      at cssSyntax (lib/getPostcssResult.js:33:5)
      at getPostcssResult (lib/lintSource.js:99:10)
      at lib/standalone.js:203:27
          at async Promise.all (index 0)
      at standalone (lib/standalone.js:246:22)
      at Object.<anonymous> (lib/__tests__/overrides.test.js:207:18)

    console.warn
      /Users/jeddy3/Projects/stylelint/lib/__tests__/fixtures/config-overrides/style.scss: When linting something other than CSS, you should install an appropriate syntax, e.g. "postcss-scss", and use the "customSyntax" option

      146 |
      147 |     if (previouslyInferredExtensions[fileExtension]) {
    > 148 |             console.warn(
          |                     ^
      149 |                     `${filePath}: When linting something other than CSS, you should install an appropriate syntax, e.g. "${previouslyInferredExtensions[fileExtension]}", and use the "customSyntax" option`,
      150 |             );
      151 |     }

      at warn (lib/getPostcssResult.js:148:11)
      at cssSyntax (lib/getPostcssResult.js:33:5)
      at getPostcssResult (lib/lintSource.js:99:10)
      at lib/standalone.js:203:27
          at async Promise.all (index 0)
      at standalone (lib/standalone.js:246:22)
      at Object.<anonymous> (lib/__tests__/overrides.test.js:227:18)
```

**Comment by Mouvedia** [comment] 2023-02-09 18:51
The second one is already fixed in #6617.

**Comment by jeddy3** [comment] 2023-02-10 15:40
> About the second one. It seems to me that we should remove the following code in the first place.

SGTM. It was useful to have around for the `13.x` to `14.0` migration but its more troublesome now.

**Comment by Mouvedia** [comment] 2023-02-10 16:05
As an user, it was quite an useful hint. The problem is that the list needs to be maintained.
IMHO it should be generic, so that we don't have to maintain the list anymore.
e.g. `htm` is not picked up

**Comment by ybiquitous** [comment] 2023-02-10 16:12
> IMHO it should be generic

It seems we can adopt the idea. For example, will the list include only `postcss-scss` and `postcss-less`?

**Comment by ybiquitous** [comment] 2023-02-10 16:50
I'll open a pull request.

**Closed** 2023-02-11 03:39 UTC
Labels: status: wip, type: tests
