### ISSUE TITLE
Semver backwards compatibility and rule deprecation

### ISSUE THREAD

**Issue by ashleynolan** [stylelint/stylelint#869] opened 2016-03-07 16:21 UTC
I just wanted to flag something that’s happened a couple of times on our projects using Stylelint in our build.

It’s not a bug with the plugin, but the way rules in stylelint are deprecated atm – on minor semver releases – means that it’s not following how semver is specified and can break builds.  Semver minor updates should only include [non-breaking, backwards compatible changes](https://docs.npmjs.com/getting-started/semantic-versioning), so deprecation of rules should only happen on major releases to avoid this.

I’m not trying to be super proper about this (and love the project and work being done), but I wanted to flag this as I imagine other people are experiencing similar breaking changes in automated builds.  I’m going to change my project setup to only increment patch releases now to avoid this in future on my projects, but would be useful to know whether this will continue in minor version releases.

> Which version of stylelint are you using?

We were using `4.4.0`, and when v 4.5.0 got releases today, our build broke, as we have it setup to step up automatically on minor releases.

> How are you running stylelint: CLI, PostCSS plugin, Node API?

Using it as a PostCSS plugin

**Comment by davidtheclark** [comment] 2016-03-07 16:38
Are the deprecations breaking your build? They shouldn't be: they should just be warning you and telling you that you should probably start thinking about changing your config. 

Then when we actually *remove* the code that has been deprecated --- the change that *does* break your build --- we do deliver a major version bump.

That's the plan that we've been following and I believe it is compatible with semver, because the deprecations are not breaking. If they *are* breaking your build, please let us know the details because that's a bug that should be fixed.

**Comment by jeddy3** [comment] 2016-03-07 16:42
Sorry about this. If your build is failing then something has gone wrong with the release or we haven't accounted for something.

@davidtheclark Does the PostCSS plugin distinguish between warnings and errors? The CLI will return a different exit code, right? But would the likes of `gulp-postcss` know the difference?

@ashleynolan How are using the plugin? e.g. through a runner like `gulp-postcss` or via PostCSS Node API?

> I’m not trying to be super proper about this, but I wanted to flag it, 

We're grateful you did.

> I’m going to change my project setup to only increment patch releases now to avoid this in future on my projects, but would be useful to know whether this will continue in minor version releases.

Nope. It was a mistake that, with your help, we'll try to get to the bottom of.

**Comment by davidtheclark** [comment] 2016-03-07 16:43
> Does the PostCSS plugin distinguish between warnings and errors? The CLI will return a different exit code, right?

Ah, that's good thinking. postcss-reporter does not distinguish between severity levels. Yet another reason we need a better gulp solution.

**Comment by ashleynolan** [comment] 2016-03-07 16:46
Yeh, the deprecations do break our builds – I can see the warning, but looks like it’s throwing a full error, so it stops the build.  This is how I’m currently including it, using gulp-postcss:

```
return gulp.src([
      config.css.srcDir + '/**/*.scss'
  ])
  .pipe(
    postcss([
      stylelint(),
      reporter({
        clearMessages: true,
        throwError: true
      })
    ],
    { syntax: scss })
  );
```

**Comment by davidtheclark** [comment] 2016-03-07 16:57
So the problem is with postcss-reporter being used to break your build on *any* PostCSS warning, regardless of it's stylelint-specific "severity" level. It's not a problem with stylelint's semver, but an ecosystem problem.

The solution is to use/improve gulp-stylelint. That's in process, and I'm sure the plugin author would appreciate any help you want to offer.

**Comment by ashleynolan** [comment] 2016-03-07 17:04
Ok, that makes sense.  Could this also be improved by the `postcss-reporter` recognising differing severities, so that it can report errors and warnings?

Thanks for the help on this :+1:

**Comment by davidtheclark** [comment] 2016-03-08 14:16
The problem what adding severity recognition to postcss-reporter is that's really a stylelint-specific property, not a generic postcss-plugin property.

One possibility would be that we use postcss `message` instead of `warning` to deliver deprecation notices. We'd just have to make sure that all the reporters still work well. Somebody could look into that.

**Comment by davidtheclark** [comment] 2016-03-11 01:26
We are going to release 5.0 that removes the deprecated features. Before we add new deprecations in the future we will make sure that they do not trigger postcss-reporter to break builds. Sound good @ashleynolan?

**Closed** 2016-03-11 01:26 UTC
Labels: status: discussion

**Comment by ashleynolan** [comment] 2016-03-11 19:56
Sounds good!  Thanks for helping with this – really appreciated

**Comment by davidtheclark** [comment] 2016-03-11 21:19
Sorry about the pain in the neck.
