### ISSUE TITLE
"stylelint **/*.{css,scss,less}" run failed when has 'global.scss' file

### ISSUE THREAD

**Issue by fyangstudio** [stylelint/stylelint#5040] opened 2020-11-17 07:55 UTC
![image](https://user-images.githubusercontent.com/9896768/99224743-df47f980-2821-11eb-888d-cd29a33829c2.png)

We use npm run stylelint check style files, the script is "stylelint **/*.{css,scss,less}".

When our project has src/global.scss things got strange, no scss file be found.

I found that:

/demo-pro-1/node_modules/_stylelint@13.7.2@stylelint/bin/stylelint.js : 
```js
#!/usr/bin/env node

'use strict';

// to use V8's code cache to speed up instantiation time
require('v8-compile-cache');

require('../lib/cli')(process.argv.slice(2));
```

`**/*.{css,scss,less}`  `process.argv.slice(2)` result will become:
[ `**/*.css`, `**/*.scss`, `**/*.less` ]

when the target project directory has `src/global.scss` the `process.argv.slice(2)` result became:
[ `**/*.css`, `src/global.scss`, `**/*.less` ]

I know this issue can be fixed by add quotes.  
I just really want to know what do you think about this: some project runs well, some not.

> Which version of stylelint are you using?

e.g. `13.7.2`

**Comment by hudochenkov** [comment] 2020-11-17 09:32
If you don't use quotes then it your terminal and operating system parses glob. As you see in results is happens not consistently. We can't do anything about it, because this is what we receive from CLI. Use quotes around globs if you want reliable file matching. Then stylelint received full glob, which then parsed by stylelint.

Duplicate of #5039.

**Closed by hudochenkov** 2020-11-17 09:32 UTC
