### ISSUE TITLE
Extended config path can only be in the config file path

### ISSUE THREAD

**Issue by rygine** [stylelint/stylelint#1810] opened 2016-08-17 20:12 UTC
> Which version of stylelint are you using?

`7.1.0`

> How are you running stylelint: CLI, PostCSS plugin, Node API?

CLI with `stylelint *.css`

> Does your issue relate to non-standard syntax (e.g. SCSS, nesting, etc.)?

No

# Setup

Example folder structure

```
├ /components
│ └ /button
│   ├ /node_modules/stylelint-config-example
│   ├ index.js
│   ├ style.css
│   └ package.json
└ .stylelintrc
```

`.stylelintrc` is at the root level of the repository. My example button component is 2 levels deep.

Example `.stylelintrc`

```json
{
  "extends": "stylelint-config-example"
}
```

I'm using the CLI inside of the `/button` folder with the following command:

```sh
stylelint *.css
```

This results in the following error:

```
Error: Could not find "stylelint-config-example". Do you need a `configBasedir`?
```

> What did you expect to happen?

stylelint looks for `stylelint-config-example` in the `process.cwd()` path first, then looks where the configuration file lives.

In the above example, stylelint would look here:
* First path: `/components/button/node_modules/stylelint-config-example`
* Second path: `/node_modules/stylelint-config-example`

This is how ESLint works.

[L#75](https://github.com/stylelint/stylelint/blob/master/src/buildConfig.js#L75) in `src/buildConfig.js` is where the path is set in the above use-case.

### Why do this?

I'd like to store my stylelint configuration in one place further up the directory structure so that many modules can use the same one. This allows me to maintain only one configuration.

> What actually happened (e.g. what warnings or errors you are getting)?

stylelint only looks for configuration extensions in the same path as the configuration file be used.

In the above example, stylelint looks here: `/node_modules/stylelint-config-example`

# Next steps

Is the current behavior the intended behavior? If so, would the project be open to implement the above expected behavior?

I can submit a PR for this if it's wanted.

This is related to #1801, but I don't think it's the exact same issue. I think this is more about path resolution strategy.

**Comment by davidtheclark** [comment] 2016-08-27 19:34
@rygine Thanks for the thorough explanation. 

> Is the current behavior the intended behavior? 

Yes, this is. I believe you should be able to accomplish what you want by using the `configBaseDir` option, as the prompt suggested. Unfortunately, it looks like that option is not available in the CLI! I opened an issue for that: #1853.

> If so, would the project be open to implement the above expected behavior?

Awesome that you offered to submit a PR for this. I would be open to the change if the implementation is relatively simple. But since your intended behavior should be accomplishable with existing options (once we add that one to the CLI), I wouldn't want to add a ton of complexity for this shortcut. Does that make sense?

**Comment by davidtheclark** [comment] 2016-09-18 00:52
This and #1881 are duplicates. Since #1881 has a corresponding PR, I'll close this one and discussion should continue over there.

**Comment by davidtheclark** [comment] 2016-09-27 13:38
@rygine I'm considering this as a part of #1930. However, I'm not sure I understand the rationale. In your example, why would `.stylelintrc` want to extend the config in `button/node_modules/`? Why does `button/node_modules/stylelint-config-example` exist? I might need some more explanation to know what we'd be aiming at.

**Comment by davidtheclark** [comment] 2016-09-29 14:21
After seeing @gucong3000's example directory structure in #1935, I understand the justification for this. I will try to build it into #1930.

**Closed** 2016-10-08 14:37 UTC
Labels: status: wip, type: enhancement
