### ISSUE TITLE
Running the stylelint --fix command doesn't fix all fixable problem in the first attempt

### ISSUE THREAD

**Issue by Avivhdr** [stylelint/stylelint#5347] opened 2021-06-05 16:17 UTC
> Clearly describe the bug

Running the CLI command `npx stylelint --fix` does not fix all the fixable problems.
Only after running the command twice, are all the fixable problems fixed. See example:

![stylelintfix](https://user-images.githubusercontent.com/23265867/120897945-04b71c00-c629-11eb-914c-448ff19f7023.gif)

> Which rule, if any, is the bug related to?

I think it only happens if one of the errors is a parsing-error

> What code is needed to reproduce the bug?
```css
body {
  margin: 0
	width: 100px
	height: 200px
	top: 200px
right: 200px
	    left: 200px
}
```

> What stylelint configuration is needed to reproduce the bug?

```json
{
  "extends": [
		"stylelint-config-recommended",
		"stylelint-prettier/recommended"
	],
	"rules": {
		"selector-type-no-unknown": null
	}
}
```

> Which version of stylelint are you using?

`13.13.1`

> How are you running stylelint: 

CLI

> Does the bug relate to non-standard syntax (e.g. SCSS, Less etc.)?

The example is a css file.

> What did you expect to happen?

That I would not have to run the CLI command twice in a row

> What actually happened (e.g. what warnings or errors did you get)?

I needed to run in twice to solve all fixable issues.

**Comment by jeddy3** [comment] 2021-06-05 19:03
@Avivhdr Thanks for the report and for using the template.

> I think it only happens if one of the errors is a parsing-error

I think you're right. We use [`postcss-safe-parser`](https://github.com/postcss/postcss-safe-parser) to fix parse errors where we can, and that seems to happen after the rules have run (as we run the `indentation` rule last).

I'm going to close as a dupe of https://github.com/stylelint/stylelint/issues/3853 for now, so that we only have one issue open for this. That issue will now have a reference to this one so that anyone working on that issue should take the safe parser into account.

The issue is a little old now because we've added mitigations for most problems people encounter, e.g. we run plugins first and the `indentation` rule last, but it may become more pressing as we migrate to PostCSS@8 (see https://github.com/stylelint/stylelint/issues/4942#issuecomment-839727013).

Please consider [contributing](https://stylelint.io/contributing) to https://github.com/stylelint/stylelint/issues/3853 if you have time.

**Closed by jeddy3** 2021-06-05 19:03 UTC

**Comment by yuzihan30** [comment] 2023-09-16 06:27
git commit -m "feat: 测试styleLint" 

> investbank-web@0.1.4 lint:lint-staged
> lint-staged

✔ Preparing lint-staged...
❯ Running tasks for staged files...
  ❯ package.json — 5 files
    ✔ *.{js,jsx,ts,tsx} — 1 file
    ↓ {!(package)*.json,*.code-snippets,.!(browserslist)*rc} — no files [SKIPPED]
    ↓ package.json — no files [SKIPPED]
    ❯ *.vue — 3 files
      ✔ eslint --fix
      ✔ prettier --write
      ✖ stylelint --fix [SIGSEGV]
    ↓ *.{scss,less,styl,html} — no files [SKIPPED]
    ↓ *.md — no files [SKIPPED]
↓ Skipped because of errors from tasks. [SKIPPED]
✔ Reverting to original state because of errors...
✔ Cleaning up temporary files...

✖ stylelint --fix failed without output (SIGSEGV).


How to solve this stylelint error?
