### ISSUE TITLE
Cannot read property 'length' of undefined after updating to 13.2.0

### ISSUE THREAD

**Issue by paul-v-m** [stylelint/stylelint#4608] opened 2020-02-17 10:19 UTC
> Clearly describe the bug

Since version 13.2.0 I get an error the `Cannot read property 'length' of undefined` when running `stylelint './src/**/*.js'`. I even get it when running it just on a single empty file.

> Which rule, if any, is the bug related to?

N/A

> What CSS is needed to reproduce the bug?

N/A

> What stylelint configuration is needed to reproduce the bug?

None, it even happens on an empty config

> Which version of stylelint are you using?

`13.2.0`

> How are you running stylelint: CLI, PostCSS plugin, Node.js API?

`stylelint './src/index.js'`

> Does the bug relate to non-standard syntax (e.g. SCSS, Less etc.)?

No

> What did you expect to happen?

Anything

> What actually happened (e.g. what warnings or errors did you get)?

Full error:

```
TypeError: Cannot read property 'length' of undefined
    at Object.getPatternParts (/Users/paulverbeek-mast/code/assets/node_modules/stylelint/node_modules/fast-glob/out/utils/pattern.js:94:20)
    at PartialMatcher._getPatternSegments (/Users/paulverbeek-mast/code/assets/node_modules/stylelint/node_modules/fast-glob/out/providers/matchers/matcher.js:30:37)
    at PartialMatcher._fillStorage (/Users/paulverbeek-mast/code/assets/node_modules/stylelint/node_modules/fast-glob/out/providers/matchers/matcher.js:19:35)
    at new Matcher (/Users/paulverbeek-mast/code/assets/node_modules/stylelint/node_modules/fast-glob/out/providers/matchers/matcher.js:10:14)
    at new PartialMatcher (/Users/paulverbeek-mast/code/assets/node_modules/stylelint/node_modules/fast-glob/out/providers/matchers/partial.js:4:1)
    at DeepFilter._getMatcher (/Users/paulverbeek-mast/code/assets/node_modules/stylelint/node_modules/fast-glob/out/providers/filters/deep.js:16:16)
    at DeepFilter.getFilter (/Users/paulverbeek-mast/code/assets/node_modules/stylelint/node_modules/fast-glob/out/providers/filters/deep.js:11:30)
    at ProviderAsync._getReaderOptions (/Users/paulverbeek-mast/code/assets/node_modules/stylelint/node_modules/fast-glob/out/providers/provider.js:25:41)
    at ProviderAsync.read (/Users/paulverbeek-mast/code/assets/node_modules/stylelint/node_modules/fast-glob/out/providers/async.js:12:30)
    at Array.map (<anonymous>)
```

**Comment by paul-v-m** [comment] 2020-02-17 10:20
Ah, this probably the same as #4607

**Comment by ybiquitous** [comment] 2020-02-17 10:50
@paul-v-m Thanks for your issue report. This is a duplicate of #4607, so I close.

**Closed by ybiquitous** 2020-02-17 10:50 UTC
