### ISSUE TITLE
Add font-weight-whitelist

### ISSUE THREAD

**Issue by booc0mtaco** [stylelint/stylelint#4549] opened 2020-01-15 19:37 UTC
> What is the problem you're trying to solve?

The current rule for `font-weight-notation` has two options: "numeric" and "named-where-possible". While "numeric" is unambiguous, "named-where-possible" allows for a mix of values. Other rules like this control for value type (e.g., `color-named`, `color-no-hex`), and in our case we wish to only allow named values in the CSS. 

> What solution would you like to see?

Two options stand out:
- add an additional option to `font-weight-notation` such that only named values are allowed. Possible name for the option could be `named-only`
- add a new rule `font-weight-named` that is similar to `color-named` and only allows the fixed and relative named values for `font-weight` (e.g., "lighter", "normal", "bold", etc.). This might necessitate a refactor of the existing `font-weight-notation` rule for naming consistency purposes.

In either implementation, the new behavior would be to only allow non-numeric values for `font-weight:`, inline. CSS variable values and the [named values](https://developer.mozilla.org/en-US/docs/Web/CSS/font-weight) would be allowed.

> Related to previous rules/functionality?

- in 4.5.0, `always` option was removed from `font-weight-notation`. I'm not sure what that behavior was, but it's the only relevant functionality I could find that could be related to this new functionality.

**Comment by hudochenkov** [comment] 2020-01-15 21:40
But there is only two named values that could be transformed to numeric value: `normal` and `bold`.

You might find [`declaration-property-value-blacklist`](https://stylelint.io/user-guide/rules/declaration-property-value-blacklist) solving your problem.

**Comment by booc0mtaco** [comment] 2020-01-15 22:20
`declaration-property-value-blacklist` might actually work for me. Curious to hear the discussion on when `-where-possible` rules are appropriate. It seems that [`always-where-possible'](https://stylelint.io/user-guide/rules/color-named) for `color-named` would follow the same rules as the `named-where-possible` works for `font-weight-notation`. 

Also `color-no-hex` is the only rule I saw that is very similar to what I've proposed here. The other `*-no-*` rules are usually checking for validity. We could re-characterise this rule as `font-weight-no-numeric` as a bit of clarification.

**Comment by jeddy3** [comment] 2020-01-16 10:37
> Curious to hear the discussion on when `*-where-possible` rules are appropriate.

I tend to think of it as a scale of strictness:

- `*-where-possible` options and `*-notation` rules set a preference
- `*-no-unknown` rules are about working within the specs
- `*-black/whitelist` rules set strict subsets, think design systems

There's overlap between these rules, and you're likely to only need one in your config.

(`color-no-hex` is a bit of an oddity, but exists [because a `black/whitelist` rule would require complex regex](https://github.com/stylelint/stylelint/blob/master/docs/user-guide/about-rules.md#-whitelist--blacklist-color-named-and-applicable--no--rules).)

You have got a valid use case. I think `declaration-property-value-blacklist` would work in this instance, but I think we can make it more user-friendly by adding a new rule, one that will be useful for anyone enforcing design tokens in the CSS: `font-weight-whitelist`.

```js
{
  "font-weight-whitelist": ["normal", "bold", /^--/]
}
```

I can imagine other similar rules too e.g.

```js
{
  "line-height-whitelist": [1, 1.25, 1.5]
}
```

(Enforcing design rules with stylelint is one of my favourite use cases.)

@booc0mtaco Would `font-weight-whitelist` address your use case? @hudochenkov What do you think about adding additional whitelist rules?

**Comment by jeddy3** [comment] 2020-01-16 10:58
> but I think we can make it more user-friendly by adding a new rule

To clarify, it is shorthand properties that `declaration-property-value-blacklist` problematic i.e. the line-height or font-weight within `font`.

**Comment by booc0mtaco** [comment] 2020-01-16 19:45
@jeddy3 I think `font-weight-whitelist` could work as well. Question: it would be possible to create a similar rule for each property. Is that a good direction?

**Comment by jeddy3** [comment] 2020-01-19 10:32
> Question: it would be possible to create a similar rule for each property. Is that a good direction?

I believe so, but only where shorthands make `declaration-property-value-blacklist` tricky to use. For example:

```
a { 
  font: italic bold 1rem/1.5 sans-serief;
}

b {
  line-height: 1;
}

c {
  font-weight: normal;
}
```

The font-weight and line-height within the first rule-set are tricky to enforce with `declaration-property-value-blacklist`.

Does anyone have an objection to a `font-weight-whitelist` otherwise I'll label it up to go?

**Comment by booc0mtaco** [comment] 2020-02-07 17:20
@jeddy3 to bump this, I think the proposal would work for my use case. I'd also be happy to give implementing this rule a try :)

**Comment by jeddy3** [comment] 2020-02-07 21:44
The existing `*-blacklist` and `*-whitelist` rules target [syntactical constructs](http://apps.workflower.fi/vocabs/css/en) like functions, declarations, values and properties.  The proposal is for the first of a new class of whitelist and blacklist rules, ones that aren't just aware of the constructs of the CSS language but also the meanings within them.

For example, the existing `function-whitelist` rule won't change if the W3C adds a new function to the CSS language, e.g. [`paint()`](https://drafts.css-houdini.org/css-paint-api/#paint-notation). It will continue to work as intended whereas the proposed `font-weight-whitelist` rule will need to change if we can use font weights outside of the `font` and `font-weight` properties, perhaps in some future property.

It might be a contrived example, but offhand I can think of the following rules within this new class:

- `curve-radii-whitelist`
- `margin-whitelist`
- `padding-whitelist`
- `gutter-whitelist`
- `font-size-whitelist`
- `font-weight-whitelist`
- `font-family-list-whitelist`
- `letter-spacing-whitelist`
- `color-whitelist`
- `sizing-whitelist` ([spec ref](https://www.w3.org/TR/css-sizing-3/#sizing-properties))
- `shadow-whitelist`

And their equivalent `*-blacklist` rules. 

Each will need a deeper understanding of the CSS language than just syntactical constructs.

There's nothing inherently wrong with this, and I believe such rules would [meet the criteria for inclusion](https://stylelint.io/developer-guide/rules#criteria-for-inclusion).  However, I'd like more input from users and contributors on whether we should add, and then support, this new class of rule within stylelint as we'll need to collectively weigh-up their usefulness against their complexity.

I suggest we close this issue in favour of a new one about this broader proposal. It will allow users and contributors to understand the full context, rather than focusing on a single rule. If there is enough interest over time (usually measured in thumbs up), we can begin building these rules into stylelint.

---

Of course, that doesn't solve your immediate problem within stylelint. Fortunately, I believe the [stylelint-scales plugin pack](https://github.com/signal-noise/stylelint-scales) may solve it within userland. (Disclosure: I started that plugin pack, but someone else  maintains it now). I believe the [`scales/font-weight` rule](https://github.com/signal-noise/stylelint-scales/blob/master/lib/rules/font-weight/README.md) will cater to your use case. You may find the other [scale rules](https://github.com/signal-noise/stylelint-scales#list-of-rules]) beneficial too.

As a plugin, it can take liberties.  For example, the plugin uses "[space](https://github.com/signal-noise/stylelint-scales/blob/master/lib/rules/space/README.md)", which isn't in the specifications, to refer to [margins](https://www.w3.org/TR/css-box-3/#margins), [padding](https://www.w3.org/TR/css-box-3/#paddings), and [gutters](https://www.w3.org/TR/2016/CR-css-grid-1-20160929/#gutter). Ambiguity is convenient in the short term but problematic in the long term, which is why we generally disallow it in the built-in rules. Plugins are great as they allow us to experiment with these types of rules before building them into stylelint.

> I'd also be happy to give implementing this rule a try :)

Thank you for offering! We're always [grateful for new contributions](https://github.com/stylelint/stylelint/blob/de6f8ebdb6c4e7c49d790dff7a607112ae12792a/CONTRIBUTING.md#contributing). It might be that you contribute to [stylelint-scales](https://github.com/signal-noise/stylelint-scales) if it needs tweaking to meet your needs.

**Comment by jeddy3** [comment] 2020-02-11 16:59
Closing in favour of #4593

**Closed by jeddy3** 2020-02-11 16:59 UTC
Labels: status: needs discussion
