### ISSUE TITLE
Crash in comment-no-empty

### ISSUE THREAD

**Issue by crystalfp** [stylelint/stylelint#7398] opened 2023-12-11 18:31 UTC
### What minimal example or steps are needed to reproduce the bug?

```scss
$ui: system-ui, "Roboto","Verdana","Helvetica","Geneva","DejaVu Sans",sans-serif; 
$title: "Quattrocento Sans","Open Sans","Verdana",sans-serif;
$mono: "Roboto Mono","Consolas",monospace;
$text: "Quattrocento","Cambria","Times New Roman",serif;
```

### What minimal configuration is needed to reproduce the bug?

```json

extends:
  - stylelint-config-standard
  - stylelint-config-standard-vue
  - stylelint-config-standard-scss
  - stylelint-config-recommended-vue/scss
  - stylelint-config-recommended-scss

overrides:
- files:
  - "*.scss"
  - "**/*.scss"
  customSyntax: postcss-scss
- files:
  - "*.vue"
  - "**/*.vue"
  customSyntax: postcss-html

ignoreFiles:
  - src/styles/splitpanes.css

reportNeedlessDisables: true

rules:
  ## declaration-property-value-no-unknown: true # this rule does not accept scss variables
  alpha-value-notation: number
  at-rule-no-unknown: null
  color-function-notation: null
  color-hex-length: long
  comment-whitespace-inside: always
  declaration-block-single-line-max-declarations: 4
  font-family-no-missing-generic-family-keyword: true
  function-url-quotes: always
  max-nesting-depth: 3
  media-feature-name-no-vendor-prefix: true
  scss/at-rule-no-unknown: true
  scss/dollar-variable-empty-line-before: null
  scss/dollar-variable-pattern: null
  scss/selector-no-redundant-nesting-selector: null
  scss/double-slash-comment-empty-line-before: null
  selector-no-qualifying-type: null
  selector-pseudo-class-no-unknown: [true, {ignorePseudoClasses: [deep, slotted, global]}]
  shorthand-property-no-redundant-values: null
```

### How did you run Stylelint?

```shell
stylelint -c .stylelintrc fonts.scss

### Which Stylelint-related dependencies are you using?

```json
{
    "stylelint": "^16.0.2",
    "stylelint-config-recommended-scss": "^13.1.0",
    "stylelint-config-recommended-vue": "^1.5.0",
    "stylelint-config-standard": "^35.0.0",
    "stylelint-config-standard-scss": "^11.1.0",
    "stylelint-config-standard-vue": "^1.0.0",
```

### What did you expect to happen?

As before the last upgrade (today) from 15.11.0 to 16.0.2 that everything works

### What actually happened?

PS D:\Projects\IIE> stylelint .\src\styles\fonts.scss
TypeError: Cannot read properties of undefined (reading 'rejected')
    at Object.<anonymous> (D:\Projects\IIE\node_modules\stylelint-scss\src\rules\comment-no-empty\index.js:12:42)
    at Module._compile (node:internal/modules/cjs/loader:1233:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1287:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Module._load (node:internal/modules/cjs/loader:938:12)
    at Module.require (node:internal/modules/cjs/loader:1115:19)
    at require (node:internal/modules/helpers:130:18)
    at Object.<anonymous> (D:\Projects\IIE\node_modules\stylelint-scss\src\rules\index.js:31:23)
    at Module._compile (node:internal/modules/cjs/loader:1233:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1287:10)

### Do you have a proposal to fix the bug?

No, even disabling the rule `comment-no-empty` changes nothing.

**Comment by ybiquitous** [comment] 2023-12-11 18:38
@crystalfp Thanks for the report with a reproduction. The cause seems `stylelint-scss` is outdated. Can you try updating it? Today, `stylelint-scss` published a new version: https://github.com/stylelint-scss/stylelint-scss/releases/tag/v6.0.0

**Comment by ybiquitous** [comment] 2023-12-12 03:53
I'm closing this. Please reopen if you still have a problem.

**Closed by ybiquitous** 2023-12-12 03:53 UTC
Labels: status: needs clarification

**Comment by crystalfp** [comment] 2023-12-12 12:50
`"stylelint-config-recommended-scss"` and/or `"stylelint-config-standard-scss"` were outdated. After updating them the problem disappeared.
