### ISSUE TITLE
VSCode Stylelint | Cannot find module 'postcss-jsx/extract'

### ISSUE THREAD

**Issue by asilvadesigns** [stylelint/stylelint#3323] opened 2018-05-21 19:33 UTC
If I could open an issue in the plugin repo, I would.
Unfortunately, at this point only contributors are allowed to do so.

Within VSCode(insiders and or stable) when using the stylelint plugin, throws an Error on load with the following message:
```
Error: Cannot find module 'postcss-jsx/extract' at Function.Module._resolveFilename (module.js:470:15) at Function.Module._load (module.js:418:25) at Module.require (module.js:498:17) at require (internal/module.js:20:19) at rules.filter.map.rule (/Users/USER/.vscode-insiders/extensions/shinnn.stylelint-0.36.1/node_modules/stylelint/node_modules/postcss-syntax/processor.js:9:19) at Array.map (native) at processor (/Users/USER/.vscode-insiders/extensions/shinnn.stylelint-0.36.1/node_modules/stylelint/node_modules/postcss-syntax/processor.js:6:54) at Object.parse (/Users/USER/.vscode-insiders/extensions/shinnn.stylelint-0.36.1/node_modules/stylelint/node_modules/postcss-syntax/parse.js:18:9) at new LazyResult (/Users/USER/.vscode-insiders/extensions/shinnn.stylelint-0.36.1/node_modules/postcss/lib/lazy-result.js:70:24)  at Processor.process (/Users/USER/.vscode-insiders/extensions/shinnn.stylelint-0.36.1/node_modules/postcss/lib/processor.js:117:12)
```

**Comment by Arcanemagus** [comment] 2018-05-21 20:07
From https://github.com/shinnn/vscode-stylelint/issues/182#issuecomment-390665800 it looks like this is a duplicate of https://github.com/stylelint/stylelint/issues/3317#issuecomment-390223935. Since the fixed version is allowed by the range re-installing the VSCode plugin _should_ get things working for you, otherwise you'll need to wait for [v9.2.2](https://github.com/stylelint/stylelint/issues/3319) and `vscode-stylelint` to update to that.

**Closed by Arcanemagus** 2018-05-21 20:07 UTC

**Comment by asilvadesigns** [comment] 2018-05-21 20:26
@Arcanemagus thank you!

**Comment by ntwb** [comment] 2018-05-22 00:46
@shinnn I'm not sure what the reasoning is behind not being able to open issues on that repo but could some info be added to the readme.md explaining what the support options are, i.e. if there is a recommended support forum, e.g. https://stackoverflow.com/ then add that

**Comment by Arcanemagus** [comment] 2018-05-22 01:32
@ntwb It's a temporary measure that can only be enabled for 24 hours in a repo's setting:

![image](https://user-images.githubusercontent.com/427137/40337599-50fdec1c-5d25-11e8-8999-f9a27f6d8a89.png)

No idea why it's been enabled there though 🤷‍♂️.

**Comment by shinnn** [comment] 2018-05-22 01:51
> Since the fixed version is allowed by the range re-installing the VSCode plugin should get things working for you

No. stylelint v9.2.1 is still broken.

```
$ npm i stylelint
npm WARN postcss-markdown@0.23.7 requires a peer of postcss-syntax@^0.10.0 but none is installed. You must install peer dependencies yourself.
npm WARN postcss-html@0.23.7 requires a peer of postcss-syntax@^0.10.0 but none is installed. You must install peer dependencies yourself.

+ stylelint@9.2.1
```

```js
'use strict';

const {lint} = require('stylelint');

(async () => {
  try {
    await lint({
      code: '',
      codeFilename: 'exmaple.jsx',
      config: {
        rules: {}
      }
    });
  } catch (e) {
    console.error(e);
  }
})();
```

```console
$ node index.js
{ Error: Cannot find module 'postcss-jsx/extract'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:571:15)
    at Function.Module._load (internal/modules/cjs/loader.js:497:25)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at rules.filter.map.rule (/Users/shinnn/github/style/node_modules/postcss-syntax/processor.js:9:19)
    at Array.map (<anonymous>)
    at processor (/Users/shinnn/github/style/node_modules/postcss-syntax/processor.js:6:54)
    at Object.parse (/Users/shinnn/github/style/node_modules/postcss-syntax/parse.js:18:9)
    at new LazyResult (/Users/shinnn/github/style/node_modules/postcss/lib/lazy-result.js:70:24)
    at Processor.process (/Users/shinnn/github/style/node_modules/postcss/lib/processor.js:117:12) code: 'MODULE_NOT_FOUND' }
```

Even if I install stylelint from the latest `master` ecd7c0a89ef3d0c164770883852b3574a013144e, 

```
$ npm i stylelint/stylelint#ecd7c0a89ef3d0c164770883852b3574a013144e
+ stylelint@9.2.1
```

it results in the same error.

> No idea why it's been enabled there though

You can use a web search engine to learn what the feature is. https://www.google.com/search?q=github+temporary+interaction+limits

**Comment by evilebottnawi** [comment] 2018-06-08 11:52
@shinnn can you create issue in stylelint?

**Comment by shinnn** [comment] 2018-06-08 15:53
@evilebottnawi No. https://github.com/stylelint/stylelint/issues/3323#issuecomment-390837505 is enough.
