### ISSUE TITLE
After Nuxt3 update: Error: No configuration provided

### ISSUE THREAD

**Issue by TimGuendel** [stylelint/stylelint#7581] opened 2024-03-26 09:56 UTC
### What minimal example or steps are needed to reproduce the bug?

After updating my Nuxt App to 3.11.1, stylelint does not work anymore - not sure if this a nuxt or stylelint problem. After the update, the config fil (.stylelintrc.cjs in the root folder of the app) is not found anymore.

This happens when running stylelint with yarn or directly inside my IDE.

### What minimal configuration is needed to reproduce the bug?

```
module.exports = {
    plugins: ['stylelint-scss'],
    extends: ['stylelint-config-recommended-scss', 'stylelint-config-recommended-vue/scss'],
    rules: {
      // many rules
    }
```

### How did you run Stylelint?

Inside package.json:

`"lint:style": "stylelint \"**/*.{vue,scss,css}\"",`

or inside Webstorm

### Which Stylelint-related dependencies are you using?

```     "stylelint": "^16.2.1",
        "stylelint-config-recommended-scss": "^14.0.0",
        "stylelint-config-recommended-vue": "^1.5.0",
        "stylelint-scss": "^6.2.0",
```

### What did you expect to happen?

No errors

### What actually happened?

```"C:\Program Files\nodejs\yarn.cmd" run lint:style
Error: No configuration provided for C:\dev\frontend-web-2\layouts\default.vue
    at configurationError (file:///C:/dev/frontend-web-2/node_modules/stylelint/lib/utils/configurationError.mjs:12:49)
    at getConfigForFile (file:///C:/dev/frontend-web-2/node_modules/stylelint/lib/getConfigForFile.mjs:67:4)
    at async isPathIgnored (file:///C:/dev/frontend-web-2/node_modules/stylelint/lib/isPathIgnored.mjs:23:17)
    at async lintSource (file:///C:/dev/frontend-web-2/node_modules/stylelint/lib/lintSource.mjs:43:20)
    at async file:///C:/dev/frontend-web-2/node_modules/stylelint/lib/standalone.mjs:214:27
    at async Promise.all (index 1)
    at async standalone (file:///C:/dev/frontend-web-2/node_modules/stylelint/lib/standalone.mjs:257:22)

Process finished with exit code 78
```

**Comment by volarname** [comment] 2024-03-26 10:16
same issue on pure vue 3 project without nuxt

**Comment by ybiquitous** [comment] 2024-03-26 10:57
@TimGuendel Thanks for the report. This seems to be the same as #7577, which has been closed. I'll release the fixed version soon. Please be patient 🙏🏼

**Comment by ybiquitous** [comment] 2024-03-26 10:57
Duplicate of #7577

**Closed by ybiquitous** 2024-03-26 10:57 UTC
