### ISSUE TITLE
Add ignoreCustomProperties: [] to value-keyword-case

### ISSUE THREAD

**Issue by klimashkin** [stylelint/stylelint#2862] opened 2017-09-06 20:59 UTC
**Feature request**

In most cases `value-keyword-case` should be `'lower'` in our project, but since we use css modules and camelCase class names, we compose that class names:
```css
.headerItem {
   align-self: stretch
}

.title {
  composes: headerItem; // Error
}
```

Also, we would like to keep some font family names in natural capitalized notation:
```css
font-family:
  -apple-system,      /* iOS Safari, macOS Safari, macOS Firefox (San Francisco) */
  BlinkMacSystemFont, /* macOS Chrome (San Francisco) */
  'Segoe UI',         /* Windows */
  Roboto,             /* Android, Chrome OS */
  Oxygen-Sans,        /* KDE */
  Ubuntu,             /* Ubuntu */
  Cantarell,          /* GNOME */
  'Helvetica Neue',   /* Fallback, native for macOS versions < 10.11 or custom will be downloaded for others */
  Arial, sans-serif;  /* Fallback if Helvetica Neue can't be downloaded for some reason */
```

Rule could look like:
```javascript
'value-keyword-case': ['lower', {
  ignoreProps: ['composes', 'font-family']
}],
```

**Comment by evilebottnawi** [comment] 2017-09-07 08:15
@stylelint/core i think we should **always** ignore `font-family` and `font-family` in ``font` properties

**Comment by jeddy3** [comment] 2017-09-09 22:56
> Add ignore properties in value-keyword-case

Yes, that's the appropriate solution here. @klimashkin Please consider contributing this option if you have time. There's [a section in the Developer Guide](https://github.com/stylelint/stylelint/blob/master/docs/developer-guide/rules.md#adding-an-option-to-an-existing-rule) on how to get started.

It would be `ignoreProperties: []`, rathe than `ignoreProps`, for consistency with other rules e.g. [`property-no-unknown`](https://github.com/stylelint/stylelint/tree/master/lib/rules/property-no-unknown), where you'll find example code, tests and documentation for such an option.

> @stylelint/core i think we should always ignore font-family and font-family in font properties

I believe it already does. From the rule's README:

> This rule ignores [`<custom-idents>`](https://developer.mozilla.org/en/docs/Web/CSS/custom-ident) of known properties.

@klimashkin So, you shouldn't need this option for `font` and `font-family`, but will need for the non-standard `composes`.

**Comment by klimashkin** [comment] 2017-09-09 23:35
@jeddy3 You are right, if I put font names into `font`/`font-family` properties it is fine, by I use custom property (sorry didn't point it out), and in that case I get an error

```javascript
  --fontFamily:
    -apple-system,      /* iOS Safari, macOS Safari, macOS Firefox (San Francisco) */
    BlinkMacSystemFont, /* macOS Chrome (San Francisco) */
    'Segoe UI',         /* Windows */
    Roboto,             /* Android, Chrome OS */
    Oxygen-Sans,        /* KDE */
    Ubuntu,             /* Ubuntu */
    Cantarell,          /* GNOME */
    'Helvetica Neue',   /* Fallback */
    Arial, sans-serif;  /* Fallback if Helvetica Neue can't be downloaded for some reason */
```

**Comment by jeddy3** [comment] 2017-09-09 23:58
> But in that case probably stylelint can't figure it out properly..

Yep.

It looks like another option might be needed: `ignoreCustomProperties: []`.  Can you please create a  new issue for that, so that this issue can just be about the `ignoreProperties: []` option?

**Comment by jeddy3** [comment] 2017-09-10 00:05
Scratch that... I just spotted that this issue is a dupe of https://github.com/stylelint/stylelint/issues/2424. 

I'll simply convert this issue to `ignoreCustomProperties: []` to save time.

@klimashkin Feel free to contribute both options, if you like.

**Comment by klimashkin** [comment] 2017-10-12 01:11
With new `ignoreProperties` in `8.2.0` it is now possible to 
```
ignoreProps: ['composes', '--fontFamily']
```
 so probably there is no need in `ignoreCustomProperties `

**Comment by jeddy3** [comment] 2017-10-12 08:05
@klimashkin Thanks for spotting that. I believe that's actually a bug that needs to be patched. The `ignore*` option should only accept _names_ of things, e.g. names of at-rules or custom properties. Whereas the `@` and `--` denote the thing itself. I think it's better we patch this so the behaviour of this `ignoreProperties` option is _consistent_ with all the other `ignore*` options, and then a separate `ignoreCustomProperties` option.

**Comment by abdonrd** [comment] 2017-10-12 08:41
About naming... Reference to [Custom Properties in the CSSWG](https://drafts.csswg.org/css-variables/#defining-variables).

**Comment by jeddy3** [comment] 2017-10-12 08:52
@abdonrd Many thanks for chiming in! I stand corrected :) Custom properties are properties whom's name starts with a `--`. So, the current behaviour does seem correct.

I had a quick trawl through the other `ignoreProperties` options in other rules and they appear to behave in this way too. So, I think we can close this issue.

**Closed by jeddy3** 2017-10-12 08:52 UTC
Labels: beginner friendly, Hacktoberfest, status: help wanted, type: new option
