### ISSUE TITLE
postcss-sass as customSyntax not working

### ISSUE THREAD

**Issue by lili21** [stylelint/stylelint#2531] opened 2017-04-26 06:20 UTC
> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

A bug.

> Which rule, if any, is this issue related to?

`customeSyntax` option

> What CSS is needed to reproduce this issue?

non

> What stylelint configuration is needed to reproduce this issue?

```
{
  customeSynax: path.join(__dirname, '../node_modules/postcss-sass//index.js'),
  config: { extends: 'stylelint-config-standard' }
}
```

> Which version of stylelint are you using?

`7.10.1`

> How are you running stylelint: CLI, PostCSS plugin, Node API?

[stylelint-webpack-plugin](https://github.com/JaKXz/stylelint-webpack-plugin)

> Does your issue relate to non-standard syntax (e.g. SCSS, nesting, etc.)?

no

> What did you expect to happen?

no error

> What actually happened (e.g. what warnings or errors you are getting)?

```
SyntaxError: Unexpected part "8" (char 3)
    at createSyntaxError (/Users/markli/dev/napos/melody/node_modules/mathjs/lib/expression/parse.js:1524:17)
    at parseStart (/Users/markli/dev/napos/melody/node_modules/mathjs/lib/expression/parse.js:507:15)
    at parse (/Users/markli/dev/napos/melody/node_modules/mathjs/lib/expression/parse.js:66:14)
    at string (/Users/markli/dev/napos/melody/node_modules/mathjs/lib/expression/function/eval.js:43:14)
    at Object.compile (eval at _typed (/Users/markli/dev/napos/melody/node_modules/typed-function/typed-function.js:1115:22), <anonymous>:22:14)
    at process (/Users/markli/dev/napos/melody/node_modules/postcss-sass/index.js:230:43)
    at process (/Users/markli/dev/napos/melody/node_modules/postcss-sass/index.js:163:17)
    at process (/Users/markli/dev/napos/melody/node_modules/postcss-sass/index.js:61:25)
    at process (/Users/markli/dev/napos/melody/node_modules/postcss-sass/index.js:112:25)
    at process (/Users/markli/dev/napos/melody/node_modules/postcss-sass/index.js:41:13)
    at sassToPostCssTree (/Users/markli/dev/napos/melody/node_modules/postcss-sass/index.js:302:12)
    at new LazyResult (/Users/markli/dev/napos/melody/node_modules/postcss/lib/lazy-result.js:70:24)
    at Processor.process (/Users/markli/dev/napos/melody/node_modules/postcss/lib/processor.js:117:12)
    at getCode.then.e (/Users/markli/dev/napos/melody/node_modules/stylelint/lib/getPostcssResult.js:83:29)
```

**Comment by evilebottnawi** [comment] 2017-04-26 09:49
@lili21 now we don't have support `postcss-sass`, see https://github.com/stylelint/stylelint/pull/2503, your can help with this, but seems it is bug in parser, you can try to find what is now correct parse and create issue in `postcss-sass`

**Comment by evilebottnawi** [comment] 2017-04-26 10:20
@lili21 also you can see https://github.com/stylelint/stylelint/issues/2533#issuecomment-297337181

**Comment by jeddy3** [comment] 2017-04-26 11:37
Closing as a dupe of https://github.com/stylelint/stylelint/issues/2486

@lili21 Please consider assisting @AleshaOleg in his endeavours to write a PostCSS-based SASS parser.

**Closed by jeddy3** 2017-04-26 11:37 UTC

**Comment by ntwb** [comment] 2017-04-29 06:36
Typu FYI: Just in case, it's `customSyntax` not `customeSyntax`, remove the extra `e`
