### ISSUE TITLE
Fix EBADENGINE error for Node.js 14.13.1 through 14.17.x

### ISSUE THREAD

**Issue by bbrk24** [stylelint/stylelint#6729] opened 2023-03-23 20:53 UTC
### Describe the documentation issue

The package.json says it supports `"node": "^14.13.1 || >=16.0.0"`. However, it also lists as a dependency `"supports-hyperlinks": "^3.0.0"`, which requires `"node": ">=14.18"`. Thus, attempting to install using versions of node older than 14.18 results in EBADENGINE.

### What solution would you like to see?

There are three possible solutions:

- Say that listing the lower bound as 14.13.1 was a mistake, and bump it to 14.18.0 or higher. I think this could be semver-patch.
- Make supports-hyperlinks an optional dependency, or remove it altogether.
- Revert to support-hyperlinks 2, which supports earlier versions of node.

I'm not familiar enough with the codebase to say which is the best idea.

**Comment by bbrk24** [comment] 2023-03-23 21:38
I didn't notice this at first, but I double-checked just now and that's not the only dependency that can trigger this: write-file-atomic 5 requires node `^14.17.0 || ^16.13.0 || >=18.0.0`.

**Comment by ybiquitous** [comment] 2023-03-24 04:07
@bbrk24 Thanks for the report. Is a workaround of [`engine-strict=false`](https://docs.npmjs.com/cli/v9/using-npm/config#engine-strict) reasonable?

**Comment by bbrk24** [comment] 2023-03-24 04:10
All that does is demote it from an error to a warning -- and, since it currently isn't specified, it's false by default anyways.

**Comment by ybiquitous** [comment] 2023-03-24 04:25
Do you know how to detect an inconsistency of `engines.node`?

**Comment by bbrk24** [comment] 2023-03-24 15:20
No, I'm not aware of any automated tool, but also I haven't looked very hard. I discovered the issue with write-file-atomic by grepping package-lock.json (I was using node 14.17, so only supports-hyperlinks triggered EBADENGINE).

I decided to go back and double-check with the same method, and I found that none of the `@csstools` packages support node 17 -- they require `^14 || ^16 || >=18`. I fully understand the need for such a tool.

**Comment by romainmenke** [comment] 2023-03-26 16:50
> I found that none of the @csstools packages support node 17

We can relax this if needed.

**Comment by bbrk24** [comment] 2023-03-26 19:29
I just created a simple tool to check this: https://github.com/bbrk24/engine-check. I haven't tested it super thoroughly yet but it seems to work so far.

Sample output:
```
@csstools/css-parser-algorithms@2.0.1 requires node "^14 || ^16 || >=18".
@csstools/css-tokenizer@2.1.0 requires node "^14 || ^16 || >=18".
@csstools/media-query-list-parser@2.0.1 requires node "^14 || ^16 || >=18".
@csstools/selector-specificity@2.2.0 requires node "^14 || ^16 || >=18".
supports-hyperlinks@3.0.0 requires node ">=14.18".
write-file-atomic@5.0.0 requires node "^14.17.0 || ^16.13.0 || >=18.0.0".
```

**Comment by ybiquitous** [comment] 2023-03-27 00:15
@bbrk24 Thanks for sharing your tool. I just confirmed it works on my local machine.

For now, the following way seems easier because changes between <https://github.com/jamestalmage/supports-hyperlinks/compare/v2.3.0...v3.0.0> do not seem to include significant things: 

> Revert to support-hyperlinks 2, which supports earlier versions of node.

But I still have a few questions:

- Do we need to address `engines.node` strictly in the whole dependency tree? 
- Is not there a best practice or something in the Node.js community to address such a problem?
- Will we need to check inconsistency all the time in the future?

By the way, note that Node.js v14 will [become end-of-life](https://nodejs.dev/en/about/releases/) on April 30 this year. So we will drop the support with the next Stylelint major version.

**Comment by bbrk24** [comment] 2023-03-27 00:28
> Do we need to address engines.node strictly in the whole dependency tree?

As I mentioned earlier, I use node 14.17, so the others don't affect me directly. However, write-file-atomic does prevent using earlier minor versions of node 14.

I'm not as concerned about @csstools, since node 17 has already reached end of life.

> Is not there a best practice or something in the Node.js community to address such a problem?
> Will we need to check inconsistency all the time in the future?

I would like to believe there's an existing solution for this, but I'm not aware of one.

> By the way, note that Node.js v14 will [become end-of-life](https://nodejs.dev/en/about/releases/) on April 30 this year. So we will drop the support with the next Stylelint major version.

Thanks for the heads-up. I'll have to change my configuration to use v16 or v18 by default instead of v14. As a side note, I'm not aware of any other language that goes through major versions as quickly as Node does.

**Comment by ybiquitous** [comment] 2023-03-27 01:31
It seems reasonable to wait until Node.js v14 EOL (about a month left) unless people complain about this inconsistency.

For future releases, we might need to consider any way to check `engines.node` consistency... 🤔

**Comment by ybiquitous** [comment] 2023-03-28 02:46
I just opened an issue to remove Node.js 14 support: #6740

**Comment by jeddy3** [comment] 2023-08-14 13:36
Closed by https://github.com/stylelint/stylelint/pull/7020

**Closed by jeddy3** 2023-08-14 13:36 UTC
Labels: status: needs discussion
