### ISSUE TITLE
sylelint installation with npm

### ISSUE THREAD

**Issue by raphael-quadrini** [stylelint/stylelint#5073] opened 2020-12-12 16:51 UTC
> Clearly describe the bug
the command 
     npm i -g stylelint
failed

it seems to to be linked to a problem of json structure
please see log attached
[2020-12-12T16_18_58_096Z-debug.log](https://github.com/stylelint/stylelint/files/5683454/2020-12-12T16_18_58_096Z-debug.log)

> Which version of stylelint are you using?

@latest

**Comment by raphael-quadrini** [comment] 2020-12-12 17:34
Please, check the json files are at the root of the package.
At the moment it's not the case as they are in the stylelint-master directory.
I guess this folder shouldn't exist and all the content of this directory should be at the root of the zip.  
-- description of the used procedure to test --
I downloaded the zip file
and unziped it.
i repacked it with :
cd stylelint-master
tar czvf ../stylelint-master.tar.gz ./*
I ran again npm using stylelint-master.tar.gz in a local installation
the package was installed  properly.

**Comment by raphael-quadrini** [comment] 2020-12-12 18:01
I also checked https://github.com/stylelint/stylelint/archive/13.8.0.tar.gz.
It's the same issue. The files and folders are in a directory : stylelint-13.8.0.

Please, can u fix it so i can run the dojo.io @dojo/cli-create-app?

**Comment by malsf21** [comment] 2020-12-15 20:18
Hm, @raphael-quadrini I can't reproduce this with just `npm i -g stylelint` - can you give us more information with what operating system, version of node, etc. you're using? I'd recommend you follow the issue template, so that it's easier for us to help you.

**Comment by jeddy3** [comment] 2020-12-17 11:23
Closing for now. @raphael-quadrini You're welcome to open a new issue using the template and including a reproducible repo.

**Closed by jeddy3** 2020-12-17 11:23 UTC
Labels: status: needs clarification, status: needs reproducible example
