### ISSUE TITLE
Refactor stylelint cli distribution binary location 

### ISSUE THREAD

**Issue by ntwb** [stylelint/stylelint#1968] opened 2016-10-10 08:26 UTC
This issue relates to a [discussion](https://github.com/stylelint/stylelint/pull/1930#issuecomment-251326408) had in #1930 regarding the stylelint `cli.js` file location.

Currently there's no easy way to test unpublished NPM versions of stylelint.

Some use cases:
• Testing upcoming changes such as the refactor in #1930 
• stylelint users needing to "pin" a particular branch, pull request or fork of stylelint

NPM [documention](https://docs.npmjs.com/files/package.json#git-urls-as-dependencies) suggests changing the URL in `package.json` to match the fork or branch you want to use, for example: `"git@github.com:stylelint/stylelint.git#some-branch-or-commit"`

Utilising the above method fails though with error: `ENOENT: no such file or directory, chmod '/usr/local/lib/node_modules/stylelint/dist/cli.js'`

There are various manual ways to workaround the issue such as copy and paste another clone of the fork or branch you wish to use over an existing install, use `npm link` to link to another clone of the fork or branch you wish to use.

Part of the refactor in #1930 was testing cosmiconfig v2, commit https://github.com/stylelint/stylelint/pull/1930/commits/17c8015c595d957cb0e8b5cad26737a8df1a30de shows the above method in action and showcasing this to test against cosmiconfig `v2` branch with a minor change in the `package.json` file: `"cosmiconfig": "davidtheclark/cosmiconfig#v2"`

It would be great if stylelint users could benefit from the same simplicity, if users wanted to test against the next major version 8 of stylelint a change in their `package.json` file to: `"stylelint": "stylelint/stylelint#v8"` would be all that was required.

-----

The issue itself revolves around the CLI location `/dist/cli.js`, this is symlinked by NPM via [this code](https://github.com/stylelint/stylelint/blob/master/package.json#L23) in `package.json` file: `"bin": "dist/cli.js",`

One of the workarounds is to run `npm run build` which then copies `cli.js` to `/dist/cli.js` which in turn makes the binary file available for the NPM symlink.

Of note, ESLint, uses [the following](https://github.com/eslint/eslint/blob/master/package.json#L6-L8) path for its binary
```js
  "bin": {
    "eslint": "./bin/eslint.js"
  },
```

The stylelint binary is *also* available in this location as part of NPM's symlinking process.

Would this be sufficient that stylelint inks the binary in a similar way be all we need?

**Comment by davidtheclark** [comment] 2016-10-10 14:12
Feel free to give that a try, but I don't know any reason it should work. 

> One of the workarounds is to run npm run build which then copies cli.js to /dist/cli.js which in turn makes the binary file available for the NPM symlink.

I doubt there is any way around the need to run `npm run build` if you are not using a standard npm install, which runs that command automatically. Even if we made `cli.js` not rely on Babel transformations, the files that it imports would. If everything works, though, after you `npm run build`, that's not too bad for development.

I think the root of the problem is that we're Babel. If you want to look around for solutions, this might be what needs to be searched for.

**Comment by jeddy3** [comment] 2016-10-22 12:21
> I doubt there is any way around the need to run `npm run build` 

I believe this is the case.

I think we can close this issue with the addition of a FAQ entry:

---

How do I "pin" a particular branch, pull request or fork of stylelint in my `package.json`?

Use [`npm-git-install`](https://github.com/lzrski/npm-git-install), to work around [a current limitation](https://github.com/npm/npm/issues/3055) of `npm`.

---

**Comment by ntwb** [comment] 2016-10-27 10:12
Fantastic, from my quick read of the upstream issue and `npm-git-install` docs this will do the trick. 

Next time I need to test this out I'll document some of the commands used and see if they're worth adding to the FAQ.

Thanks heaps for this @jeddy3 and @davidtheclark and as is probably obvious I've not been around much recently, lots of work on at the moment 😄

**Closed** 2016-10-27 11:05 UTC
Labels: status: wip, type: documentation
