### ISSUE TITLE
Autofix removes the number sign in the color value of border shorthand notations

### ISSUE THREAD

**Issue by mindnektar** [stylelint/stylelint#6912] opened 2023-06-09 07:00 UTC
### What steps are needed to reproduce the bug?

https://stylelint.io/demo/#N4Igxg9gJgpiBcIoEsBuAdAdgAmwIwgCdZCBaAgFwogFt5sBGABwA9sBnCAG2SmwGIAIgA4RIkABoQAM2RcYAOQCGNOIhgsVTeQDp2S9u0ngImWQHMEIYFlzpwAV3bUaAZQCemCkpb369pghnMENSfUN7CVtse0IHeXY-bGAAXywU40gzZHMAMSIaJQorACtOTGNYJiNEGxwYkEDg0PDEhAaABh0AVh0OyOj7Z3d5Hi8k+wZegHY++3SQFKA

### What Stylelint configuration is needed to reproduce the bug?

None

### How did you run Stylelint?

See demo

### Which version of Stylelint or dependencies are you using?

15.7.0

### What did you expect to happen?

The number sign should be left alone.

### What actually happened?

The number sign is removed by autofix.

Additional info: Rules such as `color-hex-case` seem to be ignored in border shorthand notations.

**Comment by ybiquitous** [comment] 2023-06-09 14:50
@mindnektar Thanks for the report with the reproducible demo. Unfortunately, this seems to be a bug of `postcss-sass`, not `stylelint`. See the following:

```js
const sass = require('postcss-sass');
const code = `
div
  border-bottom: 1px solid #D8D8D8
`;
sass.parse(code).walkDecls(({ prop, value }) => console.log(`${prop}: ${value}`));
```

When running this code with the `node` command, it outputs:

```
border-bottom: 1px solid D8D8D8
```

`#` before the color hex value is missing. I guess there is no way to avoid this bug with Stylelint.

**Comment by ybiquitous** [comment] 2023-06-09 14:53
A similar issue about autofix is reported on https://github.com/AleshaOleg/postcss-sass/issues/175. `postcss-sass` may not be maintained now.

**Comment by mindnektar** [comment] 2023-06-13 09:51
Oof. Thanks for looking into it, and yes, you're quite right in that it's a `postcss-sass` issue. It happens to be one of many issues unfortunately, as I had the displeasure of finding out while diving deeper into integrating stylelint in our project 🙈 

`postcss-sass` is indeed unmaintained, so that's a problem. Migrating our code from sass to scss, less, postcss or something along those lines would be too big of an undertaking right now (and I still like the sass syntax too much to switch anyway), and I don't have the time to become an active maintainer of the `postcss-sass` library. I do have the time to fix the issues stopping me personally from using stylelint, though, which is what I'm currently doing. As I go, I'm publishing my fixes [here](https://www.npmjs.com/package/postcss-sass-2), so if that somehow happens to be helpful to anyone else, they're very welcome to it.

As far as I'm concerned, you can close this issue, unless of course there is something you feel would be useful to do on the stylelint side.

**Comment by ybiquitous** [comment] 2023-06-13 12:24
@mindnektar I'm glad to hear that you've published your fork version of `postcss-sass`!

If you continue maintaining your `postcss-sass-2` and are interested, please consider adding it to [Awesome Stylelint](https://github.com/stylelint/awesome-stylelint) for anyone who needs it. 🙏🏼 

I'm closing this issue since we cannot resolve it at this point.

**Closed by ybiquitous** 2023-06-13 12:24 UTC
Labels: status: needs discussion, syntax: sass, upstream
