### ISSUE TITLE
Fatal error: Cannot read property 'slice' of null

### ISSUE THREAD

**Issue by jimbateson** [stylelint/stylelint#899] opened 2016-03-10 12:13 UTC
> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

A bug where after running through a certain number of files task fails  with message 

"Fatal error: Cannot read property 'slice' of null"

> What stylelint configuration is needed to reproduce this issue?

```json
{
  "rules": {
	"no-indistinguishable-colors": true
  }
}
```

> Which version of stylelint are you using?

4.5.0

> How are you running stylelint: CLI, PostCSS plugin, Node API?

PostCSS Grunt plugin

> Does your issue relate to non-standard syntax (e.g. SCSS, nesting, etc.)?

SCSS

> What did you expect to happen?

Run through all SCSS files in directory 

> What actually happened (e.g. what warnings or errors you are getting)?

The task failed after running about hafway through the "components" SCSS directory. Tried removing the directory but fails while running through any other directory, with this error message (no line number or file given):

"Fatal error: Cannot read property 'slice' of null"

**Comment by davidtheclark** [comment] 2016-03-10 13:23
Please provide the full stack trace and reduce your test case. Can you give us some minimal CSS that causes the problem, and reduce the rules down?

**Comment by evilebottnawi** [comment] 2016-03-10 14:02
@jimbateson @davidtheclark i think this issue related to https://github.com/stylelint/stylelint/issues/875

**Comment by jimbateson** [comment] 2016-03-10 15:13
@evilebottnawi @davidtheclark Yes setting the ```no-indistinguishable-colors``` rule to ```null``` has allowed the task to run through the rest of the files. Thanks for the pointer!

**Comment by davidtheclark** [comment] 2016-03-10 16:19
OK, then sounds like this is a duplicate of #875.

**Closed by davidtheclark** 2016-03-10 16:19 UTC
