### ISSUE TITLE
Missing parentheses in calc will cause crash

### ISSUE THREAD

**Issue by ArthurClemens** [stylelint/stylelint#2265] opened 2017-01-17 12:20 UTC
> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

A bug

> Which rule, if any, is this issue related to?

none

> What CSS is needed to reproduce this issue?

e.g.

```css
top: calc((1px * 2);
```

> What stylelint configuration is needed to reproduce this issue?

not relevant

> Which version of stylelint are you using?

`7.7.1`

> How are you running stylelint: CLI, PostCSS plugin, Node API?

npm script: `"./node_modules/.bin/stylelint \"src/**/*.css\""`

> Does your issue relate to non-standard syntax (e.g. SCSS, nesting, etc.)?

No, this is an error in the CSS

> What did you expect to happen?

A message like "Error in markup" or "Could not parse block".

> What actually happened (e.g. what warnings or errors you are getting)?

Output:

```shell
npm ERR! Darwin 16.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "lint:css"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
```

No further files are processed after this.

**Comment by evilebottnawi** [comment] 2017-01-17 12:23
@ArthurClemens please use template

**Comment by jeddy3** [comment] 2017-01-18 10:19
@ArthurClemens Thanks for updating the issue to use the template.

I can't reproduce this I'm afraid.

The following:

```css
a {
  top: calc((1px * 2);
}
```

Correctly produces:

```console
2:12 error Unclosed bracket (CssSyntaxError)
```

> No further files are processed after this.

Because there is a syntax error, the file can't be processed and so no checks can be made. 

As an aside,

```
 npm ERR! Darwin 16.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "lint:css"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
```

is the error from npm (and not related to stylelint). You can hide it with:

```
"./node_modules/.bin/stylelint \"src/**/*.css\" ||  true"
```

If this doesn't resolve your issue, please can you create a repo with a reproducible test case?

**Comment by hudochenkov** [comment] 2017-01-21 12:03
Same here. Can't reproduce.

**Comment by jeddy3** [comment] 2017-01-21 12:33
Closing. 

@ArthurClemens Feel free to continue posting to this issue if you're able to produce a repo with a reproducible test case.

**Closed by jeddy3** 2017-01-21 12:33 UTC
Labels: status: needs investigation

**Comment by ArthurClemens** [comment] 2017-01-21 12:38
I'm sorry for the trouble, I must have overlooked something.
