### ISSUE TITLE
Multiple --fix runs needed to get final result

### ISSUE THREAD

**Issue by ThiefMaster** [stylelint/stylelint#4777] opened 2020-05-15 14:50 UTC
> Clearly describe the bug

When using certain rule combinations, I need to run `stylelint --fix` multiple times to get the correct result.

> Which rule, if any, is the bug related to?

`scss/at-mixin-argumentless-call-parentheses` and `prettier/prettier`

Likely others as well.

> What code is needed to reproduce the bug?

```scss
.foo {
  @include my-mixin;
}
```

> What stylelint configuration is needed to reproduce the bug?

```yaml
extends:
  - stylelint-prettier/recommended

plugins:
  - stylelint-scss

rules:
  scss/at-mixin-argumentless-call-parentheses: always
```

> Which version of stylelint are you using?

- `stylelint@13.3.3`
- `stylelint-scss@3.17.2`
- `stylelint-prettier@1.1.2`

> How are you running stylelint: CLI, PostCSS plugin, Node.js API?

Happens in the CLI and the vscode integration

> Does the bug relate to non-standard syntax (e.g. SCSS, Less etc.)?

SCSS

> What did you expect to happen?

A single `--fix` run solving all problems. AFAIK `eslint`'s behavior is to repeat applying fixers until nothing gets changed anymore.

> What actually happened (e.g. what warnings or errors did you get)?

The first `--fix` rule fixed a problem but added another, that required a second run to be fixed.

```shell
[adrian@blackhole:/tmp/stylelint-bug]> cat demo.scss
.foo {
  @include my-mixin;
}
[adrian@blackhole:/tmp/stylelint-bug]> npx stylelint demo.scss

demo.scss
 2:3  ✖  Expected parentheses in mixin "my-mixin" call   scss/at-mixin-argumentless-call-parentheses

[adrian@blackhole:/tmp/stylelint-bug]> npx stylelint --fix demo.scss
[adrian@blackhole:/tmp/stylelint-bug]> cat demo.scss
.foo {
  @include my-mixin ();
}
[adrian@blackhole:/tmp/stylelint-bug]> npx stylelint demo.scss

demo.scss
 2:20  ✖  Delete "·"   prettier/prettier

[adrian@blackhole:/tmp/stylelint-bug]> npx stylelint --fix demo.scss
[adrian@blackhole:/tmp/stylelint-bug]> cat demo.scss
.foo {
  @include my-mixin();
}
[adrian@blackhole:/tmp/stylelint-bug]> npx stylelint demo.scss
```

**Comment by jeddy3** [comment] 2020-05-17 09:39
@ThiefMaster Thanks for the clearly written report and for using the template.

I'm going to close as a duplicate of https://github.com/stylelint/stylelint/issues/3853. That issue is labelled as "ready to implement" and is looking for someone to champion it.

> AFAIK eslint's behavior is to repeat applying fixers until nothing gets changed anymore.

Yes, I think that's the approach we'll have to take to.

**Closed by jeddy3** 2020-05-17 09:39 UTC
