### ISSUE TITLE
stylelint not working with .gitignore

### ISSUE THREAD

**Issue by pavel06081991** [stylelint/stylelint#2511] opened 2017-04-18 15:41 UTC
I use "stylelint": "^7.10.1".

Here is content of my .gitignore file

```
.idea
node_modules
public
npm-debug.log*
ci
```

Then I run stylelint --ignore-path .gitignore **/*.css in the root folder of my project and get error:

```
Error: No configuration provided for D:\work\my_projects\react-starter\public\app.css
    at module.exports (D:\work\my_projects\react-starter\node_modules\stylelint\lib\utils\configurationError.js:8:27)
    at stylelint._fullExplorer.load.then.then.config (D:\work\my_projects\react-starter\node_modules\stylelint\lib\getConfigForFile.js:39:13)
```
Here is files structure:
```

react-starter/
	package.json
	public/
		app.css
		app.js
	src/
		.stylelintrc
        .gitignore
```

public folder is part of .gitignore file so why do I get error?

**Comment by evilebottnawi** [comment] 2017-04-18 15:42
@pavel06081991 `stylelint '{**/*,*}.css' --cache --ignore-path .gitignore`

**Comment by evilebottnawi** [comment] 2017-04-18 15:43
@pavel06081991 please, use template for issue in future

**Comment by pavel06081991** [comment] 2017-04-18 15:48
@evilebottnawi, I tried as you wrote but I get the same error again.

**Comment by evilebottnawi** [comment] 2017-04-18 15:50
@pavel06081991 `stylelint '{**/*,*}.css' --ignore-path .gitignore --config-base=src`?

**Comment by pavel06081991** [comment] 2017-04-18 15:52
@evilebottnawi, the same result, here is my npm script:

`"lint:css": "stylelint {**/*,*}.css --ignore-path .gitignore --config-base=src",`

and stylelint is installed locally(npm i stylelint -D)

**Comment by evilebottnawi** [comment] 2017-04-18 15:59
@pavel06081991 then formalize your problem to issue's template and for a more fast solution give a link to minimal repo reproduce

**Comment by pavel06081991** [comment] 2017-04-18 16:02
@evilebottnawi, okay, I'll prepare repo soon

**Comment by pavel06081991** [comment] 2017-04-18 16:10
@evilebottnawi, here is repo https://github.com/pavel06081991/stylelint-gitignore-issue
after cloning, copy file app.css from scr/ folder to public/ folder and then run npm run stylelint and you will get the error I described above. Thanks for your help.

**Comment by evilebottnawi** [comment] 2017-04-18 16:18
@pavel06081991 
1. Why linting `public` directory (you can have compressed code and have a lot of errors)?
2. All works as expected, if you want to use config for all nested files copy `.stylelintrc` to root directory, if you want use difference config for difference directories put in each directory own config. Also you can use  `stylelint` field in `package.json`, example `"stylelint": { "extends": ["stylelint-config-standard"]}"` for all files in project.

**Comment by pavel06081991** [comment] 2017-04-18 16:38
But anyway I can't understand why - - ignore-path with gitignore file does not ignore files in public folder? Eslint ignores if to set - - ignore-path to gitignore file

**Comment by evilebottnawi** [comment] 2017-04-18 17:36
@pavel06081991 What is not specifically ignored?

**Comment by evilebottnawi** [comment] 2017-04-18 17:37
@pavel06081991 https://github.com/stylelint/stylelint/issues/2511#issue-222459356 (see on error), it is not related to .gitignore, `stylelint` just can't find your config, please read error message

**Comment by pavel06081991** [comment] 2017-04-18 21:21
@evilebottnawi, yes, I understand, but I can't understand why I have to provide any configuration file for css files which must be ignored because of --ignore-path .gitignore? It looks like a bug of stylelint. Files which are listed in --ignore-path .gitignore must be excluded from linting at all.

**Comment by evilebottnawi** [comment] 2017-04-19 08:13
@pavel06081991 It's hard for me to understand what kind of mistake you're talking about, everything works as expected, I have a feeling that you do not quite understand architector of your apps. `.gitignore` it is just file that contain all paths which be ignoring, example i have glob `**/*.css` (all `css` files in my apps), my `.gitignore` contain `public`, it is mean all `css` files will be ignore in `public` directory, but files in `src` will be linting. `eslint` works similarly. 

You error contain notice about `stylelint` don't find you config and it is right, because you run `stylelint` use `npm run stylelint` where `process.cwd()` is root directory of your app and `stylelint` try to search config in root directory (and in field in package.json), but config don't exist and your got error.

Btw, basic configuration for `eslint`, `stylelint`, `babel`, `postcss`, `editorconfig` and etc, usually stored in root directory (or in fields into `package.json`), see https://github.com/davezuko/react-redux-starter-kit as example. Also your can read great manual https://github.com/verekia/js-stack-from-scratch

**Comment by pavel06081991** [comment] 2017-04-19 13:42
@evilebottnawi, now I understood. As for eslint it does not look for config file in the process.cwd(), here is how it works:

> The second way to use configuration files is via .eslintrc.* and package.json files. ESLint will automatically look for them in the directory of the file to be linted, and in successive parent directories all the way up to the root directory of the filesystem.

That is why I could not undertsand. Stylelint uses another way to find config file.

**Comment by evilebottnawi** [comment] 2017-04-19 13:50
@pavel06081991 https://github.com/stylelint/stylelint/blob/master/docs/user-guide/configuration.md
`eslint` by default use `recommended` config, `stylelint` nothing

/cc @davidtheclark @jeddy3 what do your think use `recommended` config if no config found?

**Comment by davidtheclark** [comment] 2017-04-19 13:59
> ESLint will automatically look for them in the directory of the file to be linted, and in successive parent directories all the way up to the root directory of the filesystem.

stylelint does the same thing: looks for file-specific configs by successive parent directories.

Let me try to articulate the problem I see here:

Given this structure:
- public/
  - a.css
- src/
  - .stylelintc
  - b.css
- .gitignore

And `.gitignore` ignores `public`.

We run `stylelint --ignore-path .gitignore **/*.css`. And we get this error: `Error: No configuration provided for /path/to/public/a.css`.

That is correct: there is no configuration for that file. If you exclude `public/` *from your glob*, it will not be linted (e.g. `"**/*.css, !public/**"`). After #2464 is merged and released, the ignore file will be equivalent to excluding the file from your glob — so after that release, @pavel06081991, this code should work as expected for you.

> /cc @davidtheclark @jeddy3 what do your think use recommended config if no config found?

Nope. I'd rather users deliberately pick their config.

**Closed by davidtheclark** 2017-04-19 13:59 UTC

**Comment by pavel06081991** [comment] 2017-04-19 14:06
@davidtheclark, thanks.
