### ISSUE TITLE
Cannot read property 'startsWith' of undefined

### ISSUE THREAD

**Issue by szepeviktor** [stylelint/stylelint#4771] opened 2020-05-14 13:44 UTC
With basic `stylelint-config-standard"` v13.3.3

```css
.u-show\@focus: active,
.u-show\@focus: focus {
    position: static !important;
    width: auto;
    height: auto;
    overflow: visible;
    clip: auto;
    white-space: normal;
    -webkit-clip-path: none;
    clip-path: none;
}
```

```
TypeError: Cannot read property 'startsWith' of undefined
    at test.css:1:1
    at module.exports (node_modules/stylelint/lib/utils/isStandardSyntaxSelector.js:18:15)
    at module.exports (node_modules/stylelint/lib/utils/isStandardSyntaxRule.js:17:7)
    at node_modules/stylelint/lib/rules/selector-pseudo-class-no-unknown/index.js:123:10
    at node_modules/stylelint/node_modules/postcss/lib/container.js:135:18
    at Root.each (node_modules/stylelint/node_modules/postcss/lib/container.js:101:16)
    at Root.walk (node_modules/stylelint/node_modules/postcss/lib/container.js:131:17)
    at node_modules/stylelint/lib/rules/selector-pseudo-class-no-unknown/index.js:119:8
    at node_modules/stylelint/lib/lintSource.js:214:8
    at Array.map (<anonymous>)
    at node_modules/stylelint/lib/lintSource.js:206:18
```

**Comment by szepeviktor** [comment] 2020-05-14 13:45
BTW I do not know what is `@focus`! I've found this CSS code in a client's project.

**Comment by jeddy3** [comment] 2020-05-14 16:12
I'm unable to reproduce the crashing `TypeError`.

Using the above CSS code with stylelint-config-standard gives me:

```
sources/css/escaped.css
 1:1  ✖  Cannot parse selector   parseError
```

Which is correct as the selector is unparseable. 

> BTW I do not know what is `@focus`!

I don't know what it is, but it is valid selector syntax because the `@` is escaped. You can test it using [the CSSTree validator)[https://csstree.github.io/docs/validator.html]. The spaces after the colons are not valid, though, which is why stylelint reports it as a `parseError`.

I'll close the issue as the `TypeError` is not reproducible using the example provided. However, you're welcome to create a new issue [using the bug template](https://github.com/stylelint/stylelint/issues/new?template=REPORT_A_BUG.md) with a reproducible example.

**Closed by jeddy3** 2020-05-14 16:12 UTC

**Comment by szepeviktor** [comment] 2020-05-15 03:57
Thank you.
After proper installation I also get `parseError`.

Sorry for the noise.
