### ISSUE TITLE
Fix invalid option regression on Windows 10

### ISSUE THREAD

**Issue by bmpeg** [stylelint/stylelint#5042] opened 2020-11-18 09:56 UTC
Hi, I get the following error in my project. i am using vuetify. 

package.json
"lint:js": "eslint --fix --ext .js,.vue --ignore-path .gitignore .",
"lint:style": "stylelint **/*.{vue,css} --ignore-path .gitignore",
"lint": "npm run lint:js && npm run lint:style --fix"

run npm run lint

Invalid option "--allow-emptyinput". Did you mean "--allow-empty-input"?
Invalid option "--disable-defaultignores". Did you mean "--disable-default-ignores"?
Invalid option "--reportinvalid-scope-disables". Did you mean "--report-invalid-scope-disables"?

why could it be? Thanks.

**Comment by jeddy3** [comment] 2020-11-18 10:22
Try quoting your glob, e.g.

```
"lint:style": "stylelint \"**/*.{vue,css}\" --ignore-path .gitignore",
```

If that doesn't work, please create a new issue using the template and link to a reproducible repo.

**Comment by bmpeg** [comment] 2020-11-18 10:56
OS: Win 10
I am using visual studio code
Nuxtjs project and vuetify

I am run > npx stylelint --help

Invalid option "--allow-emptyinput". Did you mean "--allow-empty-input"?
Invalid option "--disable-defaultignores". Did you mean "--disable-default-ignores"?
Invalid option "--reportinvalid-scope-disables". Did you mean "--report-invalid-scope-disables"?

I guess it's been running the following codes respectively;
npm install --save-dev node-sass sass-loader 
npm uninstall --save-dev node-sass sass-loader

**Comment by bmpeg** [comment] 2020-11-18 10:58
I also stick with the same problem when I create a new nuxt project. 

There may be a problem with the computer. How can I repair the stylelint?

**Comment by jeddy3** [comment] 2020-11-18 10:58
Can you run `npx stylelint` outside of any nuxt project folders, please? And then paste the complete output here.

**Comment by bmpeg** [comment] 2020-11-18 11:02
![image](https://user-images.githubusercontent.com/45894806/99522407-a5ecc680-29a6-11eb-96f6-4636e21ebc13.png)

**Comment by jeddy3** [comment] 2020-11-18 11:11
Thank you. There looks to be a regression on Windows with `13.8.0`.

Do any contributors have access to a Windows 10 machine to try to reproduce this?

**Comment by hudochenkov** [comment] 2020-11-18 11:15
I just checked on Windows 10 machine. I don't have such regression. Running `npx stylelint` and `npx stylelint --version` works as expected. And I don't have any globally installed npm packages there.

**Comment by bmpeg** [comment] 2020-11-18 11:18
I use the following packages

"devDependencies": {
    "@nuxtjs/eslint-config": "^3.1.0",
    "@nuxtjs/eslint-module": "^2.0.0",
    "@nuxtjs/stylelint-module": "^4.0.0",
    "@nuxtjs/vuetify": "^1.11.2",
    "babel-eslint": "^10.1.0",
    "eslint": "^7.5.0",
    "eslint-config-prettier": "^6.11.0",
    "eslint-plugin-nuxt": "^1.0.0",
    "eslint-plugin-prettier": "^3.1.4",
    "husky": "^4.2.5",
    "lint-staged": "^10.2.11",
    "prettier": "^2.0.5",
    "stylelint": "^13.6.1",
    "stylelint-config-prettier": "^8.0.2",
    "stylelint-config-standard": "^20.0.0"
  }

**Comment by bmpeg** [comment] 2020-11-18 11:19
It happened after running the following codes respectively and it didn't work again.
npm install --save-dev node-sass sass-loader
npm uninstall --save-dev node-sass sass-loader

**Comment by jeddy3** [comment] 2020-11-18 11:28
> I just checked on Windows 10 machine. I don't have such regression.

Phew, that's good to know as it doesn't appear to be a broad regression then.

@bmpeg I suggest:

1. using the trash can icon to close your current terminal window in VSCode
2. start a new terminal window in VSCode
3. delete your `node_modules` folder

See if that helps.

**Comment by bmpeg** [comment] 2020-11-18 11:32
I have tried them all. The problem persists.

**Comment by jeddy3** [comment] 2020-11-18 11:37
I'm out of ideas. Anyone else?

**Comment by XhmikosR** [comment] 2020-11-18 12:33
Windows and v13.8.0 is fine on my side too :)

**Comment by bilalmalkoc** [comment] 2020-11-28 15:51
Same here. Anyone find fix?

**Comment by shichaz** [comment] 2020-12-11 23:43
The problem persists.

**Comment by bmpeg** [comment] 2020-12-12 06:26
I solved the problem. I noticed it was because of the corruption in the  package-lock.json file. I reverted to the previous version, the problem was fixed. Thanks.

**Comment by bilalmalkoc** [comment] 2020-12-12 06:48
@bmpeg problem was happened on fresh install.

**Comment by samirmhsnv** [comment] 2021-01-15 18:32
any fast fix ?

**Comment by tarikcaliskan** [comment] 2021-01-30 19:37
The problem still exists. Any updates?

**Comment by metecan** [comment] 2021-01-30 19:48
I have this problem either. But it just happened on Windows 10. I tried on WSL Ubuntu 20.04, and there is no problem. The problem is about Windows.

**Comment by bilalmalkoc** [comment] 2021-02-01 08:54
@metecan Thanks. It works :) (Teşekkürler kardeş).

**Comment by metecan** [comment] 2021-02-01 10:32
@bilalmalkoc 
> @metecan Thanks. It works :) (Teşekkürler kardeş).

You're welcome! ( Rica ederim )

**Comment by yoktav** [comment] 2021-02-20 20:00
Problem still exist for windows terminal

**Comment by borablanca** [comment] 2021-03-03 15:44
I am having the same problem on windows 10 terminal.

**Comment by selimdoyranli** [comment] 2021-03-11 07:13
+1

**Comment by sinankeskin** [comment] 2021-04-16 10:05
Issue still there. Thank you.

**Comment by sinankeskin** [comment] 2021-04-16 19:51
I've created a PR in https://github.com/yargs/yargs-parser/pull/374

This will fix this issue.

Thanks.

**Comment by furcan** [comment] 2021-05-10 02:52
Same here. 

Changing the Regional Format from X(x => Turkish for me) to English is solving this issue **temporarily**. 

FYI.

![Untitled](https://user-images.githubusercontent.com/49978011/117599710-105f1200-b153-11eb-8bae-602cb7c2d8bb.png)

**Comment by Mouvedia** [comment] 2023-02-04 16:16
meow has https://github.com/yargs/yargs-parser/pull/374 since https://github.com/sindresorhus/meow/blob/829aab091db54dad0fa9aebe3918b616d81e950f/package.json#L56
which landed in version 10.1.0 but we are using version 9.0.0.

Hence if we upgrade meow to latest or 10.1.0 at the minimum it should fix it.

**Comment by ybiquitous** [comment] 2023-06-27 13:28
@Mouvedia Thanks for sharing the info.

meow has been a pure ESM since [v10.0.0](https://github.com/sindresorhus/meow/releases/tag/v10.0.0), so Stylelint must be a pure ESM to update meow.

However, we're discussing whether Stylelint 16.0.0 becomes a pure ESM or not. Please see <https://github.com/stylelint/stylelint/issues/5291#issuecomment-1604274293>.

**Comment by romainmenke** [comment] 2023-07-04 16:37
> so Stylelint must be a pure ESM to update meow.

`meow` is only a dependency of the CLI and the `lib/cli.js` should not be called from a script, it should be executed directly through `.bin/stylelint.js`.

I don't think it is a user facing change to make only the CLI purely ESM.
So it might even be possible to make changes here in `15.x`.

**Closed** 2023-07-05 13:27 UTC
Labels: status: ready to implement, type: bug
