### ISSUE TITLE
Fix deletion of code with --fix option

### ISSUE THREAD

**Issue by harapeko** [stylelint/stylelint#3514] opened 2018-08-06 06:38 UTC
I tried the minimum configuration.

package.json

```json
{
  "dependencies": {
    "stylelint": "^9.4.0"
  }
}
```

.stylelintrc

```json
{
  "rules": {
  }
}
```

# ex1
app.sass

```sass
.ToggleSwitch
  @extend .hoge
```

CLI with `yarn run stylelint app.sass --fix`
~~`yarn run stylelint app.sass`~~

Unexpected changes will be made

```sass
```

# ex2
app.sass

```sass
.ToggleSwitch
  @extend .hoge
  @include .fuga
  padding: 0 $width
  border: 1px solid $border-color
```

CLI with `yarn run stylelint app.sass --fix`
~~`yarn run stylelint app.sass`~~

Unexpected changes will be made

```sass
.ToggleSwitch
  
    padding: 0 $width
  border: 1px solid border-color
```

thx

**Comment by hudochenkov** [comment] 2018-08-06 08:34
What is your `stylelint` script in package.json?

**Comment by MeisterTea** [comment] 2018-11-22 16:22
Using stylelint 9.8.0, I can't reproduce your issue, can you close it if it's fixed ?

**Comment by jeddy3** [comment] 2018-11-22 17:03
@MeisterTea Thanks for trying to reproduce the issue with the latest version of stylelint. I suspect it was fixed as a side-effect of updating to the latest postcss-sass parser in https://github.com/stylelint/stylelint/pull/3772. I'll close the issue.

**Comment by harapeko** [comment] 2018-11-26 04:21
@MeisterTea @jeddy3 

sorry!!
The `--fix` option was missing in my command.
I prepared a reproduction repository

https://github.com/harapeko/stylelint-fix-option-reproduce

**Comment by renanpvaz** [comment] 2019-04-01 18:34
I'm having the same issue when using sass + fix option.

Here are some more examples that might be helpful:

```diff
- @import '../settings/variables'
```
```diff
- background: url("https://s3.amazonaws.com/cool-url/icon.svg")
+ background: "https://s3.amazonaws.com/cool-url/icon.svg"
```
this won't even break because navy is a preset color lol
```diff
- color: $navy
+ color: navy 
```

```diff
- @font-face
-  font-family: 'Gotham'
-  src: ...
-  font-style: italic
-  font-weight: 300
```

**Comment by speed-of-light** [comment] 2019-12-03 15:43
same here, `@import @extend` will be removed after run with `--fix` and no error has been shown without `--fix` so I can't even disable the rules for removing them.

I am linting with `sass`

**Comment by TheYoxy** [comment] 2020-02-12 11:25
Same issues with vue and sass. 
I get no errors when I lint the code but here are 2 samples of code that are removed:

```vue
<style lang="sass">
// This keyframe is removed
@keyframes appear
  0%
    opacity: 0
  100%
    opacity: 1

.Logo
  animation: 2.5s appear
</style>
```

```vue
<style lang="sass">
// All theses imports are removed
@import "@/assets/scss/bt-custom-vars.scss"
@import "@/assets/scss/bt-custom.scss"
@import "~bootstrap/scss/bootstrap.scss"
@import "~bootstrap-vue/src/index.scss"
@import "@/assets/scss/font-size.scss"
@import "@/assets/scss/main.scss"
...
</style>
```

**Comment by Upd4ting** [comment] 2020-02-12 11:36
Any workaround?

**Comment by jeddy3** [comment] 2020-02-15 16:47
This issue is likely due to to a problem in [`postcss-sass`](), which [stylelint uses](https://stylelint.io/about/syntaxes):

> We lean on [PostCSS syntaxes](https://github.com/postcss/postcss#syntaxes) to help us with this task \[of supporting non-standard syntaxes\] . We use them to transform these languages into something that resembles CSS

Please consider [contributing a fix upstream](https://stylelint.io/developer-guide/syntaxes) to resolve this issue.

I'll add an "upstream" label to indicate this.

> Any workaround?

We [added a feature in 13.2.0](https://stylelint.io/changelog#1320) to [workaround](https://stylelint.io/developer-guide/syntaxes#workarounds) these types of upstream parser issues:

> Fixing bugs in syntaxes can take time. stylelint can work around these bug by turning off autofix for incompatible sources. Autofix can then remain safe to use while contributors try to fix the underlying issue.

If you're unable to contribute to the upstream parser, please consider [contributing a workaround to stylelint itself](https://stylelint.io/developer-guide/syntaxes#add-a-workaround) so that autofix becomes safer to use with sass syntax.

**Comment by jeddy3** [comment] 2022-01-17 14:21
Closing as related to custom syntax.

**Closed by jeddy3** 2022-01-17 14:21 UTC
Labels: status: ready to implement, type: bug, syntax: sass, upstream
