### ISSUE TITLE
how to disable rule-properties-order?

### ISSUE THREAD

**Issue by jonathanong** [stylelint/stylelint#615] opened 2016-01-10 23:32 UTC
trying to add stylelint without touching the CSS yet. i'm trying to disable it, but I don't get the options.

Setting `"rule-properties-order": false` yields:

```
Invalid option value "false" for rule "rule-properties-order"
```

Setting `"rule-properties-order": 0` yields: 

```
>> Deprecation Warning: Numbered severities (0, 1, 2) have been deprecated, and in 4.0 they will be disabled.  See: http://stylelint.io/?/docs/user-guide/configuration.md
```

what am i supposed to do other than fix all my css?

**Comment by jonathanong** [comment] 2016-01-10 23:36
o i c. i have to set it to `null`. that's super weird. can we allow setting it to `false`?

**Comment by davidtheclark** [comment] 2016-01-11 00:15
We designated `null` for this purpose because it's more conceivable that a rule could take `false` as a primary option. I suppose we could negate that possibility and allow both `null` and `false` to turn rules off; but I don't think that's really necessary. Anybody else have opinions?

Since this is already documented, not a bug, I'll close the issue.

**Closed by davidtheclark** 2016-01-11 00:15 UTC

**Comment by jeddy3** [comment] 2016-01-11 07:13
> Anybody else have opinions?

Nope, you summed up our reasoning well.
