### ISSUE TITLE
selector-descendant-combinator-no-non-space lags in Atom plugin

### ISSUE THREAD

**Issue by octoxan** [stylelint/stylelint#1873] opened 2016-08-30 16:41 UTC
> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

A bug where Atom lags like mad while selector-descendant-combinator-no-non-space is not set to null.

> Which rule, if any, is this issue related to?

selector-descendant-combinator-no-non-space

> What CSS is needed to reproduce this issue?

The rule files on every keypress until a {, so the following would all throw the error and lag like crazy.

```css
.f
.fo
.foo
```

> What stylelint configuration is needed to reproduce this issue?

```json
{
  "rules": {
    "declaration-colon-space-after": "always",
    "indentation": ["tab"],
    "max-empty-lines": 2,
	"color-hex-case": "lower",
    "color-hex-length": "short",
	"number-leading-zero": "never",
	"comment-empty-line-before": null,
	"at-rule-empty-line-before": null,
	"selector-pseudo-element-colon-notation": "single",
	"no-eol-whitespace": true,
	"selector-list-comma-newline-after": "always",
	"at-rule-no-unknown": null,
	"rule-nested-empty-line-before": null,
	"declaration-colon-newline-after": null,
	"declaration-block-no-ignored-properties": null,
	"declaration-empty-line-before": null,
	"selector-descendant-combinator-no-non-space": null,
	"declaration-block-no-duplicate-properties": [
		true,
		{
			ignore: [
			"consecutive-duplicates-with-different-values"
			]
		}
	],
	"declaration-block-properties-order":
		[
		  {
		    properties: [
		      "position",
			  "top",
			  "right",
			  "bottom",
			  "left",
		      "z-index"
		    ],
		  },
		  {
		    properties: [
		      "float",
			  "clear",
		    ],
		  },
		  {
		    properties: [
		      "display",
		      "box-sizing",
			  "overflow",
			  "width",
			  "min-width",
			  "max-width",
			  "height",
			  "min-height",
			  "max-height"
		    ],
		  },
		  {
		    properties: [
		      "margin",
		      "margin-top",
			  "margin-right",
			  "margin-bottom",
			  "margin-left"
		    ],
		  },
		  {
		    properties: [
		      "padding",
		      "padding-top",
			  "padding-right",
			  "padding-bottom",
			  "padding-left"
		    ],
		  },
		  {
		    properties: [
		      "border",
			  "border-top",
			  "border-right",
			  "border-bottom",
			  "border-left",
			  "border-width",
			  "border-style",
			  "border-color",
			  "outline"
		    ],
		  },
		  {
		  	order: "flexible",
		    properties: [
		      "font-size",
		      "font-weight",
			  "font-style",
			  "font-family",
			  "line-height"
		    ],
		  },
		  {
		  	order: "flexible",
		    properties: [
		      "text-align",
			  "text-transform",
			  "text-decoration",
			  "text-indent"
		    ],
		  },
		  {
		  	order: "flexible",
		    properties: [
		      "color",
		      "background",
			  "background-color",
			  "background-image",
			  "background-size"
		    ],
		  }
		]
	}
}
```

> Which version of stylelint are you using?

7.2.0

> How are you running stylelint: CLI, PostCSS plugin, Node API?

Atom plugin

> Does your issue relate to non-standard syntax (e.g. SCSS, nesting, etc.)?

No

> What did you expect to happen?

The editor to not lag like crazy.

> What actually happened (e.g. what warnings or errors you are getting)?

The editor lags like crazy (and no other rules ever did this, computer is normally blazing fast)

**Comment by Arcanemagus** [comment] 2016-08-30 16:59
Just as an FYI, I'm unable to reproduce this, when typing the above all I get is a "Unknown word (CSSSyntaxError)" message.

**Comment by evilebottnawi** [comment] 2016-08-30 17:05
@octoxan atom plugin give setup delay?

**Comment by Arcanemagus** [comment] 2016-08-30 17:09
@evilebottnawi Only the first lint run should have a delay (as it is loading `stylelint` for the first time then), all subsequent calls should be just the lint time.

**Comment by evilebottnawi** [comment] 2016-08-30 17:12
@Arcanemagus maybe add option to `delay`, i am not use `atom`, use `ItelliJ Idea`, here all linters have some delay.

**Comment by Arcanemagus** [comment] 2016-08-30 17:17
@evilebottnawi I'm not sure what you mean... do you mean delay between typing and running the linter? That's handled in the `linter` package, and isn't really relevant to this issue as @octoxan is saying it runs fine if `selector-descendant-combinator-no-non-space` is disabled, but lags horribly if it is enabled.

**Comment by octoxan** [comment] 2016-08-30 17:35
Actually... it seems to only lag in some of my projects but not in others. Same exact stylelintrc file and same exact settings. Both in an scss file...

**Comment by evilebottnawi** [comment] 2016-08-30 17:39
@octoxan can you create testing repo?

**Comment by Arcanemagus** [comment] 2016-08-30 18:55
Just pushed out v3.2.1 of the Atom plugin, it adds timing instrumentation!

If you launch Atom from a terminal with the `--dev` option, then it will show exactly how long `stylelint` took to run, see https://github.com/AtomLinter/linter-stylelint/pull/259 for an example.

Hopefully that helps in tracking this down 😉.

**Comment by evilebottnawi** [comment] 2016-08-30 19:04
@Arcanemagus As I understand it is a long time(in second? each run takes so long)? it is related only to this rule?

**Comment by Arcanemagus** [comment] 2016-08-30 19:25
No, that's in ms and the "Stylelint" time is the time it takes to call `stylelint.lint(options)`.

**Comment by evilebottnawi** [comment] 2016-08-30 19:28
@Arcanemagus thanks for helping

**Comment by davidtheclark** [comment] 2016-09-07 23:45
Should this be closed as it's not an issue with stylelint? Or *is* it?

If we want to keep this open, let's get some benchmarks for that rule and see if we can improve the speed.

**Comment by jeddy3** [comment] 2016-09-18 16:02
> As I said earlier I can't reproduce this as the given code just results in a CSSSyntaxError for me.

Ditto.

**Closed by jeddy3** 2016-09-18 16:02 UTC
Labels: status: discussion, type: ecosystem
