### ISSUE TITLE
Suggestion for package path lookup

### ISSUE THREAD

**Issue by gucong3000** [stylelint/stylelint#1935] opened 2016-09-28 02:19 UTC
> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

new feature

> What stylelint configuration is needed to reproduce this issue?

```json
{
  "extends": ["stylelint-config-standard"],
  "plugins": ["stylelint-selector-bem-pattern"],
  "processors": ["stylelint-html-processor"]
}
```

my file list
```
/path-to-my-proj-a/test.css
/path-to-my-proj-a/.stylelintrc.json
/path-to-my-proj-b/test.css
/path-to-my-proj-b/.stylelintrc.json
/path-to-my-proj-b/.stylelintrc.json

/path-to-my-build-tool/lint.js
/path-to-my-build-tool/node_modules/...
```

```bash
cd /path-to-my-build-tool/
node lint.js --all
```

> Which version of stylelint are you using?

next

> How are you running stylelint: CLI, PostCSS plugin, Node API?

Node API

> Does your issue relate to non-standard syntax (e.g. SCSS, nesting, etc.)?

No

> What did you expect to happen?

When extend or plugin name is a NPM package ID, not a relative path, and no longer find it the project path, we should try to find from the process current directory.

> What actually happened (e.g. what warnings or errors you are getting)?

`Could not find "${lookup}". Do you need a \`configBasedir\`?`

**Comment by gucong3000** [comment] 2016-09-28 02:24
#1930 
if extend or plugin name is NPM package ID, we should not only try file path of source.

**Comment by davidtheclark** [comment] 2016-09-29 14:20
Duplicate of #1810. Let's continue the conversation over there.

**Closed by davidtheclark** 2016-09-29 14:20 UTC
Labels: status: discussion
