### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by rcerljenko** [stylelint/stylelint#6898] opened 2023-06-05 05:49 UTC
### What steps are needed to reproduce the bug?

Just install latest version.

### What Stylelint configuration is needed to reproduce the bug?

NA

### How did you run Stylelint?

```sh
stylelint --cache <path>
```

### Which version of Stylelint or dependencies are you using?

15.6.3

### What did you expect to happen?

Run without errors.

### What actually happened?

It crashes with this exception: `Segmentation fault (core dumped)`

### Does the bug relate to non-standard syntax?

No

**Comment by younky-yang** [comment] 2023-06-05 05:57
same issue happens when I updated to the latest version of 15.6.3.

**Comment by ybiquitous** [comment] 2023-06-05 06:06
@rcerljenko Thanks for the report. I doubt this is a problem of Cosmiconfig:

- https://github.com/stylelint/stylelint/pull/6893
- https://github.com/cosmiconfig/cosmiconfig/issues/307

Can you confirm a workaround to downgrade Cosmiconfig to [8.1.3](https://github.com/cosmiconfig/cosmiconfig/releases/tag/v8.1.3)?

**Comment by jlherren** [comment] 2023-06-05 06:38
Downgrading to cosmiconfig 8.1.3 did solve the issue for me.

**Comment by yogarasu** [comment] 2023-06-05 06:57
> 最新バージョン 15.6.3 に更新したときにも同じ問題が発生します。

Me too.

**Comment by tjx666** [comment] 2023-06-05 09:56
I also occur this problem:

![lQLPJx-0LdicJQLMrM0E1LCs79agXXVZTAR0XIPlwBIA_1236_172](https://github.com/stylelint/stylelint/assets/41773861/167df28b-bde5-4c38-8883-6ce5d374656b)

"stylelint": "^15.6.3"

This issue not reproduce every time, sometimes it disappear

**Comment by tjx666** [comment] 2023-06-05 12:08
I can confirmed lock "cosmiconfig": "8.1.3" works

**Comment by d-fischer** [comment] 2023-06-05 17:52
Hi, `cosmiconfig` maintainer here.

For some reason, within `stylelint`, any call to `import()` crashes. Do you have any idea why that could be? In general, even though stylelint is written in CJS. it shouldn't have any problems calling dynamic `import()`...

**Comment by romainmenke** [comment] 2023-06-05 18:18
This seems relevant : https://github.com/stylelint/stylelint/blob/main/bin/stylelint.js#L6

If I remove that the issue goes away.

**Comment by alexander-akait** [comment] 2023-06-05 18:25
Oh, yes `v8-compile-cache` and dynamic imports broken

**Comment by alexander-akait** [comment] 2023-06-05 18:26
It is an old problem https://github.com/zertosh/v8-compile-cache/issues/30

**Comment by alexander-akait** [comment] 2023-06-05 18:27
There is no good solution, because `vm` is for ESM is stim experimantal and still have a problems with dynamic imports and memory leaking, so there is only one solution, remove `v8-compile-cache` usage

**Comment by romainmenke** [comment] 2023-06-05 20:53
This still fails.

Is it possible that `jest` also isn't compatible?

**Comment by alexander-akait** [comment] 2023-06-05 21:02
Yeah, there is https://github.com/nodejs/node/issues/35889 and https://github.com/nodejs/node/issues/35889#issuecomment-949639126, ESM is still not stable as we want :disappointed:

**Comment by romainmenke** [comment] 2023-06-05 21:17
Given that the issue doesn't seem trivial to resolve I think it might be best to first help those users who are affected by this.

@d-fischer Would you consider doing a rollback of the changes in `8.2` as they seem to be breaking? A `semver` major would be less disruptive for a feature addition like this as users of Stylelint wouldn't get that next major unless a change is also made here first.

If that is not possible I think we should release a version of Stylelint with `cosmiconfig` pinned to `8.1.3`. This will takes the pressure of and ensure that there is only a limited proliferation of `"overrides": { "stylelint": { "cosmiconfig": "8.1.3" } }`.

When the issues are resolved we can unpin the version and users won't have to take manual actual.

@alexander-akait @ybiquitous thoughts?

**Comment by alexander-akait** [comment] 2023-06-05 21:36
@d-fischer I'll tell you a secret - `vitest` has the same problem, because leaking and broken cache in v8

**Comment by d-fischer** [comment] 2023-06-05 21:41
> @romainmenke
> 
> yeah, it is the best solution right now - pin it and open an issue (or rename this) and do a patch release

The removal of `v8-compiler-cache` would still be required, I think. I'm updating #6901 with the pin.

**Comment by d-fischer** [comment] 2023-06-05 21:41
> @d-fischer I'll tell you a secret - `vitest` has the same problem, because leaking and broken dynamic import cache in v8, not in node.js or jest

Switching from `jest` to `vitest` fixed the problems of `cosmiconfig`'s test suite with dynamic imports, that's all I can say.

**Comment by romainmenke** [comment] 2023-06-05 21:47
> Switching from jest to vitest fixed the problems of cosmiconfig's test suite with dynamic imports, that's all I can say.

My concern with that is that it might be passing the issue to users of Stylelint.
I don't want to fix this in a way that just makes the CI green here but failing for others.

Ideally the issues stop here :)

**Comment by ybiquitous** [comment] 2023-06-05 21:55
Thanks for the help, everyone.

For now, I agree with doing a patch release, pinning `cosmiconfig`. 👍🏼 
I'll prepare for the release right now.

**Comment by romainmenke** [comment] 2023-06-05 21:57
@d-fischer Is there any reason not to use the `sync` loaders?

https://github.com/stylelint/stylelint/pull/6902

I noticed that we use the async API and that only the async API has the new `esm` loader.

https://github.com/cosmiconfig/cosmiconfig/blob/889d3b491b54babf4d816a10a6c6720df5ccd944/src/loaders.ts#L8-L15

**Comment by d-fischer** [comment] 2023-06-05 21:59
> My concern with that is that it might be passing the issue to users of Stylelint.

So how likely do you think it is that people will invoke `stylelint` as part of their test suite?

The new ESM loader of cosmiconfig is pretty much exactly what `prettier` has been shipping for a while, plus an additional try-catch (which doesn't catch this error because it's a segfault, sadly). I have not tested it yet, but it should be pretty much the exact same situation, but `prettier` didn't ever get a report about that.

To be honest, I don't have any clue how to fix this problem without just getting rid of ESM loading again.

**Comment by d-fischer** [comment] 2023-06-05 22:05
> @d-fischer Is there any reason not to use the `sync` loaders?

Should be fine; as `cosmiconfig` uses `await`, a non-promise result should be handled just fine. The only (obscure) breakage I could imagine would be a file that includes a `then` property at the root level, which might just crash with an obscure error. If you want to be extra sure about that corner case, I guess you could do something like
```js
'.js': (path, content) => Promise.resolve(defaultLoadersSync['.js'](path, content)),
```

**Comment by ybiquitous** [comment] 2023-06-05 22:09
Thanks for the quick fix #6902.

To confirm, if people try using `.stylelintrc.mjs` (ESM`), can #6902 prevent this problem?

**Comment by d-fischer** [comment] 2023-06-05 22:10
> To confirm, if people try using `.stylelintrc.mjs` (ESM), can #6902 prevent this problem?

I guess you would still have to remove that weird cache package for that to work.

**Comment by romainmenke** [comment] 2023-06-05 22:11
> To confirm, if people try using .stylelintrc.mjs (ESM), can https://github.com/stylelint/stylelint/pull/6902 prevent this problem?

No, or at least not intentionally.

I am unsure what the behavior was before when people tried to use `.stylelintrc.mjs`.

Is this something that was supported and should be tested?
Is this something that wasn't supported and should be handled by a nice error message?

**Comment by ybiquitous** [comment] 2023-06-05 22:17
Currently, I don't think we should support `.mjs` explicitly. See also below (CLI help and doc):

https://github.com/stylelint/stylelint/blob/f1ace6167d1145f875050452f17b3e11494fac05/lib/cli.js#L115-L118

https://github.com/stylelint/stylelint/blob/f1ace6167d1145f875050452f17b3e11494fac05/docs/user-guide/configure.md?plain=1#L5-L8

But, we note that some people may try using `.mjs` if Cosmiconfig 8.2 is installed. Let's consider it later, though.

**Comment by romainmenke** [comment] 2023-06-05 22:19
Yeah, should just work if we remove `v8-compiler-cache` as @d-fischer said and could be tested with a simpler separate script that doesn't rely on `jest` :)

**Comment by alexander-akait** [comment] 2023-06-05 22:20
Just infromation - we use this https://github.com/webpack-contrib/postcss-loader/blob/master/src/utils.js#L37 for js/mjs/cjs and eveyrhting works for a lot of developers

**Comment by alexander-akait** [comment] 2023-06-05 22:23
Shorty - many tools and bundlers handle `import(...)` and most of the time it's expected. BUT sometimes you don't want to do it, that is why you can use non analizable code like `new Function(...)`

**Comment by ybiquitous** [comment] 2023-06-05 22:25
I agree with removing `v8-compiler-cache` if there are no more concerns. 👍🏼

**Comment by ybiquitous** [comment] 2023-06-05 22:52
Great thanks, @romainmenke! I've merged #6902.

I'll do a patch release today. See also #6903.

**Comment by ybiquitous** [comment] 2023-06-05 23:40
https://github.com/stylelint/stylelint/releases/tag/15.7.0 is released! 🎉 
The segmentation fault should not occur. 👍🏼

**Comment by ybiquitous** [comment] 2023-06-06 00:01
I've opened follow-up issues:
- #6904
- #6905

So, I'm closing this issue since it's no longer needed. Feel free to comment if you still have any concerns.

Thank you so much for helping us resolve this problem!

**Closed by ybiquitous** 2023-06-06 00:01 UTC
Labels: status: needs investigation, priority: high, help wanted
