### ISSUE TITLE
Add "--force" option to exit with exit code 0 regardless of lint errors

### ISSUE THREAD

**Issue by cstenglein** [stylelint/stylelint#5436] opened 2021-08-07 07:56 UTC
> What is the problem you're trying to solve?

When running stylelint to generate reports (e.g. for Sonarqube) I want stylelint to exit with exit code 0 so the build process does not stop.

> What solution would you like to see?

A option "--force" in the CLI that exits regardless of lint errors.

**Comment by tomdaly** [comment] 2021-08-10 14:59
If your script allows, you can just run `stylelint <args>; exit 0` and it will always exit 0. This isn't really related to Stylelint.

**Comment by jeddy3** [comment] 2021-08-10 17:35
> If your script allows, you can just run `stylelint <args>; exit 0` and it will always exit 0. This isn't really related to Stylelint.

This is what we've recommended in the past.

**Comment by cstenglein** [comment] 2021-08-15 15:49
Thank you for the suggestion @tomdaly @jeddy3 ! :)

The `stylelint` command is triggered over a package.json script, so in our case

`yarn run stylelint; exit 0` doesn't work.

What works is adding `|| exit 0` to the `package.json` script.

That would mean we have to change all our project scripts.

If you don't like the force option, that's not a problem for us. If you want to build it in I made a PR #5437 ; otherwise you can close it.

**Comment by tomdaly** [comment] 2021-08-17 08:17
@cstenglein would you not have to change all of your project scripts anyway by adding `--force` if the PR was merged in?

I'm not sure I understand why `yarn run stylelint; exit 0` wouldn't work - are you using a CI process that involves listing bash commands? If you could post a snippet of the CI build steps then that would help solve the issue, as this seems like a bit of an [XY problem](https://en.wikipedia.org/wiki/XY_problem)

**Comment by ChristophRSG** [comment] 2021-08-25 07:25
Hi, @cstenglein's company account here.

In the `package.json` scripts of the respective projects, we got the following script:

`"stylelint": "stylelint src/**/*.{css,scss,sass} projects/**/*.{css,scss,sass}",`

In the build process, it will be triggered by calling `yarn stylelint` + extra parameters, like `-o` for a report.

That where we would put `--force`, so the process exits with 0 in the CI process - but reports the errors in Sonarqube with a report - & exits with an error on the local machine. 

We figured out a workaround thanks to your input and now the process will always exit with exit code 0, regardless of the child process outcome.  Thank you very much! 👍

We're not sure though if that should be the intended behaviour to "override" the exit code of another program instead of letting the program exit how it wants & providing an explicit option. If it is, then you can just close the issue & PR.

**Comment by jeddy3** [comment] 2021-08-31 13:39
@ChristophRSG Thanks for the extra information.

Let's close the issue and pull request for now. We can always revisit if the issue gets more thumbs up.

**Closed by jeddy3** 2021-08-31 13:39 UTC
Labels: status: needs discussion
