### ISSUE TITLE
Add contributors to release note

### ISSUE THREAD

**Issue by fpetrakov** [stylelint/stylelint#6297] opened 2022-08-22 18:10 UTC
Hi, I suggest adding 'Contributors' section to release note. I think this way more people will not only become but also stay as contributors to Stylelint. It's just a nice and a kind of warm feeling to see own nickname and profile picture in release note of the project. 

![image](https://user-images.githubusercontent.com/34133492/185988856-01d384cb-7fe0-4c9f-9d2a-156a585129d1.png)

**Comment by JounQin** [comment] 2022-08-22 23:16
It will be implemented in next iteration, we have some issues for inconsistent output for now, it will be fixed in next few days..

**Comment by JounQin** [comment] 2022-08-22 23:18
Besides, @jeddy3 @ybiquitous Shall we enable "discussions" for such questions instead of issues?

**Comment by ybiquitous** [comment] 2022-08-22 23:47
> It will be implemented in next iteration, we have some issues for inconsistent output for now, it will be fixed in next few days.

This issue sounds like a duplicate of #6253.

> Shall we enable "discussions" for such questions instead of issues?

Yes, of course. Please see also the [Managing issues](https://stylelint.io/maintainer-guide/issues).

**Comment by jeddy3** [comment] 2022-08-23 10:07
@fpetrakov Thanks for the suggestion.

> Shall we enable "discussions" for such questions instead of issues?

Issues and StackOverflow are working well for us, including [choosing a template](https://github.com/stylelint/stylelint/issues/new/choose). These types of questions are rare and could easily fall under the [request a new feature template](https://github.com/stylelint/stylelint/issues/new?assignees=&labels=&template=REQUEST_A_FEATURE.yml). I don't think it makes sense introduce another comms channel to manage as I suspect users will start adding feature requests or requests for support there.

> This issue sounds like a duplicate of https://github.com/stylelint/stylelint/issues/6253.

Yes, we can close in favour of that issue.

**Closed by jeddy3** 2022-08-23 10:07 UTC

**Comment by ybiquitous** [comment] 2022-08-23 10:10
> Yes, of course. Please see also [Managing issues](https://stylelint.io/maintainer-guide/issues).

Oh, I completely misunderstood it. Sorry for any confusion.
