### ISSUE TITLE
Typescript error when calling stylelint function

### ISSUE THREAD

**Issue by gael-boyenval** [stylelint/stylelint#4811] opened 2020-05-28 15:10 UTC
> when using stylint within a postcss plugin list, we get a typescript error. 
```
This expression is not callable.
  Type 'typeof import(".../node_modules/@types/stylelint/index")' has no call signatures.
```

> What code is needed to reproduce the bug?

non working js exemple but is enough to produce the typescript type error

```ts
import stylelint from 'stylelint';
import postcss from 'postcss';

const plugins: Array<() => void> = [
  stylelint(stylelintConfig), // => type error here
  csso(),
  reporter({ clearReportedMessages: true }),
];

postcss(plugins)
     .process(scss, {
        /*...*/
      })
     .then(res =>  /*...*/ )
     .catch(err => {  /*...*/ })
```

> Which version of stylelint are you using?

e.g. `13.5.0`

> How are you running stylelint: CLI, PostCSS plugin, Node.js API?

PostCSS plugin

> Does the bug relate to non-standard syntax (e.g. SCSS, Less etc.)?
nope

**Comment by jeddy3** [comment] 2020-06-03 10:40
@gael-boyenval Thanks for the report and for using the template.

The types published at `node_modules/@types/stylelint` are out-of-date and are for a much older version of stylelint.

We intend to publish the JSDoc-based types included in stylelint. See https://github.com/stylelint/stylelint/issues/4399. That issue is marked as needing help.

In the meantime, I believe you can declare a bare local module for stylelint to work around this.

I'll close this as a duplicate of #4399 for now.

**Closed by jeddy3** 2020-06-03 10:40 UTC
