### ISSUE TITLE
Missing semicolon in JSON file

### ISSUE THREAD

**Issue by deepslam** [stylelint/stylelint#7714] opened 2024-05-24 14:19 UTC
Hi guys!

Sorry to interupt you, I'm new in stylelint.
I have a problem, stylelint complains on a JSON file which looks completely fine for me.
Please help me, what's wrong?

Here's the file:

[CrosswordData.json](https://github.com/stylelint/stylelint/files/15435788/CrosswordData.json)

and here's the complain:

 2:10  ✖  Missing semicolon. (2:10)

Thank you for your help!
It's a new project for me, I made a few changes and fixed everything but this one I cannot understand.

**Comment by ybiquitous** [comment] 2024-05-24 14:29
Hi @deepslam, can you provide more info to reproduce the error?

- How do you run Stylelint? Via CLI? (e.g. `stylelint your-json-file.json`)
- What content is your Stylelint config? (e.g. `.stylelintrc.json`)

**Comment by deepslam** [comment] 2024-05-24 14:44
> Hi @deepslam, can you provide more info to reproduce the error?
> 
> * How do you run Stylelint? Via CLI? (e.g. `stylelint your-json-file.json`)
> * What content is your Stylelint config? (e.g. `.stylelintrc.json`)

Thank you for so quick reply!
Here's my .stylelintrc.yaml:

`
processors:
  - stylelint-processor-styled-components

extends:
  - stylelint-config-recommended
  - stylelint-config-prettier
  - stylelint-config-styled-components
`

And this is how I run it:

`npm run stylelint src/stories/CrosswordData.json`

And it gives me this error:

src/stories/CrosswordData.json
 2:10  ✖  Missing semicolon. (2:10)

**Comment by ybiquitous** [comment] 2024-05-24 14:56
Thanks. Your stylelint seems outdated because `processors` has been removed in 15.0.0. See:
https://stylelint.io/migration-guide/to-15#removed-processors-configuration-property

Also, I'm not sure about [stylelint-config-styled-components](https://github.com/styled-components/stylelint-config-styled-components), but it's also outdated (last published 7 years ago).

In the usual way, Stylelint cannot analyze JSON files... 🤔

**Comment by deepslam** [comment] 2024-05-24 15:49
> Thanks. Your stylelint seems outdated because `processors` has been removed in 15.0.0. See:
> https://stylelint.io/migration-guide/to-15#removed-processors-configuration-property
> 
> Also, I'm not sure about [stylelint-config-styled-components](https://github.com/styled-components/stylelint-config-styled-components), but it's also outdated (last published 7 years ago).
> 
> In the usual way, Stylelint cannot analyze JSON files... 🤔 
> 
> 

Thank you for your time and your help!
I just forked a repo and trying to figure out how it works.
And I believe that the best way to fix the error is to exclude json files at all.
And after that, I'll probably update dependencies and remove styled-components.

**Comment by ybiquitous** [comment] 2024-05-24 16:08
Okay, I'm closing this. If you find any problems, feel free to reopen the issue.

**Closed by ybiquitous** 2024-05-24 16:08 UTC
Labels: status: needs reproducible example
