### ISSUE TITLE
Fix ExperimentalWarning: Readable[Symbol.asyncIterator] error

### ISSUE THREAD

**Issue by mmswi** [stylelint/stylelint#4794] opened 2020-05-20 15:48 UTC
> Clearly describe the bug

After updating from 13.3.3 to 13.5.0 I get the following error in PhPStorm

> /Users/.../.nvm/versions/node/v10.15.1/bin/node /Users/.../project-path/node_modules/stylelint/bin/stylelint.js -f json --stdin-filename source/pages/Page.vue
> [{"source":"/Users/.../project-path/source/pages/Page.vue","deprecations":[],"invalidOptionWarnings":[],"parseErrors":[],"errored":false,"warnings":[]}]
> (node:23664) ExperimentalWarning: Readable[Symbol.asyncIterator] is an experimental feature. This feature could change at any time

> Which rule, if any, is the bug related to?

no rule

> What code is needed to reproduce the bug?

e.g.

```javascript
async function () {
            await httpCall()
        }
```

> What stylelint configuration is needed to reproduce the bug?

e.g.

```json
{
    "extends": [
        "stylelint-config-standard",
        "stylelint-config-recommended-scss",
        "stylelint-config-rational-order"
    ],
    "rules": {
        "indentation": 4,
        "rule-empty-line-before": null,
        "at-rule-empty-line-before": null,
        "declaration-empty-line-before": null,
        "no-descending-specificity": null,
        "number-leading-zero": "never",
        "string-quotes": "double",

        "scss/at-import-no-partial-leading-underscore": true,
        "scss/no-duplicate-mixins": true
    }
}
```

> Which version of stylelint are you using?

e.g. `13.5.0`

> How are you running stylelint: CLI, PostCSS plugin, Node.js API?

PhPStorm with Inspections

> Does the bug relate to non-standard syntax (e.g. SCSS, Less etc.)?

e.g. "Yes, it's related to javascript"

> What did you expect to happen?

e.g. "No warnings to be flagged."

> What actually happened (e.g. what warnings or errors did you get)?

e.g. "The following warnings were flagged:"

```shell
/Users/.../.nvm/versions/node/v10.15.1/bin/node /Users/.../project-path/node_modules/stylelint/bin/stylelint.js -f json --stdin-filename source/pages/Page.vue
[{"source":"/Users/.../project-path/source/pages/Page.vue","deprecations":[],"invalidOptionWarnings":[],"parseErrors":[],"errored":false,"warnings":[]}]
(node:23664) ExperimentalWarning: Readable[Symbol.asyncIterator] is an experimental feature. This feature could change at any time
```

**Comment by mmswi** [comment] 2020-05-22 07:31
Just checked with 13.4.0 and it seems that this introduces the error.

**Comment by jeddy3** [comment] 2020-06-03 12:06
@mmswi Thanks for the report and for using the template.

Judging by the thumbs up, this is effect a few other people too. However, I'm unable to reproduce this locally using the CLI and node version 10.15.1.

I'll label as needing investigation to determine if the issue lies with stylelint itself or with its use in PHPStorm. If you're affected by this issue, please consider helping out with the investigation.

**Comment by jepstein-eagle** [comment] 2020-06-11 16:48
Node.js removed the "Symbol.asyncIterator" warning in Node.js 10.17.0 and above via this [PR](https://github.com/nodejs/node/pull/26989). They no longer felt the feature was experimental, so the warning was removed.

I am able to point to higher Node.js versions in the Stlylint plugin settings in WebStorm (another affected JetBrains IDE). We should attempt to locate the exact source of the issue so users on these versions do not see this warning.

**Comment by acha5066** [comment] 2020-07-21 05:16
Similar issue for me on 13.6.1 using the basic setup (css only). My node version is v8.12.0 and I'm running on the CLI (no PHPStorm integration). However, it is not a warning for me but an error relating to an async iteration in the get-stdin library which prevents me from using that version. Reverted to 13.3.3 and the issue went away.

**Comment by calsal8** [comment] 2020-08-17 14:51
I've been waiting for a fix since June because my IDE kept showing me this irritating warning but I just realised I could upgrade Node instead, i had v11.8.0. So for all of you who wants an easy fix to get rid of the warning, upgrade to Node v12.18.3 (or higher). 

As [jepstein-eagle mentions](https://github.com/stylelint/stylelint/issues/4794#issuecomment-642803837), you might need to select the Node version in Stylelint settings.

**Comment by jblotus** [comment] 2020-10-23 19:49
I'm also trying to use stylelint with Intellij - the interpreter I want to use is node 10.16.3 

The warning itself prevents stylelint from actually showing any results in the IDE (this may be an upstream bug).  It does look like stylelint is emitting the rule output.

![image](https://user-images.githubusercontent.com/382230/97047525-21458e80-1547-11eb-8da1-ee9bde97b25d.png)

```
"mycode\node_modules\stylelint\bin\stylelint.js -f json --stdin-filename  myfile.css
[{"source":"mycode/myfile.css","deprecations":[],"invalidOptionWarnings":[],"parseErrors":[],"errored":true,"warnings":[{"line":8,"column":1,"rule":"max-empty-lines","severity":"error","text":"Expected no more than 1 empty line (max-empty-lines)"},{"line":50,"column":5,"rule":"indentation","severity":"error","text":"Expected indentation of 2 spaces (indentation)"}]}]
(node:5840) ExperimentalWarning: Readable[Symbol.asyncIterator] is an experimental feature. This feature could change at any time
```

**Comment by deadka1313** [comment] 2021-03-29 06:28
A similar problem. Webstorm

**Comment by jeddy3** [comment] 2021-03-29 13:43
This is still open and need of help to investigate. Having said that, Node 10 is EOL at the end of April and stylelint will be moving to a minimum version of Node 12.

**Comment by alexander-akait** [comment] 2021-03-29 13:46
@jeddy3 Node.js v13 is very unstable and have a lot of bugs, I think better to say: "Please prefer to use only LST releases"

**Closed** 2022-01-18 16:41 UTC
Labels: status: needs investigation, help wanted
