### ISSUE TITLE
How to let Stylelint accept CSS Module syntax?

### ISSUE THREAD

**Issue by MenaiAla** [stylelint/stylelint#7170] opened 2023-09-05 17:33 UTC
### What minimal example or steps are needed to reproduce the bug?

We are using a CSS module in our NextJS project, and we integrate stylelint, however, I could not figure out which rule I apply to achieve the camelCase syntax.

```css
.contentContainer{

}
```

In our project, our CSS was made with modules syntax m while when we integrated stylelint it requires the hyphen-casem which enforc us to access our styles like this : `styles['content-container']` which what we want it  as a  convention.

### What minimal configuration is needed to reproduce the bug?

.

### How did you run Stylelint?

.

### Which Stylelint-related dependencies are you using?

.

### What did you expect to happen?

.

### What actually happened?

.

**Comment by Mouvedia** [comment] 2023-09-05 22:16
IIUC you want https://stylelint.io/user-guide/rules/selector-class-pattern

**Comment by mattxwang** [comment] 2023-09-11 00:33
Hi @MenaiAla, could I ask you to fill out the issue template? In other words, what code is accepted/rejected by Stylelint that shouldn't be, and what is the behaviour you're looking for? It's not clear from what you've written right now what the problem is (i.e., as Marc has mentioned above, you can set the options for `selector-class-pattern`).

**Comment by Mouvedia** [comment] 2023-10-09 23:05
After one month and without any responses to @mattxwang's inquiries, I am closing this issue.

**Closed by Mouvedia** 2023-10-09 23:05 UTC
Labels: status: needs clarification
