### ISSUE TITLE
Missing documentation for --report-needless-disables CLI flag

### ISSUE THREAD

**Issue by thibaudcolas** [stylelint/stylelint#4347] opened 2019-10-14 11:55 UTC
I couldn’t find any documentation for the `--report-needless-disables` CLI flag on the website, both by browsing the site manually and googling it. The only documentation for it seems to be in the `stylelint --help` output, and https://stylelint.io/user-guide/node-api#reportneedlessdisables for the Node API.

> What solution would you like to see?

I think there should either be:

- A (small) section on https://stylelint.io/user-guide/cli about this flag, example usage and quick explanation like what is shown in `--help`.
- Or add the output of `stylelint --help` at the top of the CLI docs like ESLint does: https://eslint.org/docs/user-guide/command-line-interface#options

Or both of those things combined – so all CLI flags have at least minimal documentation on the website, and specific flags can have an additional section that can be linked to directly.

**Comment by hudochenkov** [comment] 2019-10-14 11:58
Thank you. Your ideas are good. But I'll close this one as a duplicate of https://github.com/stylelint/stylelint/issues/4094

**Closed by hudochenkov** 2019-10-14 11:58 UTC

**Comment by thibaudcolas** [comment] 2019-10-14 13:08
Ah thanks, I did look around but somehow didn’t find that issue 👌
