### ISSUE TITLE
Fix autofix for switch statements within literals

### ISSUE THREAD

**Issue by Newbie012** [stylelint/stylelint#5051] opened 2020-11-22 09:23 UTC
> Clearly describe the bug

When I try to write a nested switch case inside a react component with styled-components while using the literal `css`, it duplicates a lot of lines that shouldn't be appended.

```tsx
const Button = styled.button<Props>`
  border: 2px solid var(--border-color);
  background-color: var(--background-color);

  ${(props) => {
    switch (props.variant) {
      case "filled":
        return css`
          --background-color: #ffca28;
          --foreground-color: #000;
        `;
      case "outlined":
        return css`
          --background-color: transparent;
          --foreground-color: #fff;
          --border-color: #fff;
        `;
      case "soft":
        return css`
          --background-color: rgba(255, 255, 255, 0.12);
          --foreground-color: #fff;
        `;
    }
  }}

  :disabled {
    opacity: 0.5;
  }

  :hover:not(:disabled) {
    opacity: 0.8;
  }
`;
```

> Which rule, if any, is the bug related to?

I'm not sure if it's related to `"stylelint-config-recommended"` or `stylelint-config-styled-components`.

> What code is needed to reproduce the bug?

Given the code above, on a fix, it will be saved as:

```diff
const Button = styled.button<Props>`
  border: 2px solid var(--border-color);
  background-color: var(--background-color);


  ${(props) => {
    switch (props.variant) {
      case "filled":
        return css`
          --background-color: #ffca28;
          --foreground-color: #000;
        `;
      case "outlined":
        return css`
          --background-color: transparent;
          --foreground-color: #fff;
          --border-color: #fff;
        `;
      case "soft":
        return css`
          --background-color: rgba(255, 255, 255, 0.12);
          --foreground-color: #fff;
        `;
    }
  }}

  :disabled {
    opacity: 0.5;
  }

  :hover:not(:disabled) {
    opacity: 0.8;
  }
+
+          --background-color: #ffca28;
+          --foreground-color: #000;
+        `;
+      case "outlined":
+        return css`
+          --background-color: transparent;
+          --foreground-color: #fff;
+          --border-color: #fff;
+        `;
+      case "soft":
+        return css`
+          --background-color: rgba(255, 255, 255, 0.12);
+          --foreground-color: #fff;
+        `;
+    }
+  }}
+
+  :disabled {
+    opacity: 0.5;
+  }
+
+  :hover:not(:disabled) {
+    opacity: 0.8;
+  }
`;
```

> What stylelint configuration is needed to reproduce the bug?

```json
{
  "extends": [
    "stylelint-config-recommended",
    "stylelint-config-styled-components",
    "stylelint-config-idiomatic-order"
  ]
}
```

> Which version of stylelint are you using?

```
    "stylelint": "^13.7.2",
    "stylelint-config-idiomatic-order": "^8.1.0",
    "stylelint-config-recommended": "^3.0.0",
    "stylelint-config-styled-components": "^0.1.1",
```

> How are you running stylelint: CLI, PostCSS plugin, Node.js API?

npm script `"lint:css:fix": "stylelint src --fix"`

> Does the bug relate to non-standard syntax (e.g. SCSS, Less etc.)?

Yes, it's related to styled-components

> What did you expect to happen?

Not to duplicate the code mentioned above

> What actually happened (e.g. what warnings or errors did you get)?

It has duplicated almost all of my switch case code and what came below.

**Comment by jeddy3** [comment] 2020-11-22 12:19
@Newbie012 Thanks for the report and for using the template.

It's likely a problem with [the parser](https://github.com/stylelint/postcss-css-in-js) stylelint uses [to support CSS-in-JS](https://stylelint.io/about/syntaxes). I've added this issue to https://github.com/stylelint/stylelint/issues/4574, which is a growing list of the problems with the syntax that we need help to fix.

Please consider [contributing to the parser](https://stylelint.io/developer-guide/syntaxes) if you have time.

As this is a corruption caused by autofix, we can [add a temporary workaround](https://stylelint.io/developer-guide/syntaxes#workarounds) that would turn off autofix for files that contain the `switch` construct.

**Comment by jeddy3** [comment] 2022-01-18 15:18
Closing as the [`syntax` option was removed](https://github.com/stylelint/stylelint/issues/5289) for the [14.0.0 release](https://github.com/stylelint/stylelint/issues/5205). (See the [migration guide](https://github.com/stylelint/stylelint/blob/main/docs/migration-guide/to-14.md#syntax-option-and-automatic-inferral-of-syntax).)

We'll also [be deprecating](https://github.com/stylelint/postcss-css-in-js/issues/225) our [forked CSS-in-JS package](https://github.com/stylelint/postcss-css-in-js), in favour of leaner custom syntaxes.

Please consider [writing a custom syntax](https://github.com/stylelint/stylelint/blob/main/docs/developer-guide/syntaxes.md) specific to the CSS-in-JS library in this issue and fixing the bug there.

**Closed by jeddy3** 2022-01-18 15:18 UTC
Labels: status: ready to implement, type: bug, syntax: css-in-js, upstream
