### ISSUE TITLE
Escaped at-symbol in class name causing selector-class-pattern error

### ISSUE THREAD

**Issue by superfein** [stylelint/stylelint#4618] opened 2020-02-24 22:58 UTC
> What is the problem you're trying to solve?

I am using `\@` as part of a class name in a .scss file. The Stylelint error caused by this is: 
"Expected class selector ".grid-auto-cols\@xs" to match specified pattern   selector-class-pattern".

> What solution would you like to see?

A new pattern rule that can handle the escaped `@` in the class name.

My code:
```
$grid-columns: 12 !default;

.grid, [class*="grid-auto-"] {
  display: grid;
  grid-gap: var(--grid-gap, 0);
}

.grid {
  --grid-cols: #{$grid-columns};
  grid-template-columns: repeat(var(--grid-cols), 1fr);

  > * {
    grid-column: span var(--span, #{$grid-columns}) / span var(--span, #{$grid-columns});
  }
}

.grid-auto-xs, .grid-auto-sm, .grid-auto-md, .grid-auto-lg, .grid-auto-xl { // auto-sized grid
  grid-template-columns: repeat(auto-fit, minmax(var(--col-min-width), 1fr));
}

.grid-auto-xs { --col-min-width: 8rem; }
.grid-auto-sm { --col-min-width: 10rem; }
.grid-auto-md { --col-min-width: 15rem; }
.grid-auto-lg { --col-min-width: 20rem; }
.grid-auto-xl { --col-min-width: 25rem; }

.grid-auto-cols { // cols = same size
  grid-template-columns: repeat(auto-fit, minmax(0, 1fr));
}

.grid-gap-xxxxs { --grid-gap: var(--space-xxxxs, 0.125rem); }
.grid-gap-xxxs  { --grid-gap: var(--space-xxxs, 0.25rem); }
.grid-gap-xxs   { --grid-gap: var(--space-xxs, 0.375rem); }
.grid-gap-xs    { --grid-gap: var(--space-xs, 0.5rem); }
.grid-gap-sm    { --grid-gap: var(--space-sm, 0.75rem); }
.grid-gap-md    { --grid-gap: var(--space-md, 1.25rem); }
.grid-gap-lg    { --grid-gap: var(--space-lg, 2rem); }
.grid-gap-xl    { --grid-gap: var(--space-xl, 3.25rem); }
.grid-gap-xxl   { --grid-gap: var(--space-xxl, 5.25rem); }
.grid-gap-xxxl  { --grid-gap: var(--space-xxxl, 8.5rem); }
.grid-gap-xxxxl { --grid-gap: var(--space-xxxxl, 13.75rem); }

@for $i from 1 through $grid-columns {
  .col-#{$i} { --span: #{$i}; }
  .col-start-#{$i} { grid-column-start: #{$i}; }
  .col-end-#{$i+1} { grid-column-end: #{$i+1}; }
}

.col-start { grid-column-start: 1; }
.col-end   { grid-column-end: -1; }

// breakpoints
$breakpoints: (
  xs: 32rem, 
  sm: 48rem,
  md: 64rem,
  lg: 80rem,
  xl: 90rem
) !default;

@mixin breakpoint($breakpoint) {
  @media (min-width: map-get($map: $breakpoints, $key: $breakpoint)) { @content; }
}

@include breakpoint(xs) {
  .grid-auto-xs\@xs { --col-min-width: 8rem; }
  .grid-auto-sm\@xs { --col-min-width: 10rem; }
  .grid-auto-md\@xs { --col-min-width: 15rem; }
  .grid-auto-lg\@xs { --col-min-width: 20rem; }
  .grid-auto-xl\@xs { --col-min-width: 25rem; }

  .grid-auto-cols\@xs { grid-template-columns: repeat(auto-fit, minmax(0, 1fr)); }
  
  @for $i from 1 through $grid-columns {
    .col-#{$i}\@xs { --span: #{$i}; }
    .col-start-#{$i}\@xs { grid-column-start: #{$i}; }
    .col-end-#{$i+1}\@xs { grid-column-end: #{$i+1}; }
  }

  .col-start\@xs { grid-column-start: 1; }
  .col-end\@xs   { grid-column-end: -1; }
  
  .col-start-auto\@xs { grid-column-start: auto; }
  .col-end-auto\@xs   { grid-column-end: auto; }
}
```

**Comment by jeddy3** [comment] 2020-03-04 12:46
@superfein Thanks for the request.

What is your `selector-class-pattern` configuration?

I assume it's possible to configure the rule to accept classes the are suffixed with `@` (escaped or otherwise). If it is not, then I believe it's a bug in the rule that we should fix.

**Comment by superfein** [comment] 2020-03-09 10:59
I'm using this configuration in my `package.json` file:

```
  "stylelint": {
    "extends": "stylelint-config-wordpress",
    "plugins": [
      "stylelint-scss"
    ],
    "rules": {
      "selector-class-pattern": "^(col-|grid-){1}([-]?[\\\\]?[/]?[a-z]+){2,}(__[a-z]([-]?[a-z]+)*)?(--[a-z-]+)?(\\\\@[a-z-]+)",
      "at-rule-no-unknown": [
        true,
        {
          "ignoreAtRules": [
            "extend",
            "at-root",
            "debug",
            "warn",
            "error",
            "if",
            "else",
            "for",
            "each",
            "while",
            "mixin",
            "include",
            "content",
            "return",
            "function"
          ]
        }
      ]
    }
  }
```

**Comment by jeddy3** [comment] 2020-03-09 13:51
> Escaped at-symbol in class name causing selector-class-pattern error

I'm not able to reproduce this using [the demo](https://stylelint.io/demo#N4Igxg9gJgpiBcIB0BDAOmgAgIwATAF80A7EAGhAGcBPYgFxQA8FxLLzwJiAzASwHMWwErlxoQAJwCuAGxiVx8fCNFiqMOWDoQJAWjAyUbXQAcUdOjAnFFa9BiwBtFLoBeAXXErRKosQIgBEA).

Perhaps there is a problem with your regex? For example, I [don't believe you need to escape `@`](https://stylelint.io/demo#N4Igxg9gJgpiBcIAkBzATgSygWkgGwFcBbAOwGd4ACARgCZKBCWAMwEMC8AXAbgB0T+AOnRYANJQDaYPKzJkAVAF5eIETnacI2FQF1KwfpUpQMZAA4yAnlTV8SRtdhSszVAG6s0ACmxPMOZzNxAAYASjsAX34hNX1okiiBEmF-bA0tAA8ycRSsNIJNbDIiHMd07CIoUtTyvBRqvPKMvH1KQ0pHThgiC1Yu3AhCUgpKNBgzGD6vcuYMTnEiDBIiVgyvD29ffAql7AB3LE4AC1DxamY0UPD+RJiagsyyVq3BnZJ9w6OqAA4xom5KIlcuoHkUiM8Bng3h8oMcqNRgn8AUCyqDKhDtot3gdYV8aABWJGAu6NUF1DGvLEwuGUWiI7rIkkgwrNClQqk4mm0QkM4lJYH5Qr4J7ANr2DqpLo9GT9fDEchUMYTKYzOYLJYrNbBM4XK6ReICwLYDImrIQxyBdyeHxFMysMAwY2m7KUYKCOg8ojhPmGlxOs3m1KWygbG3me2O50hQTcv7elFBv0mp5GUW+C0uK2bW0Rp0ut0AZgA7J740ynEmU6nKOnE64Q9bfOGHcb84JS4zkhmzGCjNXa3lg6Gm3aW8VoyW453fT30X2035B5mG9nm47KmcYx2fd3sOT5zXFwFl8Ocy26uJaFOd3XjS0DwPj-XT2u7+IC1vrwmlz2TffAz+WZhqOkbNOI+Kft0ZZdrepr3gu3ZASOuZweI3ztl+5ZGqarIIXWSFnqBf5nB+k5QZ2QjbGQnCeJwrSOHKpBFDRaCcPC07bDAJBQAeDGDPK2BcVAVDYNQFFJAAAosGRLJQABGYysAA1mYEBLJwXhIApkwqWpJCcKEcTilJMAmKwlBeBynxUCsPYoDAGlILZVBaYpunqS6SBKTA1iUK5OmqepVytBJkD6VxPB8rcJASUs0gELA8luYF+leFkhkGOKApNGQvC8BJZoLpiuycnivy8okRjZaCxR5QVIqHsV2LWTQ9L-HyVWooUlR1YVjWUiVLXUJ6nadfchR1L1DUvOyg24lQdJEpVlDVSyeBTWy0KlQtI18u0q1aMKG2ip03S9LK-HDIq4yTBpqrzJQWKal42o0Lq0FGPEVVUSxnDHRKeSMe81G0exHUrZx3EbdWfFDO8QkiWJ4P7T9tGChA-2wwJIOsVQ6SjRDrxCej0P0akQOCdxeMPJ2iQgKIIBkJY+mrAg4ByPT4AQCQswoGzmWfSAaAcDAuUIEZfZtIzMB4DAYCaGguAyHI2B2pwXRoAI4sqAAel42wAD6OKEwDUBEXgSNgOgAPwSHl9v2zbEgAPRO6w2AAF46AA1CbtCiObAD6gcSO7XsW1btthz7oTyKE1s2qHntW77CcOxJSceyn8cqKI7SC302DC7L2AkFoBAkEpZd7FrVCcMLMB5+KgtyXgEBgEppdaGdnCWCodcN03ksqPgECK2X2BLB4eB5EcMAZP3lD1wQjf51LkBEEQEVd4JPS94vy+r83UuwNInh9Bg3PYK37edxPUAEBYGBgH0jpmGgEATKxGCi4vdvH0YQ+Q9JYSxAYLDAKAy5jD-mvMBI9uZkDlgUDAbhHQPyfi-LoZAPjHGwCYZgzAYBjH0tgaeK8xawL7DoShy0jA6GAYLU+Mg0AXyvjfDuO8yBHDHscVg3FVYfy-r3bAEBUFoH8L-cWQC14qGYNzTg2A2CLDwJYHe6CZ6YMdCQVgW8xYDxXgwqWciSFKIwConeiw5BLBQE4LiRDn6KJ0WY1R3lLB7DHlAA+g8ZEgGYBXeWl93gvzwGAHeU9WAz08VI7xx9ZH+M4IE3AETQkTwrmuHAn8iF9DHl4gxPi-EkACVfGeJBJiK3QKwEw28J5l3IDRbingcAmDGEU2uS8YnDxAK4i4Oi0Fy2Yaw94E8MA9B4Xwv60S8mxJAFvMyijboEDGKXXpO8K5VwgDXXJR9On31Fg6bi1jbRywwLMMAcw+6TO2X2FQ99H4aNfmkBRIzVKsSLiLPR7Spk7K0Oo5+DzEGy3lmPD50jpkTx7qosgEBFkOi2YYm53cMj13dogxYo9yBwp8cMkg088hQGha3R0ZBlZHAGJvCKIKOnXJAO-TJrFVGpMrtXNpoLOkArlgrVWiCEqHWVtgxl6zNmXPhdLQFnKzDcvxYJWWW8SECuZZi6Z7KgWK17hMVZTKNksqpYLaimASA2JqTAPYJSYCKs6RXOYGrBXaq+dSwuxdHQQr3EsR0ckYByOgeLf+cCQARL2KwSwYtDGpkoYLeeDozATKoD6sB1L2FKVlirVgzANZFBWdore1824dyTcGsN1LZhoGoqXUWXQokFvoQWlQECoFmu9QWguqaiFktlRMytNC15VumQ6kWyys0v0QYvFQbc9hENzj43tJdM1EpAmkZtaBh1+rwAGoNRRrEl1NROntCjHVFG6M-QYV9SkmtdfOjWS7-WBvzdMhNSsIBkEOQpXMzrTXXw9WPetVAbkwDEduzpd7pAPqfSwlsJ630povdrZdq6b0AZzZ3IDj6DXX1A1o41b73Weq-VLK9a6iAcASS60p-740Ifvchmxz6xxzqw5+y9K7r3roNZu11pGW7kcySQEDuZwNnsg+O6DeHsEEa4BgYj9aRV3q4zxmjuYBOLqE4xtdlHWMkfpj46TExuMoeo7O3MdGvXfpg9e9j68j2KznhkJJQ7oOjsEyK0eln557i4igY4S6uE8LM-A8lJDX1nsMzh2NnThNmdDQA6lEbxjRskI2oxGBi0KNKdRUyKhK0hupbW+jDbItst7rLEpCiN4rG4hQvLlBqGRdoZVxzEA-MKL2EcOYos51LEfbABjsGfPgAINRerAi6XCIC6U992GYGRZUGFjTkWBZxpUNFqNE2432oXbgPrmgiCDaERczLnSi0lpS+W9LFXu0rZrZAnLMb4tTbWyViK4WQE1vIFgIlG7HSYYQydlbVWwE1bO9Sph58ElsL4TY18Cml2lL-TNzpQOWEg-eHJMHhExtXdw8puDgP+nA8SXe1Fh625DIw-xhdXWmOiaI1u2H2Oz4I7x+Rgn6LUeQ6U7B5jKA1OSZ8fDwZ2bb77rRUe4GtGP1GaltDhzPOcf07YYz97EmKirDwTLwZHzqAit54j-nHDkVmMOUz4X5Og09a14k5nfHRus+M8JiohHxPU816r7XzOIdk7Z0x1TH22M08Yc783wvUdBah7+qX0yzdXxG26sXwXKFTcx49ubvrFuxZC-Nv1a2I9az24WxLh2y1pZABl6tIBsvi7T76hTraHu+-T+117HOuc66Ut9uNv2QH-ZFQU1prb3aW8dNbjH7PKcO5913+JAfN4ornYP+P7OvcSZ693l39WVhB5jyHmH4-Cna81LvKNqjTUfO1Pkifx6VmDpwyOjZYf9tn-eHaYhxxRai1Lae0b9fOse-w-bxfte4k76JKP4RRzyILYKvif5X4gCS6KwL6O6n6AFXxNYtZu5QY24J7-6l7cQRSDKLz+w+KywGq4IexEJaCMpzDmrUp75R7q4iqzIYDuyEJ9CLKOiu4z7u7oHdaYH0GMELJLJsEGYb7QYwE9Y8HzLMFLIzo2ZQH2aKZ0GmQMHiGcAsGqyeAgEv7gFtYvZf7GYiHcEKG8ESGOgsIGqOh0rZKwHsFoFD6mb6FzJMHKFLImH2QiJfwWHr7jbf5Y6CxiEACOK8aAh+pgxWq+feJOVuHBNhP+Ymf+8hcy-hRCQRJaJW0+8mkRc+nuCu8B0yfhARSRIRU+Hh6OP6W+WK3crwyBWCIElBgsE8lilGlMGSzARQ0KaAYG4ROGrK1KJAxA7qissslShyJBH8xu3hEuvRLaE8euJSNiwxD6NRUstKO20hS6shPWe6UeaO5eceJm0RVOY+lCSeT2IAKey2K2CWSWpaqWFap2OeF2daZx52Geaa92+kreYC7eksnePiyqnKfQ9cGAckBQbqoG3knAmhuYkBm+t+1KvxY8jyAJQJ-Q5hnKqBgmuhoechPxMsHK8J-xmASJZhbhqJounhGJpRSqOJKqZKckSw7haJimnBthIqcJisG8tJ2iJJghZJURYxKgrJKuZA+yUA4yNJdJnKNSV8a4Cx-JVJnKM8yRoRb+EG6RuxfJoquJ-RwRveRR4uJRMJuqcp8J1Be8QRKWi8J+lJYq8JEqMAPKSssg2Cl+qxN+WJVpmpXKdpUqZ8KswB+koBr+EB2hUBehLJRpistp9pOJbaKxdmrpPWApkZUq0Z28FuEANEiOS6+KBAhKCZ4Z2AaqrBsgMh8ZmBlqxWxZLpY6bpnSZCjori7iaAOAzpcZ1ZPWdZLqiphR-e566JvJduMR2RtZESK8nZBRa+DJoxje3u6mIqHZCp45qRLYwewhmJ7ZI53uJaJpB+Emx+7QiQEQIAEQQAA). This appears to work for everything but the `.grid` class, but I believe that's because the regex requires classes to start with either `grid-` or `col-` (with a suffixed dash), which `.grid` does not.

I'm going to close the issue for now. However, feel free to reopen with a reproducible repo or demo showing the erroneous handling of escaped characters.

**Closed by jeddy3** 2020-03-09 13:51 UTC
Labels: status: needs reproducible example
