### ISSUE TITLE
Hyphens in less variables names call error in function-calc-no-invalid 

### ISSUE THREAD

**Issue by MrVladevoit** [stylelint/stylelint#4102] opened 2019-06-05 13:54 UTC
**function-calc-no-invalid / "stylelint": "^9.10.1"**

After adding less variables to calc function i have error in function-calc-no-invalid. It expects me to put space on each side of the "-:

```
div {
  width: calc(100% + @tooltip-padding); // error
}
```
Stylelint prints the errors:

```
Expected space before "-" operator
Expected space after "-" operator
```

**Comment by hudochenkov** [comment] 2019-06-05 14:02
Please, update your issue [using a template](https://github.com/stylelint/stylelint/issues/new?template=REPORT_A_BUG.md). No need to close and create again with the same text. Edit current issue.

**Comment by ota-meshi** [comment] 2019-06-07 06:52
@MrVladevoit Hello!
I think you can write as follows.

```less
div {
  width: calc(100% + @{tooltip-padding});
}
```

**Comment by ota-meshi** [comment] 2019-06-07 06:57
I gave a misinformation.
#4046 has not been released, so changing the syntax may not solve it.

**Comment by hudochenkov** [comment] 2019-06-07 16:21
Could you try the latest release `stylelint@10.1.0`, please?

**Comment by MrVladevoit** [comment] 2019-06-12 12:03
@hudochenkov , i am updated stylelint to 10.1.0, but this version have same problem

Code less for example: https://codepen.io/mrvladevoit/pen/xobMJj?editors=0100

Screenshots of this error: 

![image](https://user-images.githubusercontent.com/12032655/59349756-1956c700-8d23-11e9-8fbe-c301a16abecc.png)

![image](https://user-images.githubusercontent.com/12032655/59349760-1bb92100-8d23-11e9-91ff-f54303050774.png)

**Comment by LolliDepp** [comment] 2020-01-09 18:07
Opened PR #4534 to highlight underlying issues in the test cases

**Comment by jeddy3** [comment] 2020-01-12 02:39
Closing as duplicate of https://github.com/stylelint/stylelint/issues/4114

**Closed by jeddy3** 2020-01-12 02:39 UTC
Labels: syntax: less, syntax: sass, type: bug
