### ISSUE TITLE
Allow overriding rules via CLI arguments

### ISSUE THREAD

**Issue by GergelyKalmar** [stylelint/stylelint#6805] opened 2023-04-21 18:17 UTC
### What is the problem you're trying to solve?

There are cases when it would be useful to be able to override certain rules via CLI arguments (similar to how ESLint allows this: https://eslint.org/docs/latest/use/command-line-interface#--rule, or how [black](https://black.readthedocs.io/en/stable/usage_and_configuration/the_basics.html) or [pylint](https://pylint.readthedocs.io/en/latest/index.html) allow this for at least the maximum line length).

I'm working on integrating Stylelint into [pytest-logikal](https://docs.logikal.io/pytest-logikal/latest/), which is a comprehensive web application testing framework, however, I can't seem to be able to specify the line length when invoking `stylelint`, which would be necessary for a successful integration.

### What solution would you like to see?

It should be possible to override the rules when running in certain environments (e.g. in CI vs. locally) or when called as part of larger test suites (e.g. when there are multiple tools that need to share the same maximum line length value).

**Comment by GergelyKalmar** [comment] 2023-04-22 12:24
I'm not sure. The use case in that issue is to be able to have a run with just a single rule, here the use case is to be able to append to the existing set of rules (just like it is in ESLint). The other use case would need a `--no-config` option too (if the rule option extends instead of overwriting).

**Comment by ybiquitous** [comment] 2023-04-22 13:20
@GergelyKalmar I think <https://github.com/stylelint/stylelint/issues/4331#issuecomment-1266481392> seems to meet your request, but different?

**Comment by GergelyKalmar** [comment] 2023-04-22 13:38
Yes, what is described there would be fine for this use case as well.

**Comment by ybiquitous** [comment] 2023-04-23 01:13
Okay, let's continue to discuss it on #4331. If you have any concerns, feel free to comment on #4331.

Duplicate of #4331

**Closed by ybiquitous** 2023-04-23 01:13 UTC
