### ISSUE TITLE
Flow type error unusedRange.start in stylelint/lib/needlessDisables.js:48

### ISSUE THREAD

**Issue by rolele** [stylelint/stylelint#2562] opened 2017-05-09 00:25 UTC
> The issue appear when running flow type check: ``` npm run flow ```
```
/Users/others/universal-react-redux-boilerplate/node_modules/stylelint master ⚡
$ npm run flow                                                                 [10:20:24]

> stylelint@7.10.1 flow /Users/others/universal-react-redux-boilerplate/node_modules/stylelint
> flow

lib/needlessDisables.js:48
 48:           return unusedRange.start === range.start && unusedRange.end === range.end
                                  ^^^^^ property `start`. Property not found in
 48:           return unusedRange.start === range.start && unusedRange.end === range.end
                      ^^^^^^^^^^^ object type


Found 1 error

npm ERR! Darwin 16.4.0
npm ERR! argv "/Users/pierrecaserta/.nvm/versions/node/v4.5.0/bin/node" "/Users/pierrecaserta/.nvm/versions/node/v4.5.0/bin/npm" "run" "flow"
npm ERR! node v4.5.0
npm ERR! npm  v2.15.9
npm ERR! code ELIFECYCLE
npm ERR! stylelint@7.10.1 flow: `flow`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the stylelint@7.10.1 flow script 'flow'.
npm ERR! This is most likely a problem with the stylelint package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     flow
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs stylelint
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls stylelint
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/others/universal-react-redux-boilerplate/node_modules/stylelint/npm-debug.log
FAIL: 1
```

on the file: needlessDisables.js
I see few commented flow types, maybe that is the problem
```
module.exports = function (results/*: Array<stylelint$result>*/)/*: stylelint$needlessDisablesReport*/ {

...

function isWarningInRange(
  warning/*: {
    rule: string,
    line: number,
  }*/,
  range/*: {
    rules?: Array<string>,
    start: number,
    end?: number,
  }*/
)/*: boolean*/ {

...
```

**Comment by ntwb** [comment] 2017-05-09 01:43
@rolele Thanks, did you run `npm install` / `npm update` in your repo?

We updated Flow ~11 days ago in #2538 and there are no issues with our CI tests, I also cannot reproduce this locally

Also the latest NodeJS 4.x branch is `4.8.3`, is there a specific reason why you're using `4.5.0`?

**Comment by ntwb** [comment] 2017-05-09 06:26
Thanks @casertap, closing this now 👍

**Closed by ntwb** 2017-05-09 06:26 UTC
Labels: status: discussion
