### ISSUE TITLE
Fix `no-duplicate-selectors` hang for leading namespace char

### ISSUE THREAD

**Issue by cordis-dev** [stylelint/stylelint#6344] opened 2022-09-12 11:56 UTC
### What steps are needed to reproduce the bug?

Run stylelint for:

```cs
| h1 {
  color: red;
}
```

### What Stylelint configuration is needed to reproduce the bug?

```json
{
  "rules": {
    "no-duplicate-selectors": true
  }
}
```

### How did you run Stylelint?

`"%ProgramFiles%\nodejs\node.exe" "%AppData%\npm\node_modules\stylelint\bin\stylelint.js" test.css`

### Which version of Stylelint are you using?

`14.11.0`

### What did you expect to happen?

Expected process to exit.

### What actually happened?

Process did not exit.

**Comment by ybiquitous** [comment] 2022-09-12 13:45
@cordis-dev Thanks for opening the issue and using the template.

I can reproduce the bug via the following code:

```js
const selectorParser = require('postcss-selector-parser');
selectorParser().processSync('| h1', { lossless: false });
```

Here is the related code:

https://github.com/stylelint/stylelint/blob/dd04517bd17690e7ebb835df229d63923bdee633/lib/rules/no-duplicate-selectors/index.js#L170

It seems to be a problem with `postcss-selector-parser`, but I'm not sure now.

**Comment by ybiquitous** [comment] 2022-09-12 13:48
Perhaps the same problem as https://github.com/postcss/postcss-selector-parser/issues/266

**Comment by jeddy3** [comment] 2022-09-12 13:54
@ybiquitous Thanks for the investigation. It does look to be caused by that bug in the selector parser.

@cordis-dev Thanks for the report. The maintainer of the selector parser package has welcomed to pull request to fix the issue. Please consider contributing if you have time.

**Comment by romainmenke** [comment] 2023-05-21 21:01
This has been fixed upstream.
Cases like these will no longer hang indefinitely, but will throw an exception.

Do we need to add a test cases here?
Or good to close?

**Comment by ybiquitous** [comment] 2023-05-21 23:56
@romainmenke Thank you so much for fixing it upstream! We can see the problem never occurs with [this demo](https://stylelint.io/demo/#N4Igxg9gJgpiBcIA+ACAFgRhcAOgOxRUgBsIAneFMmKAbnwF8QAaEAMwEtiYA5AQwC2cRDAAeggA7cAdGADOcluAh5OAcwQhcBFDhBiALjDxQ5eygG18hQnrkGAnt2Ic8BgLSRVHNe-t8TPjIoPWsUAF1GJS91ADFyAT4DTQArORUlWAlFRG1bEHsnGBc3c10QYiSYez1mMLtHZ1cPGJ8-AwCoIJCEcsqjGpAohiA). 👍🏼 Analyzing process exits with the error message `Unexpected '|'`.

<img width="224" alt="image" src="https://github.com/stylelint/stylelint/assets/473530/5b8408bd-9709-469f-ac2b-71642bcdf364">

Let's close it.

**Closed by ybiquitous** 2023-05-21 23:56 UTC
Labels: status: ready to implement, type: bug, help wanted, upstream
