### ISSUE TITLE
Fix unexpected `cannot read properties of undefined` error when reading `config`

### ISSUE THREAD

**Issue by romainmenke** [stylelint/stylelint#8044] opened 2024-10-14 18:52 UTC
> We are using stylelint with our vite project — and something in 16.10.0 is causing errors for us: "Internal server error: Cannot read properties of undefined (reading 'config')"
>
>Current setup is that we have a .stylelintrc.yml that extends our global .stylelintrc.json; but we keep getting this error even though 16.9.0 works just fine! This is the only part of the changelog referencing a config > so starting here.

_Originally posted by @michwads in https://github.com/stylelint/stylelint/issues/8030#issuecomment-2411951545_

**Comment by romainmenke** [comment] 2024-10-14 18:55
@michwads Thank you for reporting this.

Do you have a reproduction?
A minimal vite project we can run and inspect?

A stacktrace might also help, but probably won't allow us to resolve this without also a minimal repro.

**Comment by Mouvedia** [comment] 2024-10-14 19:11
@michwads can you try `"stylelint": "github:mouvedia/stylelint#mouvedia-8044"`?

**Comment by michwads** [comment] 2024-10-14 19:30
@Mouvedia still the same error >

[vite] Internal server error: Cannot read properties of undefined (reading 'config')
[vite] Pre-transform error: Cannot read properties of undefined (reading 'config')

**Comment by Mouvedia** [comment] 2024-10-14 19:45
Without you providing a MRE like requested by @romainmenke I can only guess that this line might be the culprit:

https://github.com/stylelint/stylelint/blob/c360343410cd92560ed48f6684d26c7177c4c7a5/lib/utils/getFormatter.mjs#L33

**Comment by ybiquitous** [comment] 2024-10-16 05:21
Yeah, we need a reproduction to investigate the problem. Please consider providing it. 🙏🏼 

---

I'm not 100% sure, but I doubt this line cannot raise the error because `configForFile?.config` returns `undefined` if `configForFile?` is `undefined`: 🤔 

```js
formatter = configForFile?.config.formatter; 
```

**Comment by Mouvedia** [comment] 2024-10-16 06:16
I was picking this line because it's part of https://github.com/stylelint/stylelint/compare/16.9.0...16.10.0 and `config` is `any`.
It's a guessing game at this point; let's wait for the MRE.

**Comment by Mouvedia** [comment] 2024-10-27 03:33
@michwads without any response from you, Ill have to close this issue at the end of the month.

**Comment by romainmenke** [comment] 2024-10-27 09:17
I was able to replicate this, in our own benchmark script 😅.
Working on something else, so not investigating further at this time.
You can trigger the error with:

```
node benchmark-rule.mjs value-keyword-case '["upper"]'
```

**Comment by Mouvedia** [comment] 2024-10-27 09:40
#8009 is the culprit
see also https://github.com/stylelint/stylelint/pull/8009#issuecomment-2380624578

**Comment by ybiquitous** [comment] 2024-10-27 09:51
`scripts/benchmark-rule.mjs` seems like a special use case for our internal use. 🤔 

https://github.com/stylelint/stylelint/blob/b6e6a719e0e9924b60ca2b7fc1b989ab3e2f8a07/scripts/benchmark-rule.mjs#L9

https://github.com/stylelint/stylelint/blob/b6e6a719e0e9924b60ca2b7fc1b989ab3e2f8a07/scripts/benchmark-rule.mjs#L66

Have we documented to support this usage of `lib/rules/index.mjs`?

**Comment by Mouvedia** [comment] 2024-10-27 10:02
@ybiquitous what we documented is https://stylelint.io/developer-guide/rules#improve-the-performance-of-a-rule which used to work.

**Comment by ybiquitous** [comment] 2024-10-27 12:28
Yes, the benchmark script is documented, and so it should be fixed immediately. However, the script's implementation doesn't depend on the public API and is fragile.

I guess this usage of `lib/rules/index.mjs` might be unsupported. 🤔

**Comment by ybiquitous** [comment] 2024-10-27 12:30
So, I'm still not sure if the original issue #8030 has the same problem as the benchmark's one.

**Comment by romainmenke** [comment] 2024-10-27 12:45
> So, I'm still not sure if the original issue https://github.com/stylelint/stylelint/pull/8030 has the same problem as the benchmark's one.

I think that `#8030` is completely unrelated to this issue.
I think @michwads just happened to find that pull request by searching for `config`.

-------

I agree that we can't know this for sure if what we see in our own benchmark script is the same kind of problem as reported in this issue.
Even a stack trace might be able to tell us more.

But I also think it is very unlikely that we get the same error messages as the original reporter and that the root cause would be something unrelated.

----

I do agree that this might be an unsupported way of using Stylelint.

I did try searching for other people reporting this issue in Vite repo's but I couldn't find any.
We also didn't get any other report, +1's in this issues, ...

So I am guessing that @michwads has a very custom setup and that this isn't a widespread issue?

**Comment by ybiquitous** [comment] 2024-10-27 12:54
Agree with @romainmenke. I've reverted the issue status.

If there are no actions from the original reporter in a few weeks, I think we can close this.

**Comment by Mouvedia** [comment] 2024-10-27 13:05
> I do agree that this might be an unsupported way of using Stylelint.

I knew that when I sent the PR.
i.e. our types may be too strict

> So, I'm still not sure if the original issue https://github.com/stylelint/stylelint/pull/8030 has the same problem as the benchmark's one.

Check https://github.com/stylelint/stylelint/compare/16.9.0...16.10.0.
As @romainmenke said, it's unlikely that it wouldn't be that.
Granted since `stylelint` isn't optional, it's not a bug.

**Comment by Mouvedia** [comment] 2024-11-06 08:03
Without any MRE after 3 weeks, [`stylelint` being required](https://github.com/stylelint/stylelint/blob/13933eda2c6430ea2c595f02f47799adbda771df/types/stylelint/index.d.ts#L172) and #8090 merged, I am closing this issue as _by design_.
It may be reopened if we were to decide to change the type of `PostcssResult['stylelint']`.

**Closed by Mouvedia** 2024-11-06 08:03 UTC
Labels: status: needs reproducible example
