### ISSUE TITLE
/* stylelint-disable */ multi-line comments polluting expanded CSS

### ISSUE THREAD

**Issue by djibe** [stylelint/stylelint#4927] opened 2020-09-07 11:28 UTC
Hi,

with latest stylelint, I had to switch all my `// stylelint-disable` comments to multi-line ones `/* stylelint-disable */` in order to bypass errors.

This means that SASS will keep these (as they are multi-line comments) in compiled CSS.

Is there an option to keep the single-line comment in Stylelint ?
Or how to remove those `/* stylelint-disable */` comments from CSS ?

Thanks a lot.

**Comment by angelikatyborska** [comment] 2020-09-07 14:17
I experienced the same issue with version 13.7.0 but the problem is already fixed on master (see: https://github.com/stylelint/stylelint/blob/master/CHANGELOG.md#head).

**Comment by ThiefMaster** [comment] 2020-09-07 15:58
A patch release for this would be great so people don't have to downgrade or edit their files...

**Comment by malsf21** [comment] 2020-09-09 06:06
@stylelint/core any chance we could push a quick `13.7.1`?

**Comment by hudochenkov** [comment] 2020-09-11 20:47
13.7.1 is released, which should have fixed this problem.

**Closed by hudochenkov** 2020-09-11 20:47 UTC
