### ISSUE TITLE
`npm run` hides config errors?

### ISSUE THREAD

**Issue by cmalard** [stylelint/stylelint#2909] opened 2017-09-20 14:11 UTC
> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

A bug where `npm run stylelint` hide config errors
```json
  "scripts": {
    "stylelint": "stylelint client/**/*.scss",
  },
```

While :
```shell
npx stylelint client/**/*.scss
Error: Undefined rule foo
    at module.exports (/home/cedric/Projects/shippeo.frontend/node_modules/stylelint/lib/utils/configurationError.js:8:28)
    at Object.keys.forEach.ruleName (/home/cedric/Projects/shippeo.frontend/node_modules/stylelint/lib/augmentConfig.js:302:13)
    at Array.forEach (<anonymous>)
    at normalizeAllRuleSettings (/home/cedric/Projects/shippeo.frontend/node_modules/stylelint/lib/augmentConfig.js:297:29)
    at augmentConfigBasic.then.then.then.augmentedConfig (/home/cedric/Projects/shippeo.frontend/node_modules/stylelint/lib/augmentConfig.js:91:14)
    at <anonymous>

```

> What stylelint configuration is needed to reproduce this issue?

```json
{
  "rules": {
    "foo": true
  }
}
```

> Which version of stylelint are you using?

 `8.1.1`

> What did you expect to happen?

See the error

> What actually happened (e.g. what warnings or errors you are getting)?

Everything looked good, as if there are no errors at all.

**Comment by jeddy3** [comment] 2017-09-21 08:19
@cmalard Thanks for the report and for using the template.

I'm unable to reproduce this locally. Both `.node_modules/.bin/stylelint` and `npm run stylelint` throw `Error: Undefined rule foo`. Can you please create the smallest reproducible test repo, so we can help further?

**Comment by jeddy3** [comment] 2017-09-21 18:15
Closing for now, feel free to reopen if you're able to create a  reproducible test repo.

**Closed by jeddy3** 2017-09-21 18:15 UTC
Labels: status: needs investigation

**Comment by cmalard** [comment] 2017-09-21 19:34
Well, can't reproduce either, no idea what happened ! :open_mouth:
