### ISSUE TITLE
You tried to parse SCSS with the standard CSS parser; try again with the postcss-scss parser

### ISSUE THREAD

**Issue by szmxx** [stylelint/stylelint#7082] opened 2023-07-15 07:53 UTC
### What minimal example or steps are needed to reproduce the bug?

【Vue3 + Vite + Typescript + Eslint + Prettier + Stylelint】
- Upgrade all dependencies of the project to the latest version
- npm run dev
- show details
<img width="1152" alt="image" src="https://github.com/stylelint/stylelint/assets/24505926/72a84131-75d1-4692-81a5-3f12a061cf20">
- Rolling back project dependencies has no effect

[Reproduce the code](https://github.com/szmxx/vite-template/tree/visual-demo)

### What minimal configuration is needed to reproduce the bug?

{
  "extends": [
    "stylelint-config-standard",
    "stylelint-config-standard-scss",
    "stylelint-prettier/recommended"
  ],
  "plugins": ["stylelint-order"],
  "customSyntax": "postcss-scss",
  "rules": {
    "scss/at-function-pattern": [
      "^[a-z][a-zA-Z0-9]+$",
      {
        "message": "Expected class selector to be camelCase"
      }
    ],
    "function-name-case": [
      "lower",
      {
        "ignoreFunctions": ["/^get.*$/"]
      }
    ],
    "at-rule-no-unknown": null,
    "function-no-unknown": null,
    "order/order": ["custom-properties", "declarations"],
    "order/properties-order": [
      "position",
      "top",
      "right",
      "bottom",
      "left",
      "z-index",
      "display",
      "justify-content",
      "align-items",
      "float",
      "clear",
      "overflow",
      "overflow-x",
      "overflow-y",
      "margin",
      "margin-top",
      "margin-right",
      "margin-bottom",
      "margin-left",
      "border",
      "border-style",
      "border-width",
      "border-color",
      "border-top",
      "border-top-style",
      "border-top-width",
      "border-top-color",
      "border-right",
      "border-right-style",
      "border-right-width",
      "border-right-color",
      "border-bottom",
      "border-bottom-style",
      "border-bottom-width",
      "border-bottom-color",
      "border-left",
      "border-left-style",
      "border-left-width",
      "border-left-color",
      "border-radius",
      "padding",
      "padding-top",
      "padding-right",
      "padding-bottom",
      "padding-left",
      "width",
      "min-width",
      "max-width",
      "height",
      "min-height",
      "max-height",
      "font-size",
      "font-family",
      "font-weight",
      "text-align",
      "text-justify",
      "text-indent",
      "text-overflow",
      "text-decoration",
      "white-space",
      "color",
      "background",
      "background-position",
      "background-repeat",
      "background-size",
      "background-color",
      "background-clip",
      "opacity",
      "filter",
      "list-style",
      "outline",
      "visibility",
      "box-shadow",
      "text-shadow",
      "resize",
      "transition"
    ]
  },
  "ignoreFiles": ["node_modules/**", "dist/**", "build/**", ".git/**", "*.js"],
  "overrides": [
    {
      "files": ["*.(html|vue)", "**/*.(html|vue)"],
      "customSyntax": "postcss-html",
      "extends": [
        "stylelint-config-standard-vue/scss",
      ]
    }
  ]
}

### How did you run Stylelint?

- npm run style
- its normal
<img width="843" alt="image" src="https://github.com/stylelint/stylelint/assets/24505926/36f3db5f-7fd8-4be8-9544-c85d9b87f5c0">

### Which Stylelint-related dependencies are you using?

{
  "name": "vite-ts",
  "private": true,
  "version": "0.0.0",
  "scripts": {
    "dev": "vite --host",
    "build": "vue-tsc --noEmit && vite build",
    "preview": "vite preview --host",
    "prepare": "husky install",
    "lint": "eslint --ext .ts,vue,tsx --ignore-path .gitignore .",
    "style": "stylelint src/**/*.{css,scss,vue}",
    "lint:markup": "vue-tsc --noEmit",
    "commit": "git-cz",
    "test": "vitest dev",
    "ui": "vitest --ui",
    "coverage": "vitest run --coverage"
  },
  "dependencies": {
    "@amap/amap-jsapi-loader": "^1.0.1",
    "@antv/l7": "^2.17.4",
    "@antv/l7-maps": "^2.17.4",
    "@floating-ui/dom": "^1.4.5",
    "@iconify-json/carbon": "^1.1.18",
    "@iconify-json/iconoir": "^1.1.29",
    "@iconify-json/mdi": "^1.1.53",
    "@turf/turf": "^6.5.0",
    "@vueuse/core": "^10.2.1",
    "@vueuse/integrations": "^10.2.1",
    "@wangeditor/editor": "^5.1.23",
    "@wangeditor/editor-for-vue": "^5.1.12",
    "axios": "^1.4.0",
    "echarts": "^5.4.2",
    "element-plus": "^2.3.8",
    "handlebars": "^4.7.7",
    "inquirer": "^8.0.0",
    "jszip": "^3.10.1",
    "lodash-es": "^4.17.21",
    "lodash-unified": "^1.0.3",
    "mitt": "^3.0.1",
    "monaco-editor": "^0.40.0",
    "nprogress": "^0.2.0",
    "pinia": "^2.1.4",
    "postcss-scss": "^4.0.6",
    "pretty": "^2.0.0",
    "qiankun": "^2.10.11",
    "spark-md5": "^3.0.2",
    "style-to-js": "^1.1.3",
    "stylelint-config-html": "^1.1.0",
    "stylelint-scss": "^5.0.1",
    "telejson": "^7.1.0",
    "universal-cookie": "^4.0.4",
    "vue": "^3.3.4",
    "vue-grid-layout": "^3.0.0-beta1",
    "vue-request": "^2.0.3",
    "vue-router": "^4.2.4",
    "vuedraggable": "^4.1.0"
  },
  "devDependencies": {
    "@commitlint/cli": "^17.6.6",
    "@commitlint/config-conventional": "^17.6.6",
    "@commitlint/cz-commitlint": "^17.5.0",
    "@types/echarts": "^4.9.18",
    "@types/jsdom": "^21.1.1",
    "@types/lodash": "^4.14.195",
    "@types/lodash-es": "^4.17.8",
    "@types/node": "^20.4.2",
    "@types/nprogress": "^0.2.0",
    "@types/spark-md5": "^3.0.2",
    "@unocss/preset-icons": "^0.53.5",
    "@vitejs/plugin-vue": "^4.2.3",
    "@vitejs/plugin-vue-jsx": "^3.0.1",
    "@vitest/ui": "^0.33.0",
    "@vue/eslint-config-prettier": "^7.1.0",
    "@vue/eslint-config-typescript": "^11.0.3",
    "@vue/test-utils": "^2.4.0",
    "c8": "^8.0.0",
    "commitizen": "^4.3.0",
    "eslint": "^8.45.0",
    "eslint-plugin-vue": "^9.15.1",
    "husky": "^8.0.3",
    "jsdom": "^22.1.0",
    "jsonc-eslint-parser": "^2.3.0",
    "lint-staged": "^13.2.3",
    "postcss-html": "^1.5.0",
    "prettier": "^3.0.0",
    "sass": "^1.63.6",
    "stylelint": "^15.10.1",
    "stylelint-config-standard": "^34.0.0",
    "stylelint-config-standard-scss": "^10.0.0",
    "stylelint-config-standard-vue": "^1.0.0",
    "stylelint-order": "^6.0.3",
    "stylelint-prettier": "^4.0.0",
    "terser": "^5.19.0",
    "typescript": "^5.1.6",
    "unocss": "^0.53.5",
    "unocss-preset-scrollbar": "^0.2.1",
    "unplugin-auto-import": "^0.16.6",
    "unplugin-icons": "^0.16.5",
    "unplugin-vue-components": "^0.25.1",
    "unplugin-vue-define-options": "^1.3.11",
    "vite": "^4.4.4",
    "vite-plugin-inspect": "^0.7.33",
    "vitest": "^0.33.0",
    "vue-tsc": "^1.8.5"
  },
  "lint-staged": {
    "src/**/*.{json,md,vue}": "prettier -w -u",
    "docs/**/*.{json,md,vue}": "prettier -w -u",
    "*.{js,jsx,ts,tsx,vue}": "npm run lint --fix",
    "*.{less,sass,css,scss,vue}": "npm run style --fix"
  },
  "config": {
    "commitizen": {
      "path": "@commitlint/cz-commitlint"
    }
  }
}

### What did you expect to happen?

Everything can be up and running

### What actually happened?

The project cannot run

**Comment by jeddy3** [comment] 2023-07-17 18:11
Closing as non-minimal example.

@szmxx You're welcome to reopen with a _minimal_ example that shows the problem is with Stylelint itself, rather than another tool or 3rd party integration.

**Closed by jeddy3** 2023-07-17 18:11 UTC
Labels: status: needs reproducible example
