### ISSUE TITLE
PostCSS 5.0 version

### ISSUE THREAD

**Issue by davidtheclark** [stylelint/stylelint#349] opened 2015-08-19 23:29 UTC
Looks like it was just released: https://github.com/postcss/postcss/releases/tag/5.0.0

I think we'll have to make some adjustments to accommodate breaking changes PostCSS API (like `.before` data moving).

Then we can use 5.0 to start working on more accurate error reporting.

Maybe we should start a branch for the changes that will work with PostCSS 5.0 and will break if people use an earlier version of PostCSS -- make it ready then decide when to release.

Thoughts?

**Comment by jeddy3** [comment] 2015-08-20 10:07
> Looks like it was just released: https://github.com/postcss/postcss/releases/tag/5.0.0

Great news!

> I think we'll have to make some adjustments to accommodate breaking changes PostCSS API (like .before data moving)

Yeap, it looks that way. I'll probably have time to have a poke around this afternoon, but I won't be able to take a proper look until next week.

> Then we can use 5.0 to start working on more accurate error reporting.

Excellent! 

> Maybe we should start a branch for the changes that will work with PostCSS 5.0 and will break if people use an earlier version of PostCSS -- make it ready then decide when to release.

Agreed. This seems like the most sensible approach.

**Comment by davidtheclark** [comment] 2015-08-20 12:28
Ok. I will not have any time until the middle of next week, so I will catch up then.

**Comment by jeddy3** [comment] 2015-08-23 17:56
I spent a couple of hours on this trying to track down the source of 3 failing tests that occur when using `5.0.2`. I'm going to hold off doing any more because I think a second pair of eyes later in the week would be very useful. I suspect I'm missing something really obvious to with the use of `node.toString` in `block-opening-brace-newline-after`.

**Comment by davidtheclark** [comment] 2015-08-27 01:53
I think this is causing problems: https://github.com/postcss/postcss/issues/522

**Comment by davidtheclark** [comment] 2015-08-27 01:54
Also this: https://github.com/postcss/postcss/issues/521

**Comment by davidtheclark** [comment] 2015-08-27 01:56
I committed some initial compat changes here: d620dae05c763401b197d13ee958ebf5c549ee34

The tests are not yet passing *at least* because of the two issues mentioned above.

**Comment by jeddy3** [comment] 2015-08-27 12:24
Thanks for making a start on this! I had another go yesterday, but ran into those same two issues as you. I wasn't sure if I was heading down the right road or making more work, as, after disabling the tests that caused those aforementioned errors, I ran into a problem with `no-eol-whitespace` and, I think, the use of `line` in `report`. I wasn't able to track down the cause of this one though, so I'd hoped you'd have better luck with it all than I. Sorry I wasn't more help!

**Comment by davidtheclark** [comment] 2015-08-27 13:51
Latest push to the `valac-compat` branch has all tests passing!

I want to try tinkering with the positioning, though, before we release this version — because one of valac's features is that we should be able to get more accurate positioning.

**Comment by jeddy3** [comment] 2015-08-27 14:06
> Latest push to the valac-compat branch has all tests passing!

Thanks so much for this! Soz again for lacking the confidence in my understanding of the code base to raise those issues myself in postcss issue-tracker.

> I want to try tinkering with the positioning, though, before we release this version

Agreed. That would be sweet! :)

**Comment by isellsoap** [comment] 2015-09-02 20:05
I’m really looking forward to this. Thanks a lot for your work!

**Comment by jeddy3** [comment] 2015-09-02 21:53
FYI, progress towards this is being tracked in #133 and #355 .

**Comment by jeddy3** [comment] 2015-09-04 14:55
Not that I can think of.

**Comment by jeddy3** [comment] 2015-09-05 18:56
Released as [`1.0.0`](https://github.com/stylelint/stylelint/releases/tag/1.0.0)

**Closed by jeddy3** 2015-09-05 18:56 UTC
Labels: status: wip

**Comment by jeddy3** [comment] 2015-09-05 19:02
:tada:
